dotnet/wcf

build.cmd

*Previously we only support passing OuterLoop parameter:
/p:WithCategories=OuterLoop
* The change adds parsing command line parameters.
We will be able to pass more than one parameter, such as
build /p:Coverage=true /p:WithCategories=OuterLoop

Support more than one parameter to build.cmd for OuterLoop Tests

---

.gitignore
src/System.Private.ServiceModel/src/project.lock.json
src/System.Private.ServiceModel/tests/project.lock.json
src/System.ServiceModel.Duplex/tests/project.lock.json
src/System.ServiceModel.Http/tests/project.lock.json
src/System.ServiceModel.NetTcp/tests/project.lock.json
src/System.ServiceModel.Primitives/tests/project.lock.json
src/System.ServiceModel.Security/tests/project.lock.json
src/System.ServiceModel.Tests.Common/src/project.lock.json

The project.lock.json file must be added to the repo
to ensure building against the correct versions.
This matches how CoreFx handles them.

Add project.lock.json files for product and unit tests

---

dir.props
dir.targets
src/.nuget/packages.Windows_NT.config

The CoreFx repro has updated its common targets files to
restore the build tools.  We track whenever these change
and keep our repo up to date. This is necessary to permit
building the OSS projects in the TFS mirror.

Copy common target files from CoreFx to restore build tools

---

src/System.Private.ServiceModel/src/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenarios.Common/project.lock.json
src/System.Private.ServiceModel/tests/project.lock.json
src/System.ServiceModel.Http/tests/project.lock.json
src/System.ServiceModel.NetTcp/tests/project.lock.json
src/System.ServiceModel.Primitives/tests/project.lock.json
src/System.ServiceModel.Security/tests/project.lock.json
src/System.ServiceModel.Tests.Common/src/project.lock.json

sets the 'locked' value to true for all project.lock.json files.
Also adds project.lock.json files for refactored scenario tests.
Setting the 'locked' value prevents package restore from
attempting to resolve package versions again and update
the project.lock.json file.
This both locks down the actual versions as well as prevents
the TFS mirror from attempting to write to a readonly file.

Set locked = true for all project.lock.json

---

src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml
src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/project.lock.json

These changes allow the main product to be built for
NET Native conditionally.  This is not the default but
is used when building the NuGet packages in the TFS mirror.
This commit also adds an embedded rd.xml when the project
is compiled for NET Native.
Fixes #60

Enable conditional building for Net Native

---

dir.props
src/.nuget/packages.Windows_NT.config
src/.nuget/packages.config

Fixes packages restore issues. 
This meant that workspaces where the packages/ directory wasn't deleted would continue to build
fine, but as soon as a clean build was done, nothing would succeed anymore.

Update buildtools to 1.0.25-prerelease-00053

---

CONTRIBUTING.md
README.md

The old links to wiki has been broken after we moved wiki to the documentation folder.
The links are updated to pointing to the new documentation location.

Fix broken wiki links

---

dir.props
src/System.Private.ServiceModel/src/Mockups/System.cs
src/System.Private.ServiceModel/src/System/IdentityModel/CryptoHelper.cs
src/System.Private.ServiceModel/src/System/IdentityModel/HashStream.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SymmetricKey.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SymmetricSecurityKey.cs

There are some internal builds that use a slightly different compiler version,
which means that while this code works with build.cmd from Git, it doesn't
work with the toolchain we use for these builds.
These changes will mean that we build on the build systems we're aware of.

Change some pragmas to format supported by internal build tools

---

src/System.ServiceModel.Tests.Common/src/BaseAddress.cs
src/System.ServiceModel.Tests.Common/src/System.ServiceModel.Tests.Common.csproj

With this change, you can specify /p:UseFiddler=true to build.cmd and the special hostname
localhost.fiddler will be used. This causes the localhost proxy bypass to be skipped and the
requests will be put through the defined proxy server. Fiddler then strips off the .fiddler
from the hostname and passes on the request with the Host being just localhost.
Some tests fail when using fiddler as the failure mode changes and there's not a lot we can
do about that, but this does give greater flexibility to debugging product/test issues.

Add support for tests to use fiddler proxy

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs
src/System.ServiceModel.Duplex/tests/ServiceModel/CallbackBehaviorAttributeTest.cs
src/System.ServiceModel.Primitives/tests/Description/ContractDescriptionTest.cs
src/System.ServiceModel.Tests.Common/src/BaseAddress.cs
src/System.ServiceModel.Tests.Common/src/ServiceInterfaces.cs
src/System.ServiceModel.Tests.Common/src/TestHelpers.cs

Adds code to extract the ContractCallbackType property from
ServiceContractAttribute and ensures it is properly initialized
in the ContractDescription.
Adds a unit test for this change and enhances the unit tests of the
CallbackBehaviorAttribute that is instantiated by this change.
Fixes #92

Enables the CallbackContractType in ContractDescription

---

src/System.ServiceModel.Tests.Common/src/ServiceInterfaces.cs

This property is not part of the public contract but was
being used inadvertantly by a unit test.  Removes that usage.

Remove use of ServiceContractAttribute.SessionMode

---

src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs

The NET Native version of xunit does not support
Assert.IsAssignableFrom, so this change removes that
usage and does explicit IsAssignable checks.

Eliminate use of xunit Assert.IsAssignableFrom

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ProducerConsumerStream.cs

Build warnings were produced due to fields not being CLS-compliant
and Equals being overridden without overriding GetHashcode.
These warnings caused the build to fail when building the
TFS mirrored sources with warnings treated as errors.

Fix build warnings

---

src/dir.props
src/test.props

Once dotnet/buildtools#181 is fixed we should be able to remove this.

Enable building and debugging of test projects from visual studio

---

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs

* None of the tests are passing because of product issue 78
Fixes #97

Add test coverage for Async APIs with NetTcpBinding

---

src/System.Private.ServiceModel/tests/Common/TestPropertiesTest.cs
src/System.Private.ServiceModel/tests/System.Private.ServiceModel.Tests.csproj
src/System.ServiceModel.Tests.Common/src/System.ServiceModel.Tests.Common.csproj
src/System.ServiceModel.Tests.Common/src/TestProperties.cs
src/System.ServiceModel.Tests.Common/src/testproperties.props
src/System.ServiceModel.Tests.Common/src/testproperties.targets

A new TestProperties class is added together with a custom
task to generate a C# file to populate a dictionary with
MSBuild properties defined at build time.
This makes all the build-time MSBuild properties available
to tests at runtime.  This is necessary because the frameworks
on which these tests run do not support configuration files
or environment variables.
Fixes #29

Adds TestProperties class to capture MSBuild properties

---

dir.props

An issue with Dnu package restore running concurrently is preventing
builds from working correctly.  This change is temporary and allows
the build to succeed.  An issue will be opened to undo this change
when Dnu is fixed.

Temporarily make package restore not run concurrently

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs

DuplexClientBaseTests used ClientBase<T>.Close() which is public
but not available in the public contract.  So the test fails when
run against NET Native.  This change allows it to function in both
CoreCLR and NET Native.

Fix DuplexClientBaseTests use of Close()

---

src/dir.targets
wcf.targets

Adds override.targets to resemble how CoreFx includes multiple
product specific targets at build time.
Also adds wcf.targets that defines common properties and targets
necessary for wcf projects.

Add override.targets and wcf.targets

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

We had another failure in CI (http://dotnet-ci.cloudapp.net/job/dotnet_wcf_outerloop/396/) where we've been bitten by the lack of a good exception message. Well, no more! (for this test, at least). 
This PR changes some of the tests. Should help us uncover what's going on with #87 and is a start on #74

Change some ExpectedExceptionTests to show better exception messages

---

dir.props

The double-slashes for URL's in dir.props needed
to be escaped to match CoreFx's changes.

Escape URLs in dir.props

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

Our internal xunit-like framework for .NET Native doesn't support the use of Assert.Contains,
so for now, moving any Assert.Contains to using Assert.True instead. 
At a later date, we can consider moving back to Assert.Contains since the messages look nicer.

Changing ExpectedExceptionTests to not use Assert.Contains

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs

Enables DuplexClientBaseOfT_OverNetTcp_Call after PR #152 was merged
and enabled duplex operation.
Also updates [ActiveIssue] of ServiceContract_TypedProxy_DuplexCallback
to refer to new issue #157.

Enable previously skipped duplex scenario test

---

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/InvokerUtil.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/SyncMethodInvoker.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/TaskMethodInvoker.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.cs

Callback contracts with a return type of simply Task were working, but Task<T> were causing a null ref exception.

Fixing Callback contracts with a Task<T> return type

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs

TypeLoader uses Type.GetInterfaceMap() to find an implementation
method corresponding to a method from an interface.  But in
NET Native this method throws PlatformNotSupportedException.
As a consequence, Duplex does not work in NET Native.
This PR replaces the call to Type.GetInterfaceMap() with private
methods that find the implementation method based on the method name
and parameter types.
Fixes #153

Replace use of Type.GetInterfaceMap in TypeLoader

---

build.proj
dir.props
dir.targets
src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenarios.Common/ServiceModel.Scenarios.Common.csproj

CoreFx made some changes to alter how the DnuRestore worked
and to enable warnings as errors (which is how the projects
are built in the TFS mirrored location).  This PR brings those
changes to WCF.
It also fixes the one warning we had that caused the build to fail.

Integrate recent CoreFx changes to props and targets files

---

src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexClientBaseTest.cs

The DuplexChannelFactoryTests use APIs appearing only in the P2P contracts
and not in the public contract. As such, these tests fail to compile when
run in the experimental CoreCLR/NETNative test environment.
It uses forms of the ctor that take an Object, which are not supported in the contract.
Replace with using teh cotr that takes an InstanceContext instead
Fixes #171

Modify DuplexChannelFactoryTests to use APIs in public contract only

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/src/TestHelpers.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs

This was causing deadlocks when calling a Task based client synchronously, e.g. FooAsync().Result.
Fixes #78

Fix async channel open so that continuations don't use the current sync context

---

src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexClientBaseTest.cs

The Endpoints class is reserved for [OuterLoop] tests and
requires a running WCF Service.
This PR adds [ActiveIssue(178)] to all the Duplex unit tests
using Endpoints.  They need to be converted to use BaseAddress only.

Disable Duplex unit tests using Endpoints

---

src/System.Private.ServiceModel/tests/Common/src/BaseAddress.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexClientBaseTest.cs

The Duplex unit tests previously disabled with [ActiveIssue(178)]
have been re-enabled and modified to use static BaseAddress URL's
Fixes #178

Re-enables Duplex unit tests previously disabled

---

dir.props
src/.nuget/packages.Windows_NT.config
src/test.props

This change to build-tools permits F5 debugging in VS2015
without needing to run build.cmd each time.
It also reverts the work-around we had made to test.props for this.
Fixes #188

Update build-tools to version 58 to match CoreFx

---

tools/Bridge/Bridge/Bridge.csproj
tools/Bridge/Bridge/IdleTimeoutManager.cs
tools/Bridge/Bridge/OwinSelfhostStartup.cs

Default timeout is 10 minutes to avoid lingering processes. 
Ideally build.cmd should be calling ensurebridge just before executing the tests.

Enable IdleTimeout for Bridge.exe . Part of #198

---

src/System.Private.ServiceModel/tests/Common/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfService.csproj
wcf.targets

TestProperties contains a configurable property for the
location of the Bridge's resources.  This PR makes the
WcfService compile to that location, and the Bridge client
configures the Bridge using this location.
Fixes #186

Make Bridge use configurable location for resources

---

src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs

When some checks for Assert.True were done to verify the contents of an exception message, the Assert.True statement did not report the full failing exception message. 
Note - for #189 
DuplexChannelFactoryTest.CreateChannel_Using_Http_NoSecurity attempts to check
for the string 'IRequestChannel' inside the exception string of the InvalidCastException.
While CoreCLR reports this string, .NET Native does not report anything meaningful inside
the exception string - only "Arg_InvalidCastException" with no further details.
As such, we need to remove this check as it will never pass in .NET Native - even
though this check will work fine in CoreCLR.

Improve exception message reporting from Assert.True checks

---

src/System.Private.ServiceModel/tests/Common/src/TestTypes.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.lock.json

5fe8647 (#200) was merged around the same time as #177, but 5fe8647 was using a FaultException ctor that doesn't exist in the contract. When #177 was merged, this caused a build break.
After #177, `ExpectedExceptions/project.json` omitted a couple of project references. For some reason though, this issue didn't show up in our previous buddy builds or even in CI. 
All this should be caught during development time now that #177 is fixed.

Fixup p2p references and project.json files after #177

---

src/System.Private.ServiceModel/tests/Common/src/System.ServiceModel.Tests.Common.csproj

The TestProperties code-gen target was previously listed
as a DefaultTarget and executed when the project was built.
However the build tools Coverage targets execute only the
Build target and bypass this code-gen target.
This change moves this target into $(CoreCompileDependsOn) to
ensure it is called by any form of build.

Trigger TestProperties code-gen from CoreCompile

---

dir.props
src/.nuget/packages.Windows_NT.config

Code coverage builds were broken with the previous
version of build-tools.  Version 61 fixes that break.

Update build tools to version 61

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IService1.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.xproj
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.lock.json

These stress tests focus on using shared instances of WCF channel factories and channels by multiple threads. 
We group those instances in pools, and we group the scenarios that use them in static classes (with public static methods for easy consumption without any preliminary setup from various stress frameworks).
Some scenarios focus on just making WCF calls using a pool of already created channels while other scenarios open/close/recycle/abort channels and factories on some threads while simultaneously invoking service calls over other threads. 
We use a number of helper methods and classes to wrap the actual calls to WCF factories and channels and service calls in order to be able to verify invariants (e.g. events do get fired only once, things do get closed, etc - this list can be …

This is the initial commit for the stress tests.

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.lock.json

The prior versions of the .json files in
the stress folder were considered invalid
and caused a 'dnu restore' which updated
multiple project.lock.json files during the
build.
This change changes the project.json file to
resemble the other project.json's and also
adds the project.lock.json file produced by
the dnu restore.
This prevents dnu restore from running during
the build due to what it considered an invalid
lock file.

Modify the stress test project.*.json files

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/AppDomainManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Bridge.csproj
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ChangedEventArgs.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ConfigController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/IdleTimeoutManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceInvoker.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/BridgeConfiguration.cs

This PR allows the Bridge to accept an
idle timeout as one of the properties in
the POST config name/value pairs.  And it
sets the idle timeout manager to use that
as its new idle timeout between requests.
To avoid making the Bridge aware of all its
configuration sensitive types, this PR also adds
a new EventHandler for configuration changes.
Types that care about configuration changes register
to be notified of the change.
The ConfigurationExtensions class was updated to
use this same notification mechanism.  And it was
renamed to reflect its true purpose -- AppDomainManager.
Fixes #198

Make Bridge idle timeout configurable

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/AddressingVersion.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageVersion.cs
src/System.Private.ServiceModel/src/System/ServiceModel/EnvelopeVersion.cs

We were using string resources for storing string formats used in ToString() methods. This
meant on .Net Native release builds, the ToString() outputs would have the wrong value as
the string resource values are stripped in .Net Native release builds.
Fixes #225

Cleanup string resources

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpVerifyDNSResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

* This is one of the key scenarios for DnsEndpointIdentity
* Note that it will fail until all dependent features mentioned in the test resolved.

Verify Server Dns for NetTcp binding

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

* Throw the same exception type and message as desktop
in case of null/empty user name
Fix issue #224

Check null/empty user name

---

src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml

Prior to this change, using Reflection on the concrete duplex
callback type failed in NET Native because its metadata was not
available.
The modification to the rd.xml file allows the NET Native version
of System.Private.ServiceModel to use Reflection on any interface
type specified in [ServiceContract(CallbackContractType)]. This is
necessary to build OperationDescriptions for the callback type.
But this alone does not enable Reflection for the concrete type.
And TypeLoader analyzes the concrete type to locate custom
attributes that implement IOperationBehavior to add them to the
operation's behaviors.
The change to TypeLoader allows it to tolerate missing metadata
when it analyzes these custom attributes. Because the
[OperationBehavior] attribute is not available in a public contract, …

Enable duplex callback usage in NET Native

---

Documentation/cross-machine-test-guide.md
Documentation/developer-guide.md
src/System.Private.ServiceModel/tools/setupfiles/RunElevated.vbs
src/System.Private.ServiceModel/tools/setupfiles/SetupWCFTestService.cmd
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ConfigController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ensureBridge.ps1
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/PortManager.cs
startBridge.cmd

These changes allow the firewall rules created by the Bridge
to be scoped to specific IP's to allow them to be secured against
unauthorized access.
Remotely starting the Bridge has been made easier with a new script.
and a new markdown file describes how to run the Bridge remotely.

Improve Bridge firewall support

---

src/System.Private.ServiceModel/tools/test/Bridge/Bridge/BridgeController.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/AssemblyLoader.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs

The Bridge CertificateManager was using too simple
an algorithm to find an existing "localhost" certificate
and accidentally matched one already installed for IIS.
This caused the CI machine to fail OuterLoop https tests.
This change tightens the algorithm to locate only a
"localhost" certificate with a known issuer.

Fixes issue matching wrong localhost certificate

---

src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/TestHelpers.cs
src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs

* Cleanup a few interfaces no longer needed in unit common code
* Moved WcfDuplexServiceCallback to common code so it could be re-used
* Fixes #280

Adding IOperationBehavior unit test

---

src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/project.lock.json

This broke the internal .Net native build so adding the dependency back.

Adding back System.Net.Primitives dependency

---

.gitattributes
Documentation/building/cross-platform-testing.md
run-test.sh

The run-test.sh script is based heavily on the CoreFx version
and adds the additional logic to overlay WCF binaries.
The cross-platform-testing.md is also based heavily on the CoreFx
version and is updated for WCF.
Using the steps in cross-platform-testing.md, most WCF unit tests
pass in Linux.

Create script to run WCF tests in Linux

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tools/setupfiles/CleanupWCFTestService.cmd
src/System.Private.ServiceModel/tools/setupfiles/SetupWCFTestService.cmd
src/System.Private.ServiceModel/tools/test/Bridge.Build.Tasks/Bridge.Build.Tasks/ReleaseBridgeResourcesTask.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/AppDomainManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/BridgeController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ConfigController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/IdleTimeoutManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceController.cs
startBridge.cmd

Prior to this change, the BridgeResourceFolder was specified by
BridgeClient when tests ran.  However, this was not a valid
strategy for x-platform use, otherwise both client and Bridge
would need to share a x-OS folder.
With this change, Bridge.exe is required to have a BridgeResourceFolder
when it is asked to start, and the BridgeClient no longer alters that.
Also adds a 'reset' option to Bridge.exe so that when tests complete
the Bridge can be asked to release all remote resources.  They will
be reacquired the next time Bridge requests are made.
Also move the Http DELETE handling to the ResourceController where it
really belonged.  An Http DELETE to the /resource endpoint releases all
resources.
Fixes #334

Set BridgeResourceFolder at Bridge startup

---

Documentation/building/cross-platform-testing.md
run-test.sh
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tools/setupfiles/SetupWCFTestService.cmd
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/BridgeConfiguration.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/PortManager.cs

These changes make it possible to tell the run-test.sh script
that OuterLoop tests should be included.  More work is required
to allow a CI machine to host a 2nd machine, but this PR makes
it possible to test manually.
This PR also enhances the error reporting from BridgeClient to
improve the debugging experience talking x-machine to the WCF
Bridge component.

Enable OuterLoop testing for x-plat

---

run-test.sh
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs

Two negative tests using known-unsupported Encodings were
failing due to issue https://github.com/dotnet/corefx/issues/2774
which returned UTF-8 for every unrecognized encoding.
Adds [ActiveIssue] to these tests using issue #333 which tracks
https://github.com/dotnet/corefx/issues/2774.  The [ActiveIssue]
disables these tests only on Linux.  They still execute on Windows.
Also modifies run-test.sh to exclude the TestRuntime folder from
CoreFx binaries when preparing the tests. The binaries in the WCF
test folders already contain the correct dependent binaries, and
allowing the TestRuntime folder to overwrite them gives out-of-date
or platform-incorrect binaries.
With these 2 changes, all unit tests not marked with [ActiveIssue]
pass on Linux.

Disable failing negative Encoding tests on Linux

---

dir.props
src/.nuget/packages.Windows_NT.config

Coverage broke with the update to build tools version -00089

Bump buildtools to version -00093 to fix code coverage

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/JsonSerializer.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceController.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceInvoker.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/AssemblyLoader.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/IResource.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/ResourceRequestContext.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/ResourceResponse.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/WcfTestBridgeCommon.csproj
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/BaseAddressResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs

Prior to these changes, invoking the IResource interface
on the Bridge did not pass any part of the request content
to the IResource.  After this change, the ResourceRequestContext
contains name/value pairs deserialized from the request content.
This change also solidifies the IResource contract so that the
Get and Put methods return a ResourceResponse rather than object.
This permits resources to return name/value pairs as well as to
receive them.
The Bridge Client was updated to expect a response containing
name/value pairs as json instead of the regex match.
The ResourceController was hardened to handle missing or
incomplete request content and to trace the incoming and
outgoing name/value pairs.
Fixes #353

Enable IResources to receive and return name/value pairs

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

* Test case name: SendTimeout_For_Long_Running_Operation_Throws_TimeoutException
* Updated it to provide the service operation with the timeout value to use on the server.
* Checking the elapsed time against an expected range still seems like the right thing to do.
* Fixes #273

Adding ActiveIssue for SendTimeout negative test.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/Infrastructure.Common.Tests.csproj

Renames the DLL generated by this project to match the
name of the folder and project.  This is necessary to
accommodate the run-test.sh conventions that assume the
DLL's match their folder and project names.
Fixes #376

Rename DLL generated by Infrstructure.Common.Tests

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj

Related to #385
In preparation for API changes to System.ServiceModel.Primitives and System.ServiceModel.NetTcp, we need to bump the minor version of System.Private.ServiceModel and wait for the nightly build to push out a new package

Bump System.Private.ServiceModel version to 4.1.0

---

netci.groovy

This is 3 parts:
1) Add outerloop testing definition.  Add an on demand PR trigger "@dotnet-bot test outerloop please" (tests debug and release outerloop) and a 4 hour rolling trigger.
2) Add coverage testing definition.   Add an on demand PR trigger "@dotnet-bot test code coverage please"
3) Move Linux testing into CI definition.  This is more complicated because of the number inputs and jobs required.  Will get simpler of course when there is native Linux building available.

Add the rest of WCF's test functionality

---

src/System.Private.ServiceModel/src/Mockups/ExtendedProtectionPolicy.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelBindingUtility.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityProtocolFactory.cs
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/project.lock.json

The System.Net.Security package is not available for UWP apps,
but WCF currently lists it as a dependency and uses it,
regardless of platform.  This causes UWP apps to fail in beta8.
The fix is to remove use of it when building for Net Native.
This PR is the first of 2.  The first adds conditional compilation
directives around code using System.Net.Security to exclude usage
when building for NET Native.
The 2nd PR will modify the project.json and project.lock.json files
to remove the dependency.
It is being done in 2 stages like this so that the code changes
can be integrated into the release branch for beta8 independently.
The change to the project*.json files will require careful planning
so that when integrated to the release branch it does not carry with
it the new (post-beta8) …

Remove code dependencies on System.Net.Security for NET Native

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/Connection.cs

Replace with Contract.Requires. With the generic Contract.Requires, an exception will be thrown in CoreCLR when this codepath is hit.
This blocks the TCP with security scenario

Remove Contract.Requires<Type> calls from files

---

src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/project.lock.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/project.lock.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/project.lock.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.lock.json
src/System.Private.ServiceModel/tests/Common/Unit/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/NetHttp/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.lock.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.lock.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.lock.json
src/System.Private.ServiceModel/tests/Unit/project.json
src/System.Private.ServiceModel/tests/Unit/project.lock.json
src/System.ServiceModel.Duplex/tests/project.lock.json
src/System.ServiceModel.Http/tests/project.lock.json
src/System.ServiceModel.NetTcp/tests/project.lock.json
src/System.ServiceModel.Primitives/tests/project.lock.json
src/System.ServiceModel.Security/tests/project.lock.json

There was a bug in System.Security.Claims that prevented our Ssl stream scenarios
from working. Moving the dependency for S.Security.Claims to depend on the -beta
versions so we can consume this change
Resolves #387

Move System.Private.ServiceModel to use new S.Security.Claims version

---

src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs

These tests were deactivated on Linux because Encoding had
not yet been implemented.  But this was fixed in CoreFx via
issue https://github.com/dotnet/corefx/issues/2774.

Reactivate negative encoding tests disabled for Linux

---

Documentation/certificate-generation-resources.md

After adding the certificate generation logic to the Bridge, we need to add some documentation to explain how it's used so people other than me can write tests against this resource :smile:

Add documentation for certificate generation resource

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

* Prior to moving to the Bridge this test worked as expected, since the move it looks like the
wrong ServiceHost is getting killed which can cause other tests to randomly fail.
* Due to other higher priority tasks just disabling this test for the short term.

Disabling test due to incorrect behavior on the Bridge

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/AddressingVersion.cs
src/System.Private.ServiceModel/src/System/ServiceModel/EnvelopeVersion.cs

* Const strings had already been included with the expected ToString formatting but the two ToString methods had not been updated and were still using SR.Format
* Fixes #323

Remove SR.Format calls and replace with string.Format

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs

* We use WebSocket.CloseAsync to close the WebSocket object. We do not dispose it
in normal Close case. We need to aggressively dispose it as WebSocket
is a disposable object and hold unmanaged resources.
Fixes #431

Dispose websocket object after Close

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TextMessageEncoder.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/OperationFormatter.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/StreamFormatter.cs

System.Runtime.Serialization.Xml implemented some async methods per our request (see https://github.com/dotnet/corefx/issues/2502). The fix is to use those methods in our code.
Fixes #218, #221, and #222.

Use new Implemented Async Methods in System.Runtime.Serialization.Xml

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateGenerator.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/EndCertificateResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/MachineCertificateResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/UserCertificateResource.cs

* Machine and user certs returned from the Bridge previously did not contain a private key, making some scenarios fail.
* BridgeClientCertificateManager will request User rather than Machine certificates
* BridgeClientCertificateManager will now check whether or not certificates were previously installed by opening the X509Store ReadOnly before attempting to install them
* BridgeClientCertificateManager error message for when an CryptographicException "Access Denied" is thrown improved
* Change the Bridge to install all "user" certs generated (not machine)
We need this so that localhost tests don't require elevation

Return certificates with private key from Bridge

---

src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/project.lock.json

The new dependency on 4.1.0 of System.Runtime.Serialization.Xml
caused a build break on TFS for TestNet.  Reverting to the prior
version solves the build break.
The 4.1.0 version contains fixes that WCF requires, but this lower
dependency is acceptable because the DNX will contain 4.1.0.

Lower dependency on System.Runtime.Serialization.Xml

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/NetHttp/WebSocketTests.cs

The WebSockets tests currently hang for long periods
on Linux.  This PR just disables those tests on Linux.
Issue #420 tracks fixing the issue and re-enabling the tests.

Disable WebSockets functional tests on Unix

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs

* Update identity positve test per cert generation changes in bridge.
* Enable the positve test because it's now pass as both product and cert
functionalities are in place.
* Add a negative test.
Fixes issue #368

Update Identity positive test and add a negative test

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrClientWebSocketFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TimeoutStream.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs

This is the first of 2 code improvement requests from the previous PR https://github.com/dotnet/wcf/pull/410. Since TimeoutHelper now create cancellation token asynchronously it make sense to allow caller to await on the creation of Cancellation token.
(Performance progression at about 1% in the Http scenario)

Allow caller to await on TimeoutHelper.CancelationToken

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrClientWebSocketFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TimeoutStream.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs

Reverts dotnet/wcf#427
It broke the build

Revert "Allow caller to await on TimeoutHelper.CancelationToken"

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

Test was disabled due to System.Security.Claims..ctor issue where the test-runtime
package was not up to date. Enable this test as test runtime package has now been
updated
Also change the endpoint so that we correctly obtain the DnsEndpointIdentity when
testing when the Bridge is located at an address other than the FQDN (e.g., when
testing against localhost or hostname)
Needs #457 to be merged first.

Enable TCP client credential test

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs

The streaming tests were disabled due to issue
https://github.com/dotnet/corefx/issues/4077.
But now that the issue is fixed, these tests pass again,
so this PR re-enables them. Verified in Linux too.

Reenable streaming tests after CoreFx fix

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/ClientCredentials.cs

The protected constructor and MakeReadOnly() method does not properly clone the _clientCertificate, _serverCertificate fields
Fixes #458

Fix System.ServiceModel.Description.ClientCredentials..ctor

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpTransportSecuritySslClientCredentialTypeCertificate.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

* Added a property in BridgeClientCertificateManager to hold the thumbprint of the ClientCertificate so that a test case can get it.
* Test sets the DnsEndpointIdentity to "localhost" which means this will only work when the Bridge and the test run on the same machine.
* Hong has a PR that adds a resource to the Bridge that will return the server Identity. I will update this PR to use that Resource
once her PR is merged, before I merge this one.
* Test currently fails due to Issue #458, added ActiveIssue

Adding primary scenario test for Issue #366

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.lock.json
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateCreationSettings.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateGenerator.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/WcfTestBridgeCommon.csproj
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateResourceHelpers.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/MachineCertificateResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/UserCertificateResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpExpiredServerCertResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

* Make cert parameters configurable by creating a CertificateCreationSettings.cs
and pass it around(Thanks for Jason's suggestion!). I have only added parameters
needed by the current invalid tests. I expect it will grow as we are adding more tests.
* Add expired certificate and custom validation fails tests.
Fixes #371

Make cert parameters configurable and add TCP negative security tests

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

In Windows, we read/write our certificates from/to the LocalMachine store.
On *nix, however, we only have access to the User store. The BridgeClient needs
to be aware of where it's running and switch the cert store used as necessary
Fixes #434

Add platform-dependent logic to BridgeClientCertificateManager

---

run-test.sh

Prior to this change the run-test.sh script used to run the tests
in Linux copied all the assemblies from the WCF bin folder into the
WCF test folders.  This was harmless when the assemblies were the
same but caused issues when the bin folder contains other versions
of the assemblies.
With this change, the script no longer copies assemblies from the
WCF bin folder but relies on the test folders containing all they need.

run-test.sh no longer copies binaries from WCF bin folder

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/WebSocketResources.cs

* Fixes #484
* Fixed an error getting the port number for the WebSocketHttpsDuplexBinaryStreamedResource, not caught earlier since all these tests are failing for other reasons.
* These new tests fail for the same high level reasons as their binary counterparts, but @mconnew in fixing the high level issues has reached a lower level issue where the type of encoding matters, so these tests may help him with his debugging efforts.

Adding text encoder variations to WebSocket scenario tests.

---

run-test.sh

This update the Linux script to run tests so that it invokes
the certificate cleanup logic after all tests are run.

Invoke CertificateCleanup.exe on Linux after all tests run

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

Mark all installed certificates as PersistKeySet; this seems to be a difference when
importing to the CurrentUser certificate store vs. the LocalMachine store in
Windows. This caused issues when attemtping to use the certificates in tests and
sems to avert the issue of the tcp tests running into the following excception:
```
System.ComponentModel.Win32Exception :
The credentials supplied to the package were not recognized
```
Fixes #495 (hopefully)

Mark client certs installed by BridgeClient as PersistKeySet

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TaskHelpers.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrClientWebSocketFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TimeoutStream.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/BridgeConfiguration.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/WebSocketResources.cs

1. HttpsChannelFactory was hard coded to throw on duplex contracts
2. TimeoutStream didn't override ReadByte and WriteByte which cause WebSocketStream.Read/Write to be called  
Fixes #468

Fix some WebSocket issues

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs

Two issues addressed here.
1. Switch to socket.ConnectAsync now that it's available
2. Enable HTTP streaming tests now that dotnet/corefx#4077 has been fixed
This required updating dependant versions to get the fixed networking builds

Use latest networking fixes

---

run-test.sh

Prior to this change, it was necessary to copy some binaries
from the CoreFx repo built on Linux when running tests.
This was necessary because the packages had incorrect binaries.
But that situation was resolved in preparation for RC1, and
it is no longer necessary to copy any binaries from CoreFx.
Fixes #442

No longer copy CoreFx binaries when running Linux tests

---

netci.groovy

There are some incompatibilites between CoreFX and CoreCLR, we need to
lock to a specific build of CoreCLR for testing for a bit of time.

Lock CoreCLR version

---

src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WSDuplexService.cs

Fixed WSDuplexService so it shouldn't throw unhandled exceptions any more
Added global exception handler to bridge default app domain (which will handle unhandled exceptions in all other app domains) so that we won't crash the process if something similar happens in the future.
Fixes #513

Stability improvments to WSDuplexService and Bridge

---

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs

This was accidentally added when debugging the failing WebSockets tests previously.

Remove accidental addition of S.N.WebSockets namespace

---

netci.groovy

This reverts the temporary fix in 367c3c8218d5571e94dbb531e28e584f4b835e07.
This was necessary to unblock Linux testing.
Now that the WCF repo carries the correct runtime-tools, it is
appropriate to use the latest successful builds, not a specific version.

Revert temporary fix to lock CoreCLR version

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/Connection.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/FramingChannels.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/StreamSecurityUpgradeInitiatorBase.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/StreamUpgradeInitiator.cs

Made ClientFramingDuplexSessionChannel.SendPreambleAsync use async methods.
Part of the fix for #303 .

 Light up async paths needed for Ssl StreamSecurity (I)

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageTests.cs

Added a scenario test that demonstrates the IClientMessageFormatter extensibility point works properly.
Fix #535.

Added a scenario test for IClientMessageFormatter.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/ClientCredentials.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/ClientCredentialsSecurityTokenManager.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/HttpDigestClientCredential.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientAuthenticationManager.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/AuthenticationResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/AuthenticationResourceHelper.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/DigestServiceAuthorizationManager.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/HttpDigestResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

Also fixing digest authentication to allow explicit credentials. There is currently an impersonation constraint which only makes sense with message security and we don't expose the property to modify it. I'm removing that constraint so that explicit credentials can be used.

Adding digest tests without domain controller

---

src/System.ServiceModel.Http/tests/Channels/WebSocketTransportSettingsTest.cs

The above test didn't build in TOF (because the Assert types in ToF do not support Func.) Changed the func to an action.
Fix #551

Fix DisablePayloadMasking_Property_Get_PNSE_Throws.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs

Now that we have started implementing the tokens/token parameters, we can now start implementing SecurityBindingElement.IsSetKeyDerivation instead of throwing `PlatformNotSupportedException`.
Fixes #540

Implement SecurityBindingElement.IsSetKeyDerivation

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/CustomAttributeProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/ServiceReflector.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

To enable it
* add back MessageParameterAttribute in CreateParameterPartDescription
* use methodInfo.ReturnParameter instead of methodInfo.ReturnType.
In the full framework, we use ReturnTypeCustomAttributes, it's essentially
ReturnParameter.
* Add a scenario test.
Fixes #527

MessageParameterAttribute for return response not working

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

* It's not necessary now as Jason has made window one cache entry per certificate
Fixes #533

Remove 2 minutes delay

---

src/System.Private.ServiceModel/src/System/IdentityModel/Claims/X509CertificateClaimSet.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateCreationSettings.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateGenerator.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateResourceHelpers.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpCertificateWithServerAltNameResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpRevokedServerCertResource.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

X509CertificateClaimSet should validate based on Subject Alternative Name instead of the Canonical Name to be consistent with Desktop .NET >= 4.6
Today, We are checking against the Subject (e.g. CN=host) on the certificate, to determine whether or not the cert was issued for a particular server, as this was the behaviour in <= 4.5. However, this is inflexible as the host could be serving the same cert but bound to multiple endpoints.
In the old case, for example, foo-bar.test.com != foo-bar, and a generated cert can only be valid for exactly one of these. In the new case, a certificate can have a Subject with a particular CN, but  multiple Subject Alt Names for which the cert is also valid.
In the wild, most certs issued already contain SANs for the names that the server can be, so we …

Validate X509CertificateClaims by SAN instead of by CN

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/ScenarioTestHelpers.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/ServiceContractAsyncInterfaces.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/ServiceContractAsyncServices.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/ServiceContractAsyncResources.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj

Adding ServiceContract tests for keyword 'out' and 'ref' variations.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportSecurityBindingElement.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Http/tests/ServiceModel/SecurityBindingElementTest.cs
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.Http/tests/project.lock.json

Follow up for #540, "Calling BasicHttpMessageSecurity.CreateMessageSecurity results in PNSE, "
Implement a test that exercises the codepath and check that the eventual call to SecurityBindingElement.IsSetKeyDerivation no longer throws

Verify that SecurityBindingElement.IsSetKeyDerivation no longer throws

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportDefaults.cs

Starting with PR https://github.com/dotnet/corefx/pull/4483
System.Net.Security does not support SSL3 in CoreFx.
Therefore we remove it from WCF's list of transport defaults.
Fixes #578, #579, #580, #581, #582, #583, #584, #585

Remove SSL3 from default protocols supported

---

release-notes/SupportedFeatures-v1.0.0-rc1.md

* The scenario table are updated according to test results on Asp.Net 5 and UWP.

Update RC1 release notes

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ProducerConsumerStream.cs

#116 disabled some compiler warnings after importing MessageContent.cs. We want to make sure that the class (and therefore the assembly) remains CLS compliant. 
@mconnew said in #116: 
> The compliance issue is that protected fields can't start with an underscore. What's the naming standard for protected fields? I would rather change the field names rather then disable the warning.
> If they are left as not CLS compliant, this simply means that those fields can't be accessed by code written in some other languages which only support CLS compliant assemblies. As this is only public to enable writing unit tests and isn't exposed on the contract, in practice this non-CLS compliance doesn't negatively affect any scenario.
The class was made public to enable unit tests... but our tests can …

Change MessageContent to internal class to fix CLS compliance

---

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs

Adds [ActiveIssue(625, PlatformID.AnyUnix)] to WebSockets tests
because they cannot pass until support has been added.
Support of WebSockets on Linux in CoreFx is tracked by issue
https://github.com/dotnet/corefx/issues/2486

Disable WebSockets tests on Linux

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs

These tests invoke code that causes failures in OuterLoop due to
the fact System.Security.Principal.Windows is not supported on Linux
but we still depend on it.  This causes the Windows assembly to be
used instead.
When #604 is resolved to remove this dependency we will need to
fix these tests or make them conditional on OS.

Disable Linux tests using System.Security.Principal.Windows

---

src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj

The last update to System.ServiceModel.Http (#634) didn't update the src/System.ServiceModel.Http.csproj version number. It looks like after #629 got merged, this issue surfaced where GenFacades complains about a version mismatch between the contract (ref/ directory) and the implementation (src/ directory) version.
Update System.ServiceModel.Http.csproj to assembly v4.1.0.0 to bring the csproj in line with the ref/csproj.

Update System.ServiceModel.Http.csproj to build v4.1.0.0

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs

* This flag is no longer needed according to Jason. 
Removing it because it requires we pre-create cert folders on Linux.

Remove OpenExistingOnly flag

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs

* this test is no longer needed as Matt has added a digest test without
the need of a domain.
Fixes #69

Remove Digest test that requires a domain

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/FaultExceptionTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

This PR adds a new scenario test that demonstrates primitive types
can be used in FaultContracts.  It is known to succeed in CoreCLR
but expected to fail in NET Native.
Making this test succeed in NET Native will occur in a different PR.

Add scenario test for FaultException using primitive type.

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

* we currently does not have OperationContextScope coverage. This is to
ensure we cover the major usage.
Fixes #655

Add a test to cover OperationContextScope major scenario

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

Includes two changes: 
* Modifies System.Private.ServiceModel.csproj to allow TargetsWindows condition to be set - this is consistent with https://github.com/dotnet/corefx/commit/9e1da13cf6d5ff4b37b1867beb3411a2fe61da6a
* Enables the NegotiateStream tests

Enable NegotiateStream tests for non-Unix platforms

---

build.proj
dir.props
src/NuGet.config
src/dirs.proj
src/packages.builds
src/ref.builds
src/src.builds
src/tests.builds

This PR copies files and.or edits from CoreFx to enable the packaging targets to build.  It does not yet build successfully, pending the merge of some open PR's to update some pkgproj files. I will rebase and update when those PR's are merged.

Enable the packaging targets to build

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

By default the PackageTargetFramework flows down to ProjectReferences for pkgprojs,
that is indended when referencing another pkgproj but not when you reference
a .builds or .csproj file as that will mess with the global properties for those
projects and cause race conditions.
cc @roncain @mconnew this should fix the race condition we have been seeing in TFS.
@ericstj we should probably fix this in packaging.targets directly. I know you had some other changes in the promoting of metadata to AdditionalProperties. As part of that can you please Undefine or not pass these properties for csproj/builds ProjectReferences.

Undefine PackagingTargetFramework property to avoid different global properties

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageEncoder.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/TextEncodingTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

Because we no longer have the ContentType class, we had previously added a PNSE exception in MessageEncoder.IsContentTypeSupported. This change restores the desktop framework implementation replacing ContentType with MediaTypeHeaderValue for parsing.

Message encoder content type fix

---

src/System.Private.ServiceModel/src/Internals/FxTrace.cs
src/System.Private.ServiceModel/src/Internals/System/Runtime/ExceptionTrace.cs
src/System.Private.ServiceModel/src/SMDiagnostics/System/ServiceModel/Diagnostics/ExceptionUtility.cs

* Change the base Event source name to System.ServiceModel as it
becomes internal to us now.
* The code logic for handling different Event level is the same as Desktop.
Fixes #690

Enable ETW when throwing exceptions

---

netci.groovy

* The value used for the parameter "/p:Configuration" will now be the OS name plus either Debug or Release.
* Like this: Windows_NT_Debug
* When the configuration is just "Debug" or "Release" WCF OuterLoop test projects are running against the wrong build of the product, there is broken logic in the build process around this which has not yet been figured out, this is a short term solution.
* Fixes Issue #731

Fixing command line used by Jenkins to build and run CI tests.

---

netci.groovy

* Line 277 the variable 'os' is not known, hardcoding it since calls to build.cmd and running OuterLoops can only be on Windows.

Fixing mistake in PR #739

---

.gitignore

The rule was also matching src/System.Private.ServiceModel/tools/* which meant new files in that folder were ignored

Fixing rule to ignore /Tools folder

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props

Currently, the expiration time for certificates is only 1 day, which means that keeping the Bridge open over multiple days will result in certs expiring, making debugging more difficult. Change this expiry time to 7 days so that a Bridge can be kept up for a longer period of time.

Increase Bridge CA cert expiry to 7 days

---

src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml

The NET Native toolchain has been improved to allow the instantiation
of open generics via a new entry in the rd.xml file.  This PR adds that
new line.
The rd.xml already had a similar line that permitted this
for generic types where the T was a class. That line has been left
unmodified to mitigate risk if a new WCF package is used with an
older toolchain.
An app was built containing this new syntax and compiled against the
older toolchain to demonstrate the new syntax would not break it.
Fixes #664

Update rd.xml to allow instantiation of open generic FaultException

---

netci.groovy

* Line 292 the variable 'os' is not known, hardcoding it since calls to build.cmd and running OuterLoops can only be on Windows.

Fixing mistake in PR #739 v2.

---

dir.props

Same changes as https://github.com/dotnet/corefx/pull/5665.
MSBuild uses `*` as a special character in `Include`, so I [escaped](https://msdn.microsoft.com/en-us/library/bb383819.aspx) the regexes. I also removed the TestData rule because it doesn't seem to be validateable: some packages are 1.0.0-prerelease and others are 1.0.1-prerelease, but TestData packages aren't produced in lockstep versions so this is normal.
cc @roncain @weshaggard

Escape *'s in validation regex

---

src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CompositeType.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

When XmlSerializerFormatAttribute is marked on a OperationContract, .Net Native tool assums that the operation wants to serialize objects using XmlSerializer and so pre-generates XmlSerializer for all relevant types. However, MessageHeader.CreateHeader() internally used DataContractSerializer to serialize the header object, even if the operation is marked with XmlSerializerFormatAttribute.
The fix is adding directives in the rd.xml to tell .Net Native tool to generate DataContractSerializer for the 'value' parameter of the MessageHeader.CreateHeader() method.
I also added tests covering the case of using MessageHeader.CreateHeader together with XmlSerializerFormatAttribute.
Fix #740

Fixed a bug with MessageHeader.CreateHeader().

---

src/System.Private.ServiceModel/tools/setupfiles/EnsureBridgeRunning.cmd
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/IdleTimeoutManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs

Prior to this change, the Bridge initialized its max idle
timeout to a fixed value and did not adjust for a value being
passed on the commandline at startup.
It was necessary to fix this issue so that a Bridge launched
on a lab machine can be given a maximum idle timeout.  This
permits the Bridge to close gracefully regardless how a test
run completes.

Make Bridge honor max idle timeout set from command line

---

src/System.Private.ServiceModel/tools/setupfiles/EnsureBridgeRunning.cmd
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs

The new /require option will ensure the Bridge is running.
If it is already running, it just returns.  But if it is not
running it starts the Bridge.exe in a new process and waits for
it to respond to pings.
This new option is not yet used but will be in automated runs
on Windows machines that require the Bridge is running before
a test can execute.

Adds new /require option to Bridge.exe to allow optional start

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.builds
src/System.Private.ServiceModel/pkg/unix/System.Private.ServiceModel.pkgproj
src/System.Private.ServiceModel/pkg/win/System.Private.ServiceModel.pkgproj

* WCF Core has a Windows and a Unix implementation both implementations need to be available in the package.
* Fixes Issue #749

Add a unix package of System.Private.ServiceModel

---

netci.groovy

Our Linux tests were not being run as corefx binaries were not being unpacked from the corefx build.pack. Unpack the artifacts from build.pack so that ./run-tests.sh can run in CI and produce us with test results

Add unpack step to netci.groovy for corefx binaries

---

build.cmd
dir.props
src/Common/test-runtime/LatestDependencies/project.json

* Use FloatingTestRuntimeDependencies=true to run against latest dependencies
* Fix the build script to allow config TestFixedRuntimeProjectJson
* Note that versions "4.0.11-rc3-23725" will be changed to "4.0.11-*" in
the build process and copy to a location used by the tests.
* Add default configration explcitly to work around the issue it will fail
if no build configration is specified

Enable running against latest dependencies

---

src/System.Private.ServiceModel/tools/test/Bridge/Bridge/AppDomainManager.cs
src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/AssemblyLoader.cs

The remote addresses property wasn't being set in the test resource app domain. This fix sets the PortManager.RemoteAddresses value in the new app domain to match what's in the default app domain.

Fix PortManager addresses for resource domain

---

build.sh

The CI machines don't seem to like using the v3 myget feeds right now, so move back to v2 feeds to unblock Linux testing in CI

Move build.sh back to v2 myget feeds to work around CI issue

---

netci.groovy

Change the dotnet-ci trigger phrases to call out "build and test" and call out "innerloop"

Change the verbage of dotnet-ci PR triggers

---

src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml

* This is needed to fix issue #769 from our side.
* Toolchain does not know we need this type and remove it during reduce
dependencies. Adding to rd.xml to explictly tell the toolchain we need it.
* I have verified the rd.xml fix worked by working around the toolchain bug 
189994: Reflection blocking applying to namespaces in unblocked assemblies.

Add OperationFault to rd.xml

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.builds
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj
src/System.ServiceModel.Duplex/src/project.json
src/System.ServiceModel.Http/src/System.ServiceModel.Http.builds
src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj
src/System.ServiceModel.Http/src/project.json
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.builds
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj
src/System.ServiceModel.NetTcp/src/project.json
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.builds
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj
src/System.ServiceModel.Primitives/src/project.json
src/System.ServiceModel.Security/src/System.ServiceModel.Security.builds
src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj
src/System.ServiceModel.Security/src/project.json
wcf.targets

Reverts dotnet/wcf#793
Seems to be a conflict with changes by Davis Goodin in TFS, reverting until we understand the changes he made and how they affect this PR.

Revert "Package S.P.SM as dotnet5.4 and consolidate facade builds."

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/ClientCredentials.cs

The initial porting work meant that some methods had functionality stripped to allow for compile. In this case, we stripped out the clone capability for the WindowsClientCredential and neglected to add it back when we were turning this capability back on
This is required for WindowsStreamSecurityUpgradePRovider to to successfully pass our creds along to the underlying NegotiateStream
(a big omission... a simple change... but boy this took forever to hunt down...)

Fix ClientCredential.Clone method which missed Windows credentials

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs

This test covers the scenario where two service contracts use the same namespace and contains the same operation. 
Fix #823

Add Test for the Scenario where Two Contracts use same Namespace.

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json

Issue #713 tracks the fact NetTcp streaming has not yet
been implemented.
This PR adds streaming tests for NetTcp which are marked
with [ActiveIssue] to suppress them until #713 is fixed.
Fixes #830

Add scenario tests for NetTcp streamed transfer mode

---

netci.groovy

This does some basic refactoring and simplification of the CI definition, as well as moving WCF to the branch based model (see below)
Move wcf to branch model
This moves wcf to the branch-based CI model.  In this model, instead of having the CI generate jobs out of dotnet/wcf's master branch for all branches (using all sorts of odd naming suffixes of course), the master CI lists tell the CI which branches it should look at for CI config info.  It passes the branch name to the netci file, which then can use it to tell the SCM to pull code from specific branches or set branch specific PR triggers.

[Do not Merge] Simplify and branchify the netci file

---

build.cmd
src/System.Private.ServiceModel/tools/test/Bridge/Bridge/Program.cs

This PR makes it possible for Bridge configuration properties
expressed at build time to be built into the test binaries.
And it also allows Build.exe to accept the MSBuild style of
property arguments.
This enables 2 important scenarios for our multi-machine effort.
1. Doing "build /p:BridgeHost=xyz" will generate the appropriate
TestProperties at compile time so that the generated test binaries
carry this information. Then if they are uploaded to Helix to
execute, they already carry the information necessary to communicate
with a Bridge on a different machine.  There is no need to set
environment variables on the execution machine for this.
2. By allowing Bridge.exe to parse the MSBuild style property
arguments, it allows our build scripts to flow Bridge configuration
information to the …

Allow MsBuild properties at build time to flow to the Bridge.

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestHelpers.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs

Some asserts in WebSockets tests were valid only when the
Bridge was running as localhost, but failed when running on
a different machine.
The change only modifies the assert to be tested if the Bridge
is running as localhost.
Fixes #677

Modify WebSocket test asserts to be correct cross-machine

---

src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs

* On cloud machines, the current logic to get FQDN does not work.
We need to append domain name cloudapp.net.
Fix #855

Fix FQDNs if the server hosted on a Cloud machine

---

src/System.Private.ServiceModel/tools/setupfiles/BridgeCertificateInstaller.sh

We need to make a call to the Bridge as the original user we sudo-ed from, as we need to write to the cert store for the current user, not as root. 
@dotnet-bot skip ci please - we are not equipped to do outerloop Linux tests yet in CI.

Change BridgeCertificateInstaller.sh to sudo as current user

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceKnownTypeTests.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs

If a ServiceContract is marked with XmlSerializerFormatAttribute, WCF would parse each operation of the service, generate a special XmlMapping object for the operation, and then generate a customized XmlSerializer instance for the operation based on the XmlMapping object. If the ServiceContract has a lot of ServiceKnownTypeAttribute, WCF might take a long time to generate the XmlMapping objects for the operations of the service. When generating an XmlMaping object for an operation WCF needs to call XmlReflectionImporter.IncludeType(Type) on every ServiceKnownType of the operation. This call is expensive. The ServiceContract defined in the [WcfPerfTest.zip](https://github.com/dotnet/wcf/files/132539/WcfPerfTest.zip), which was provided by @atanasa, contains 720 operations and each …

Made a performance improvement in XmlSerializerOperationBehavior.

---

build.cmd
src/dirs.proj
src/ref.builds
src/tests.builds

* Fix the clashes the tool found.
* Sync related files to the originals in corefx repo.
* Fixes #859

Add the BinClasher logger to our normal WCF build process.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props

* Currenty test timeout default value is 20 minutes. A test
could hang for 20 minutes before it times out. A typical test
should not run more than 1 minute.

Fix default test timeout

---

src/System.Private.ServiceModel/tools/test/BridgeCertificateInstaller/BridgeCertificateInstaller.csproj

* If not specificed it will trigger an AnyOS build of referenced assemblies in the project which triggers BinClasher errors.

Add default Configuration to BridgeCertificateInstaller.csproj

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/windows/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Common/Unit/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json

System.Runtime.Serialization.Xml 4.1.0 is now a stable package,
and the RC versions will become deprecated. This change updates
the previous dependencies from the RC to the stable version.

Update System.Runtime.Serialization.Xml dependency to stable version

---

.gitignore
BuildToolsVersion.txt
Packaging.props
build.cmd
build.proj
clean.cmd
dir.props
dir.targets
dir.traversal.targets
init-tools.cmd
src/NuGet.config
src/dir.props
src/dir.targets
src/dirs.proj
src/post.builds
src/tests.builds
sync.cmd

* Changes to dir.props and dir.targets made in corefx cause failures in WCF repo.
* Use of Roslyn compiler keeps around the task "VBCSCompiler.exe" which must be manually killed after each local build before running "git clean -xdf"
* There are a few files that either exist in corefx but not in Wcf or vice versa, am not using this PR to investigate those discrepancies.
* For sections where we have WCF specific changes I have added the comments "*** start WCF Content ***" and "*** end WCF Content ***", this should make it easier in the future to identify sections that can safely be ignored when diffing the files.

Syncing build scripts to corefx.

---

build.sh
dir.props

* The most recent sync to corefx build scripts pulled in the switch to remove any dependency on Mono
* The new version of MSBuild does not support CodeTaskFactory which we have used to generate TestProperties
* We will have to solve this issue but in the meantime it blocks our ongoing work
* This PR attempts to revert the specific changes that were made to remove the dependency on Mono

Temporarily revert back to prior version of MSBuild for Linux

---

src/System.Private.ServiceModel/tools/setupfiles/BridgeCertificateInstaller.sh

The downloaded cert was in some circumstances not chmodded to world writable, which meant that cURL would have trouble accessing the certificates when trying to establish an HTTPS connection
Not sure why this wasn't happening on my main dev box, but this problem exists on another box I spun up. 
@roncain, this should fix the problem you've been seeing when running outerloops on Linux and seeing the HTTP Security.TransportSecurity.Tests tests fail. 
You may need to remove all certs inside `/usr/local/share/ca-certificates/*` and re-run the BridgeCertificateInstaller in order to have this take. Also, please check the directory permissions on `/usr/local/share/ca-certificates` to ensure it's world-readable
skip ci please

Change BuildCertificateInstaller.sh to chmod downloaded cert

---

build.cmd

* commit e284227f820e2d0eb34d2b640e13acf71a7997e3 add
set "__args=%*", make __args the same as %*. thus we
pass commandline args twice to msbuild. This breaks
Helix, as Helix target does not allow two responses files
specified, even thougth they are the same
* The fix is to remove the redundancy.

Remove one of the duplicated commandline args

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets

The CodeTaskFactory feature is not supported in the CoreCLR
version of MsBuild.  This resulted in build failure on Linux
when we attempted to code-gen TestProperties building
tests/Common/Infrastructure.
This PR eliminates the use of CodeTaskFactory and massively
simplifies code generation to a single CDATA section.

Code generation of TestProperties no longer uses CodeTaskFactory

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs
src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs

Invoking operations on a channel that has AllowCookies = true currently fails with:
> Unhandled Exception: System.InvalidOperationException: When using CookieUsePolicy.UseSpecifiedCookieContainer, the CookieContainer property must not be null.
The root cause is that we didn't assign a CookieContainer to the winhttp handler.
Fix #853.

Enable AllowCookies=true.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs

On Linux, HttpClient returns an HResult with ERROR_INVALID_HANDLE
attempting to access an endpoint it cannot find. As a result, we
throw CommunicationException rather than EndpointNotFoundException.
This is inconsistent with Windows behavior and breaks a scenario
test for this case.
Until CoreFx provides a common way to map HResults to a predictable
set of values across platforms, we must map this specific HResult
manually in our exception conversion helpers.
Fixes #419

Map ERROR_INVALID_HANDLE to EndpointNotFoundException

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelFactoryBase.cs

Problem: ChannelFactory's async close was invoking its inner channelfactory's
async close only if it implemented IAsyncChannelFactory, otherwise it used
the synchronous close.  This led to stress issues where asynchonous closes
blocked threads.
Solution: make all channel factories declare they implement IAsyncChannelFactory.
IAsyncChannelFactory is only a tagging interface that wraps IChannelFactory and
IAsyncCommunicationObject.  And in practice, all channel factories were already
implementing both IChannelFactory as well as IAsyncCommunicationObject (because
their base class is CommunicationObject).  So the fix was only to add
IAsyncChannelFactory to their list of implemented interfaces.  This allowed
ChannelFactory to be able to call through to the async close on the base class …

Enable ChannelFactory to use async close of inner channel factory

---

src/System.Private.ServiceModel/src/System/ServiceModel/SpnEndpointIdentity.cs

This property exists in the public contract and needed to
be added back to fix a build break in TFS.

Add SpnLookupTime property back to SpnEndpointIdentity

---

src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs

PR #883 breaks one Tof test project because the PR used C#6 syntax.

Fix an Issue caused by PR #883.

---

src/System.Private.ServiceModel/src/windows/project.json

* The NET Native assembly for System.private.ServiceModel can't resolve the references in Windows.winmd, because they refer to mscorlib.
* Adding a reference to Microsoft.NETCore.Portable.Compatibility, which has an mscorlib façade in it fixes the problem.

Fix .NET Native build of S.P.SM due to mscorlib reference.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

The recent PR #883 for AllowCookies added code to assign the
cookie container to null when AllowCookies was false.  But on
NET Native, this causes an ArgumentNullException.  This caused
all Http OuterLoop tests to fail.
The fix is to set the cookie container only when AllowCookies is true.

Fix AllowCookies logic to not set cookie container to null

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs

The recent enabling of NegotiateStream in WCF Linux code
caused all the existing tcp secure streaming tests to fail
on Linux because CoreFx has not yet checked in the
implementation of NegotiateStream.
After discussion with @iamjasonp we decided to disable these
tests for the same issue being addressed by PR #898.  Once
CoreFx publishes a working NegotiateStream, we will either
reactivate these tests or fold them into the new NegotiateStream
tests in #898.

Disable tcp secure streaming tests on Linux

---

src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/BasicAuthResource.cs

The Https BasicAuthentication tests failed were they were the first
scenario tests run after a fresh start of the Bridge.  But they succeeded
when other scenario tests ran first.
Root cause was that the BasicAuthResource was not explicitly ensuring
the SSL port certificate was installed.  It passed if another scenario
test did that first.
The fix was to duplicate what the other Https test resources do and
explicitly ensure the SSL port certificate is installed.
Fixes #788

Fix test failure when BasicAuth tests were first to run

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/src/windows/project.json

* Latest version of System.Net.Http.WinHttpHandler requires a move to the pre-release version of S.IO.Compression

Update S.IO.Compression to pre-release version.

---

src/System.Private.ServiceModel/src/System/ServiceModel/SpnEndpointIdentity.cs
src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs

SpnEndpointIdentity.SpnLookupTime was not used previously as it wasn't used; it ended up causing a TFS build break, so an AutoProperty was implemented to unbreak the build. 
In #902, we have a discussion about what the real CoreFx implementation should look like. This PR shows what it looks like if we just took the desktop implementation (my preferred option) 
Note that the SpnLookupTime API is still unused, but this is essentially a harmless addition.

Implement SpnEndpointIdentity.SpnLookupTime

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs

* By wrapping the ActiveIssue in an #if #endif based on FEATURE_NETNATIVE we should be able to only skip these test on NET Native and not on NET Core.

Adding ActiveIssues for tests failing only on NET Native

---

src/System.Private.ServiceModel/tools/setupfiles/sync-pr.cmd
src/System.Private.ServiceModel/tools/setupfiles/sync-pr.sh

These scripts are for allowing the CI system to call out to a WCF sync service for outerloop tests. This is not incorporated into the CI system yet, as the relevant pieces on the test server/client are not yet done. 
skip ci please

Add PR sync scripts to repo for CI

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

Problem: HttpChannelFactory.SendRequestAsync keeps the HttpRequestMessage
in a member field and uses it during async processing.  But a Fault or Abort
will null the HttpRequestMessage field.  If this happens while the
SendRequestAsync method is executing, it leads to NullReferenceException
during error handling.
Solution: keep a local variable copy of the HttpRequestMessage for use in
error handling.  Even if the original is disposed or the field set to null,
error handling only requires access to the RequestUri property.
Fixes #931

Fix NullReferenceException in SendRequestAsync during async streaming

---

src/System.Private.ServiceModel/tests/Common/Scenarios/TestMockStream.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs

Issue #931 was discovered by stress tests, where an aborted
Http request doing an asynchronous read would throw a
NullReferenceException.
The cause is not a race condition but instead incorrect use of
member fields in exception handling.  This PR adds a scenario test
that exactly duplicates the stress test and causes NullRefException.
This test will be merged only after #935 that contains the fix to
issue #931.  The changes are being kept separate to allow selective
cherry-picking into the RC2 branch.

Adds scenario test for AV during Http async stream read

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

This test has been failing in ToF 100% of the time for me recently.
Now attempting to move to latest build tools, it fails 100% of the
time in OSS too.  It is a negative test that should be rewritten to
be smarter about testing after the cert has been revoked.

Disable certificate revoked scenario test

---

BuildToolsVersion.txt
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

Updates the version of xunit.netcore.extensions to 187.
This is to stay in sync with CoreFx and take some of the
fixes and enhancements in the test case discoverers.

Update version of xunit.netcore.extensions to 187

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

Original commit message was:
Fix NullReferenceException in SendRequestAsync during async streaming
Problem: HttpChannelFactory.SendRequestAsync keeps the HttpRequestMessage
in a member field and uses it during async processing.  But a Fault or Abort
will null the HttpRequestMessage field.  If this happens while the
SendRequestAsync method is executing, it leads to NullReferenceException
during error handling.
Solution: keep a local variable copy of the HttpRequestMessage for use in
error handling.  Even if the original is disposed or the field set to null,
error handling only requires access to the RequestUri property.
Fixes #931

Port to RC2 PR #935 to fix NullReferenceException during stress

---

src/System.Private.ServiceModel/src/System/ServiceModel/SpnEndpointIdentity.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/TestPropertiesTest.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStreamTestConfiguration.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj

Looking for some early feedback and discussion. Only review the NegotiateStream_*_Tests.cs files, please. 
I'm waiting for #893 to go in before rebasing this one. For some strange reason the rebasing is being weird, so you'll see a bunch of additional files. 
**Discussion:** 
* We need to figure out our story for how to specify usernames/passwords reasonably dynamically - this will probably involve using TestProperties so that they can be specified on the command line. 
* Furthermore, I would like to remove the [ActiveIssues] - rather, I would like to use some mechanism (like TestProperties or a ConditionalFact) to specify whether or not these tests should be run and should pass
* For example, one set of tests requires that the Bridge be run as LOCAL SYSTEM. This may require the Bridge to …

NegotiateStream tests

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

* Issue #951 is blocked by dotnet/corefx#7403 skipping the affected tests for OS X platform.

Adding OS X ActiveIssue for tests failing due to Issue #951

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs

In Helix, the runs do not spew out as much information as they do when running locally. We need to remove the Assert.True() at the end (used for showing the credentials used) so that the call stacks are shown.

Modify NegotiateStream ambient credential tests

---

src/System.Private.ServiceModel/tools/PRService/pr.ashx

RunGitCommands() would return false in the case where the method was passed zero commands to run. Now, if it's passed with a null or empty array, we will bail out early and return true to prevent the rest of the script from failing
skip ci please 
//cc @zhenlan

Fix pr.ashx returning false negatives running git

---

src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj
src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj
src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj
src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj
src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj

The TFM for these dependencies is incorrect, causing the S.P.SM to be
missed when not targeting netstandardapp1.5 (eg for a portable app).
Fix this TFM to match the implementation TFM.
I've filed a buildtools issue https://github.com/dotnet/buildtools/issues/617
to help eliminate the need for this completely.
/cc @StephenBonikowsky

Fix TFMs for System.Private.ServiceModel deps

---

Documentation/manualtest-guide.md

* Clarified how to set up for Kerberos on Linux
* Removed manual guide for Https/ClientCredentialTypeTests.cs
skip ci please

Add clarifications to manualtest-guide.md

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/TestProperties.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs

We need a way to optionally run tests that are not normally
run by default.  This includes tests that have special requirements
for setup or environment.
We also need such tests to show as "skipped" rather than being
silently stripped from the test results, as happens with the
xunit -notrait option.

Add support for [ConditionalFact] based on TestProperties

---

netci.groovy

WCF netci.groovy was previously using ''' as a quoting mechanism, but that prevented variables from being evaluated. Change the ''' to "

Change quotation in netci.groovy

---

src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config

Debug mode could take way too long and slow down our start up unnecessarily.

Disable the debug mode compilation of WCF service

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs

* Allow Test property ServiceUri.
* Note that we in the self hosted case, we only allow localhost, not multiple
service instances(localhost/wcfservice1).
* Change all endpoints point to the new services.

Init checkin of client changes

---

dir.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

This update allows us to use multiple conditions in
[ConditionalFact] tests.
This feature was added to xunit.netcore.extensions with
PR https://github.com/dotnet/buildtools/pull/619, and now
that the latest package is available, we can use it.

Update to latest xunit.netcore.extensions

---

.gitignore
build-packages.cmd
build.cmd
build.proj
clean.cmd
dir.traversal.targets
init-tools.cmd
src/dirs.proj
src/packages.builds
sync.cmd

With this PR we are almost up-to-date. Remaining is...
Corefx PRs dotnet/corefx#6572 and dotnet/corefx#7237 both of which involve a change to how we build test projects.
The comments from @iamjasonp in my merged PR #1003

April13 script sync

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs

* It should be tcp-default, not the no security one.
* A one line of code change that will fixes several security tests.

Fix Default TCP endpoint in client

---

src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj
src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj
src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj
src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj
src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj

This is the WCF version of https://github.com/dotnet/corefx/pull/7665
We need this in ASAP because the WCF repo is broken in internal builds
since it is built with the CoreFx version of buildtools.
Partial port of https://github.com/dotnet/wcf/pull/1008/commits/1901578da7ac1f82dfb09c57d87a18ce9d3e7cf9
without build tools update

[RC2] Add placeholders for PCL profiles

---

netci.groovy
src/System.Private.ServiceModel/tools/PRService/pr.ashx

* Add support for building rc2 and infrastructure branch in CI
* ~~Add PR Number guard to prevent PRService from breaks. When syncing to PR numbers lower than 987, the PRService will be wiped from the PRService endpoint and be put into an unrecoverable state.~~
~~Add a guard here to prevent syncing to a PR number < 987 and return HTTP/200 so that CI can succeed.~~
~~This should not happen during the normal course of events. In any case, PRs prior to 987 will not hit the hosted WcfService, so this no-op will not affect the outcome of any tests before that~~
(this will not prevent all breaks, but at least prevents one class of them)

Add support for building rc2 branch in CI

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

Background: When a proxy is not opened explicitly before use, the
CallOnceManager class does the open on the first service call.
Any other calls made during the open are queued, and when the
open completes are called in FIFO order.
Problem: the queued calls block on a WaitHandle that is set
only by the previous operation succeeding or by timeout. But
if the channel faults, there is no logic to set the WaitHandle,
so it will be set only after the timeout expires.  And then the
next queued operation begins its own timed wait and so on.  Code
in this state can easily lead to large numbers of blocked threads
Solution: detect when the channel faults or is closed and signal
the waiter's WaitHandles to wake up and complete their operation
(typically a failure because the channel is not usable by …

Fixes CallOnceManager to signal its blocked waiters when channel is unusable

---

src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateGenerator.csproj
src/System.Private.ServiceModel/tools/CertificateGenerator/packages.config

* Build certificate generator will fail on a new machine because the dependency is not defined.

Add BouncyCastle package dependency

---

netci.groovy

We maintained an exception for the Windows CI outerloop trigger phrase to allow for @dotnet-bot test outerloop please; we should get rid of this so that we consistently trigger all builds in the same way.

Change CI Windows Outerloop trigger phrase

---

Packaging.props
build-packages.sh
build-tests.cmd
build-tests.sh
build.proj
build.sh
clean.sh
dir.props
dir.targets
dir.traversal.targets
global.json
init-tools.sh
publish-packages.cmd
publish-packages.sh
run-test.cmd
run-test.sh
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/Infrastructure.Common.Tests.builds
src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenario.Tests.builds
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.builds
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.builds
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.builds
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.builds
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.builds
src/dirs.proj
src/global.json
src/tests.builds
sync.cmd
sync.sh

First commit syncs build-tests.cmd and related changes.
Second commit adopts the new test .builds files for building and running test projects.
Third commit takes updates to changes to shared files from last 24 hours and updates all the .sh files.
- The .sh files have not been tested on Linux.
- Even though we do not use run-test.sh I synced it, we may have to at some point.

April 14 Script Sync

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs

* We do not need to specify BridgeHost if we get it from the server.
* The service side already has the GetFQDN method, no need to update the service.

Get service FQDN from the server instead of using BridgeHost

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

* The fix for Active Issue #833 will also fix Issue #834, therefore updating the two tests in question to point to 833 so we can close Issue #834.
* Fixes #834

Update the ActiveIssue number to point to correct Issue.

---

src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509SecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportSecurityHelpers.cs

Hi! This is my first time contributing to WCF 😄 This is just a minor pull request to remove uses of async/await where they're not needed. e.g.
```cs
async Task<int> Foo()
{
return await Bar();
}
```
could simply be replaced with
```cs
Task<int> Foo()
{
return Bar();
}
```

Remove uses of async/await where not needed

---

src/System.Private.ServiceModel/tools/scripts/StartWCFService.cmd

Modified StartWcfService.cmd to locate its built executables
relative to itself rather than the current working directory.
Without this, running the script from any other folder will fail
to start the self-hosted service.

Fix StartWcfService.cmd to reference exes relative to itself

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.cs

Updates a single [Theory] to use [ConditionalTheory] so that a test
requiring certificates does not fail when the setup steps are skipped.
PR #1026 should have included this change, but I didn't see it until
I ran the tests under Linux and deliberately skipped the cert setup steps.  It also failed under CI or any other scenario that did not initialize certificates.
Fixes #1047

Update [Theory] to [ConditionalTheory] for failing test.

---

netci.groovy

* Remove infrastructure branch from netci.groovy 
After the merge of #1041, we can remove testing from CI for the */infrastructure branch
* Simplify CI triggers
Previously, we required a phrase "test [inner/outerloop] [platform] [Release/Debug]
Remove the need to specify the Release/Debug phrase as we typically want to
test both in one go anyway

Modify/simplify CI triggers and remove infrastructure branch

---

netci.groovy

This reverts part of commit 0ab55905c26be86a96d4c66266a5da37a232bdd6.
Triggers simplified in this way for innerloop seems to cause problems due to the
way the utilities groovy class handles the optional parameter - basically
specifying that parameter prevents innerloops from auto-triggering.
For now, revert the simplification for innerloop tests

Revert "Simplify CI triggers" for innerloop tests

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

Issue https://github.com/dotnet/corefx/issues/7403 caused multiple tests
to fail in OS X, so we disabled them with [ActiveIssue].
Now that 7403 is fixed, these tests can be re-enabled. Testing these
in the labs will require updating to latest CoreFx packages.

Re-enable scenario tests disabled in OS X due to SetLingerOption issue.

---

netci.groovy
src/System.Private.ServiceModel/tools/PRService/pr.ashx
src/System.Private.ServiceModel/tools/PRService/web.config
src/System.Private.ServiceModel/tools/scripts/sync-pr.cmd
src/System.Private.ServiceModel/tools/scripts/sync-pr.sh

Rather than have multiple PRServices (one for each repo) on the PR service machine, centralize them into one endpoint, and instead pass the repo id. This has the benefit of allowing only one copy of the service to be maintained, having fewer points of entry, having one consistent service across all repos, and finally, preventing accidental syncs from killing the service and requiring manual intervention

Consolidate various PRServices into one endpoint

---

src/System.Private.ServiceModel/tools/scripts/sync-pr.cmd
src/System.Private.ServiceModel/tools/scripts/sync-pr.sh

The earlier iteration of PRService relied on the URI query string passing repo=repo_id, however
we pushed a change that changed the repo ID identifier be 'id' on the query string
Modify the two scripts so they call the PR service correctly

PRService: update sync-pr scripts for new PRService

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestHelpers.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs

Moving to the new test infrastructure made these tests
fail due to using the BridgeHost property to determine
if they were running as localhost. We disabled them
temporarily during infrastructure integration.
The fix is to use the ServiceUri instead of BridgeHost.
Fixes #1043

Re-enable temporarily disabled WebSockets tests

---

src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config

This changes the default behavior of IIS-hosted test services
so that they do not trace to svclog files.  The web.config section
is preserved as a comment to allow it to be re-enabled to debug.

Disable svclog tracing in IIS-hosted test services

---

src/System.Private.ServiceModel/tools/scripts/WcfTestServerSetup.cmd

Script to Setup WCF test services hosted on IIS for the testing of WCF on .NET Core
Usage: WcfTestServerSetup Id [/c]
Id: The Id of a WCF repo and its associated IIS hosted services to be created.
The Id will be appended to the name of all assets to be created.
Master: if Id is 'Master', additional IIS hosted services such as PRService
will be created to serve as central services for other WCF repos.
/c: If specified, this will clean up any existing setup of Id instead of creating new.
Examples:
WcfTestServerSetup 42
:Create a WCF repo named 'wcf42' and IIS hosted services such as 'WcfService42'
WcfTestServerSetup 42 /c
:Clean up WCF repo 'wcf42' and all associated IIS hosted services such as 'WcfService42'

Script to setup WCF test services hosted on IIS for WCF Core testing

---

netci.groovy

The code coverage CI jobs were not passing in the ServiceUri parameter when running; this is needed for outerloop tests, which code coverage requires

Update netci.groovy for code coverage runs

---

build.cmd
build.proj

* Where before we did setup and cleanup steps directly in build.cmd now adding a generic "build.override.targets" hook to build.proj from which we can call any custom scripts to do whatever we want.
* Including example code to show how to create a setup and cleanup Target.
* Minor change to build.cmd for corefx diff reason.

Move setup and cleanup steps to msbuild.

---

netci.groovy

Copies a change for outerloops (see Line 215) to prevent ~~current~~ concurrent builds from happening in code coverage, at it also relies on outerloops with the WcfService
@dotnet-bot test ci please
EDIT: current -> concurrent

Disable concurrent builds in code coverage

---

netci.groovy

Additionally: 
Clean up netci.groovy
* Clean up dead sections of netci.groovy
* Change innerloop build status names to be simpler
* Disable rc2 builds from non Windows_NT outerloops due to dependency on Bridge.
As such, these builds will always fail

Turn on CentOS7.1 builds for CI

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs

The new self-hosted WCF service was creating the NTLM test
service host with incorrect parameters.
Fixes #1056

Fix broken NTLM functional test when self-hosted

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/TextTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextEncoderBufferedServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextEncoderStreamedServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextMessageBindingElement.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextMessageEncoder.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextMessageEncoderFactory.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

This PR just ports the custom text encoder scenario tests and converts
their Bridge endpoint resources to the new test infrastructure's
ServiceHosts.
Fixes #1042

Port custom text encoder scenario tests to new new infrastructure

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

First part of fixing issue #997, a second commit will be needed once new packages have been built to enable testing the usage of this constructor in the scenario test.

Make X509ServiceCertificateAuthentication constructable

---

netci.groovy

We used to have the phrase "test outerloop please" for testing, but it eventually got removed in the process of merging the groovy files from corefx. Change the triggers so that we allow using "test all outerloop" as a phrase to trigger CI builds

Add "test all outerloop" phrase to CI

---

build.override.targets
src/System.Private.ServiceModel/tools/CertificateGenerator/Program.cs
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
src/System.Private.ServiceModel/tools/scripts/BuildCertUtil.cmd
src/System.Private.ServiceModel/tools/scripts/CleanUpHttpsPort.cmd
src/System.Private.ServiceModel/tools/scripts/CleanUpWCFSelfHostedSvc.cmd
src/System.Private.ServiceModel/tools/scripts/OpenFirewallPorts.cmd
src/System.Private.ServiceModel/tools/scripts/PingWCFService.ps1
src/System.Private.ServiceModel/tools/scripts/RemoveFirewallPorts.cmd
src/System.Private.ServiceModel/tools/scripts/RunElevated.vbs
src/System.Private.ServiceModel/tools/scripts/StartWCFSelfHostedSvc.cmd
src/System.Private.ServiceModel/tools/scripts/StartWCFSelfHostedSvcDoWork.cmd

* Hook Start and clean up service into build
* If the build starts the service, it will clean up the service as well.
* If the service already started, the build will not restart and clean up.
* The start service will be elevated.
* Need feedback on whether "BuildAllProjects" target is the best target to ensure
set up get run before tests start.
* I have removed all ENDLOCAL as it's not needed.
* Each script is designed to handle a particular set up and clean up so that the scripts can share between Lab and Dev experiences.
* We ping the service in the set up to ensure the service is fully started.
* All clean up errors are treated as non fatal. Need feedback on it.

Integrate dev experience to build

---

src/System.Private.ServiceModel/tools/scripts/OpenFirewallPorts.cmd
src/System.Private.ServiceModel/tools/scripts/RemoveFirewallPorts.cmd

* This is because there is only one server certificate created per machine.
To run both selfhost and IIS hosted server on the same machine, we need to
use the same port.

Add port80 to firewall because crl service need it

---

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd
src/System.Private.ServiceModel/tools/scripts/WcfTestServerSetup.cmd

Fix error handling in server setup script
- Fixed `:Failure` that is completely messed up when `%_cmd%` contains quotes or parenthesis
- Redirect both standard output and standard error to log so error information can be displayed properly in failure case
Rename WcfTestServerSetup.cmd to SetupWcfIISHostedService.cmd so it follows the same "DoWhat" naming convention as the rest of scripts.

Server setup script fix

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs

Adds a single new CustomBinding test that uses Http rather than
the existing Https test. Done for 2 reasons:
1. Slightly better coverage
2. The existing Https test has [ConditionalFact] and is the only test in
this project.  When a lab run in Helix or ToF chooses not to run
this test, they both report failure due to having no tests to run
in the project.  Having a 2nd test eliminates these spurious error
reports.

Add new custom binding test to eliminate lab test failure reports

---

dir.props
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj

* Dir.props only contains the changes made by PR 8072.
* Additional changes to Contract .csproj files are necessary for WCF to not get package errors.

Porting corefx PR 8072

---

build.cmd

* Since we no longer execute setup and cleanup scripts from build.cmd we no longer need !ERRORLEVEL! after the call to msbuild, doesn't hurt to keep it but its out of sync with corefx and I think it makes more sense to change it in WCF since we don't technically need it anymore.

Don't need ERRORLEVEL to be set/used by setup/cleanup scripts.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientAuthenticationManager.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalTestDetectors.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/IUtil.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ServiceUtilHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs

Prior to this, the [ConditionalFact] condition tests were
simple heuristics.  This PR introduces runtime detectors that
to detect root and client certificates are installed as well as
whether the client is domain joined.

Add initial [ConditionalFact] detectors

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs

Remove [ActiveIssue] from this test and add to exiting [ConditionalFact]
that it should run only when username and password has been provided in
TestProperties.  Default is that they are not provided, in which case
this test is reported as skipped.
Fixes #979

Fix Digest auth test to work when username and password are available

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/IOTimer.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTSocketConnection.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/DuplexChannelBinder.cs

We are seeing high contention on the call to Timer.Change which takes a lock to modify a global priority queue of timers. By reducing the number of calls to Timer.Change, we increase throughput and won't interfere with other code running in the process which also uses Timers.
Also explicitly dispose Timer to remove from finalization queue.
Fixes #1074

Reduce the number of times the Timer is modified

---

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs

Some WebSockets tests started failing under ToF because
they really depended on there being a root certificate but
didn't say so.  They passed in GitHub because other tests
had caused them to be installed.
This change adds ConditionalFact to those WebSockets tests
that failed in ToF.

Add ConditionalFact to WebSockets tests that need it

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ServiceUtilHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/project.json

Adds Console output for the root and client certificate
installers triggered by ConditionalFact.  The changes now
show what exceptions occur, whether the cert was found in
the store by thumbprint or whether it had to fallback to the
name only.  It also shows information about the cert used.
including valid dates, issuer, etc.
On Linux, these changes allow us to see the reasons cert
installation fail.  And the exceptions contain suggestions
why it may have failed.
On cert-based tests that fail for cert validity issues, it
will likely help understand why.

Improve debugging of certificate installation

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

Now that the constructor for X509ServiceCertificateAuthentication is public in the contract, the workaround is no longer needed in the test to be able to set this.

Change test to use X509ServiceCertificateAuthentication constructor

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/FaultExceptionTests.4.0.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/FaultDetail2.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/KnownTypeA.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs

Fix #710
Add tests for: 
1) More than one ServiceKnowTypeAttribute. - already covered
2) More than one FaultContractAttribute
3) Mix of FaultContractAttribute and ServiceKnowTypeAttribute.
cc: @hongdai

Add more tests for FaultContract and ServiceKnownType

---

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/TextTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextEncoderBufferedServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/CustomTextEncoderStreamedServiceHost.cs

The custom message encoder tests caused periodic hangs running
on Linux.  Suspicion was use of an unsupported code page.  This
PR changes to a supported code page, and the hangs have not
been observed again.
Fixes #1148

Fix custom message encoder test to use supported code page

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Common/Unit/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

- Add "debian.8-x64". This is the correct rid for Debian. I want to
remove "debian.8.2-x64" before RTM.
- Add a generic "linux-x64" rid which we can use in cases where we want
to build for a distro where we don't yet have a set of runtime
packages. This will let us restore the managed assets (since they are
specific to "unix" or "linux" and then folks can do a native build to
get the shims and runtime and copy them over (this is a more
reasonable approach than our current strategy of just using
ubuntu.14.04-x64)
- Sort runtime sections

Add additional runtimes

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs

Remove setting timer to null as it may be accessed in race condition of read/write callback and Abort

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TaskHelpers.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TextMessageEncoder.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs

Created NoSpin variations of WaitForCompletion which immediately uses a WaitHandle. The original variations are still there as they will be more performant when a Task is expected to complete immediately. Switching to NoSpin variations should only be done when it's known an operation will take more than a fraction of a second to complete or when a profile shows it would be advantageous.

Prevent spin-waiting by using WaitHandle from Task

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelFactoryBase.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportChannelFactory.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs

HttpChannelFactory was handling OnCloseAsync but triggered
a synchronous close path in the layers below it.  With this
change, the underlying layers implement the async close path
and HttpChannelFactory uses it.
Fixes #1154

Fix channel factory async close path to not run synchronously

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ServiceUtilHelper.cs

The ConditionalFact detector for certificates was using a fallback
strategy to locate certificates based on IssuedBy and SubjectName
when it could not locate by thumbprint.  But this allowed matches
on left-over certificates that would not work.
With this change, we match only on thumbprint or report that there
is no certificate installed and let the ConditionalFact skip the
certificate tests.
Fixes #1172

Remove certificate matching by name

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

* Some new tests added recently fail for known Issue 1123 on Linux platforms.
* The correct fix is to create a conditional fact that skips the test based on an invalid environment setup.
* The setup that is causing the failure is currently still under investigation.

Updating tests with ActiveIssue 1123.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageFault.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/FaultFormatter.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

* We are currently unable to reflect OperationFault. The least risk option is
to make it public.
* In order to make it public, we need to make FaultFormatter and XmlObjectSerializerFault
public as well.
Fix #769 
I have verified the failing tests passed with this fix.

Make OperationFault public so that we are able to reflect it

---

src/System.Private.ServiceModel/tools/scripts/Repeat.cmd

This is the script we use whenever we need to set up a new server for CI testing or refresh all the repos/services on current CI server. For example, this command will create 36 WCF test services in batch.
```
repeat.cmd 36 SetupWcfIISHostedService.cmd #
```
---------------
Usage:
Repeat n command [parameters]
n: [Required] The number of iterations to repeat the command
command: [Required] The command to run for n iterations
parameters: [Optional] The parameters of the command
#: When parameters contain #, the last occurance in the parameter
will be replace with the number of iteration.
Example:
Repeat 42 work.cmd # param
:The script 'work.cmd' will be called 42 times like
work.cmd 1 param, work.cmd 2 param, ..., work.cmd 42 param
--------------
skip ci please

Add the script that is used to setup CI test server

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IVerifyWebSockets.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/VerifyWebSockets.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/WebSocketTestServiceHosts.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

* Verify WebSockets are actually being used when WebSocketTransportUsage is set to Always.
* Wcf automatically uses WebSockets when a callback is used, but this test verifies that it still uses
WebSockets when not using a callback.
* Fixes Issue #486

Verify WebSockets are actually used when not using a callback.

---

init-tools.cmd
init-tools.sh

Downloading from Azure can transiently fail for a number of reasons. Add
some retry logic when downloading to avoid transient failures. For *nix
variants add a retry value when using curl (wget retries by default).

Add retry logic when downloading the CLI from Azure blob storage.

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs

The scenario test to abort a channel factory with multiple operations
running concurrently gave different results depending on timing, and
therefore gave false failure intermittently.
This change makes the abort test resemble the similar close tests
in being tolerant of the exceptions thrown when the channel factory
is aborted.

Make flakey outerloop test more stable

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

* The tests are failing in the projectN lab.
We need the contitional fact to ensure root certificate is installed
to validate server certificate.

Add conditional fact for the two new tests need root cert

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.cs

Update the comment in the test file itself, as #592 is no longer an accurate
description for why this test must be skipped. #945 better tracks the issues around
why this test is currently skipped.
skip ci please

Update tests marked with ActiveIssue #592 to #945

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

* Adding 2 Https tests, one for each pivot. X509CertificateValidationMode.PeerTrust X509CertificateValidationMode.PeerOrChainTrust.
* Fixes Issue #1192

Adding tests for validating certificates with PeerTrust on https.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfUserNameService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TcpTransportSecurityStreamedTestServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/BasicAuthentication/web.config
src/System.Private.ServiceModel/tools/IISHostedWcfService/ClientCertificateAccepted/web.config
src/System.Private.ServiceModel/tools/IISHostedWcfService/DigestAuthentication/web.config
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/IISHostedWcfService/WindowAuthenticationNegotiate/web.config
src/System.Private.ServiceModel/tools/IISHostedWcfService/WindowAuthenticationNtlm/web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

* This will enable most security tests run in Domain machines.
* This will enable client certificate tests in IIS hosted lab runs.
* Fix tests with incorrect conditional fact.
* Fix service side test issue as it's the first time we enable some
of the security tests.

Create security subfolders in IIS host server

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelProxy.cs

Problem: under heavy load with multi-core machines, it was discovered
the Task used for async operations could be reused by other async
activities, leading to an inapropriate OperationContext.  This was
detected internally and threw PlatformNotSupported.
The fixes are to throw the correct InvalidOperationException, ensure
the OperationContext is set appropriately before any TrySet calls,
and use TaskCreationOptions to deny child tasks from attaching to
the tasks used for async operations.
Fixes #1137

Fix async duplex issue that uses wrong OperationContext

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelProxy.cs

Original commit was:
Fix async duplex issue that uses wrong OperationContext
Problem: under heavy load with multi-core machines, it was discovered
the Task used for async operations could be reused by other async
activities, leading to an inapropriate OperationContext.  This was
detected internally and threw PlatformNotSupported.
The fixes are to throw the correct InvalidOperationException, ensure
the OperationContext is set appropriately before any TrySet calls,
and alter the TimeoutHelper TCS to use ConfigureAwait.
Fixes #1137
Make TimeoutHelper continuations run asynchronously

Port fix to issue 1137 to 1.0.0

---

src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenario.Tests.builds

The ConditionalFact detectors were being executed during
innerloop-only test runs. This is due to the fact we build
all test projects unconditionally and because xunit's trait
and Fact discoverers are executed before deciding whether
there are any tests to run. But unless the Self-host WCF
service was running (which happens only during OuterLoop
runs), this generated many exceptions in the console log.
With this change, all projects under tests\Scenarios are
excluded from the build unless OuterLoop has been requested.
This means there are no are no binaries containing
ConditionalFact when a normal non-OuterLoop build is done.
Fixes #1224

Exclude scenario tests if not building for OuterLoop

---

src/System.Private.ServiceModel/tools/scripts/PingWCFService.ps1

The scripts to self-start the self-hosted service will fail if
the service does not respond with a ping in a short time.  But
the script to start the service also builds it, and when package
restore is slow can take longer than the ping time.  When this
happens, the ping script yields control to a 2nd CMD file attempting
to write to the same log file, and the WcfSetup target fails,
causing the build to fail.
This PR just lengthens the time we wait for the service to respond
with a ping when self-starting.  We don't use this ping script for
anything other than self-start, so the longer time will not adversely
affect other "ping" scenarios.

Lengthen the ping wait time for starting self-host server

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.NetNative.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.cs

Fixes the problem where HttpClientHandler completes the task returned from SendAsync
once the response headers have be returned when running on Unix.

Wait until message has been sent before completing HttpClient.SendAsync

---

src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs

This is needed because the channels are getting mixed up and we're
trying to send the wrong events to the wrong channels and this is
causing a performance problem.
Addresses #1217 but isn't the final solution as we need to get channels working.

Disable event channel usage

---

dir.props
pkg/baseline/baseline.props
pkg/baseline/project.json

Package baselining has been broken since the first package update after
I added it.  The problem was that the package that contains the corefx
baseline was missing from the update list so the update script updated
it to be out of sync with the CoreFxExpectedPrerelease property. I've
added the baseline package to the list of packages coming from CoreFx.
This was silently being dropped because we don't import the target if it
doesn't exist.  I've updated the import condition to be less permissive.
We just need it to not import before the restore so constraining it to
pkgproj will do that, and fail the build if this issue should occur in
the future.
Fixes https://github.com/dotnet/wcf/issues/1245
/cc @hongdai @zhenlan @weshaggard @dagood

Fix package baseline

---

dir.props
pkg/baseline/baseline.props
pkg/baseline/project.json

Package baselining has been broken since the first package update after
I added it.  The problem was that the package that contains the corefx
baseline was missing from the update list so the update script updated
it to be out of sync with the CoreFxExpectedPrerelease property. I've
added the baseline package to the list of packages coming from CoreFx.
This was silently being dropped because we don't import the target if it
doesn't exist.  I've updated the import condition to be less permissive.
We just need it to not import before the restore so constraining it to
pkgproj will do that, and fail the build if this issue should occur in
the future.
Port of https://github.com/dotnet/wcf/commit/c5118f33c380761e2c738fdeb06e3ec411ab15d2

Fix package baseline - release/1.0.0

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs

Tests were previously failing when attempting to check for certificate revocation. After testing, we've found that these tests no longer fail. 
Reactivate these tests so we get coverage again.

Reactivate tests for Certificate Revocation

---

pkg/baseline/stable.packages.props

Getting this PR ready for when we want to push the button.
Includes more changes than necessary long term.  We can remove all the CoreFx/TFS entries once we pick up the new Baseline package.  That will happen as soon as this branch transitions to servicing.
Alternatively we could a) prime the baseline package by building locally, publishing, then picking up that version or b) serialize WCF after CoreFx and have the RTM build of WCF consume the RTM/escrow build of CoreFx.
/cc @joshfree @weshaggard @roncain

Mark packages stable

---

build.proj

This is needed because we'll be producing packages with constant stable
version and content updates.
/cc @weshaggard @jhendrixMSFT
We'll also need to update the VSO build definitions so pass BuildType=Official.

Clean packages on official and CI builds

---

src/System.Private.ServiceModel/tools/PRService/pr.ashx

The PRService looks up a list of valid branches before allowing a checkout to a
branch on the query string. However, when a new branch is created, the PRService
does not do a fetch before doing the branch name check, which means the PRService
is not aware of the new branch and fails the check.
This PR
1. Causes the fetch to happen first
2. Consolidates the fetch/cleanup logic into CleanupBranches
Fixes #1287

Update PRService to be robust when fetching new branches

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

The tests are failing on CI in release/1.0.0 branch
We need the contitional fact to ensure root certificate is installed to validate server certificate.
```
DuplexChannelShapeTests.IRequestChannel_Https_NetHttpsBinding
Binding_Http_NetHttpsBindingTests.NonDefaultCtor_NetHttps_Echo_RoundTrips_String
Binding_Http_NetHttpsBindingTests.DefaultCtor_NetHttps_Echo_RoundTrips_String
```

Add conditional fact for the tests need root cert

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs

Currently the TCP NegotiateStream tests that use explicit
credentials fail.  Issue #1262 tracks the underlying
issue https://github.com/dotnet/corefx/issues/9160
These tests are currently run only manually because they
require valid user credentials.

Disable TCP Negotiate tests using explicit credentials

---

src/System.Private.ServiceModel/System.Private.ServiceModel.sln
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalTestDetectors.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ServiceUtilHelper.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/SetupValidationTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json

This alters the behavior of the ConditionalFact conditions
for Root_Certificate_Installed and Client_Certificate_Installed
to respect if they have been set explicitly via the build or
as Environment variables.  This allows CI or lab runs to
control whether certificate related tests are run or skipped,
independent of auto-detection logic.
If not explicitly set, the prior auto-detection logic works
as it did in the past.  If they can be installed and verified,
then those ConditionalFact tests run, otherwise they are skipped.
If explicitly set to false, those tests are skipped without
attempting any certificate installation.
If explicitly set to true, the ConditionalFact logic will
attempt to install the certificates, and those ConditionalFact
tests will be run, regardless whether the …

Make certificate ConditionalFacts allow explicit overrides

---

release-notes/SupportedFeatures-v1.0.0.md

* Linux OSs are in one column to simplify. The test results are identical.
* Known issues points to a github RTM known issue label query.
Fix #1281

RTM release feature table

---

src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json

* Just updated the .json file with recently addes runtimes.

Json file was missing the new runtimes and causing VSO failure.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/Infrastructure.Common.csproj
src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/Infrastructure.Common.Tests.csproj
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTests.Common.csproj
src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/Binding.Tcp.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/Contract.Fault.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/Contract.XmlSerializer.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/Extensibility.MessageInterceptor.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

* This project reference is causing strange build behavior in the VSO build pipeline. Since in that environment it is supposed to build test using the actual packages anyway these project references should not be used.

Add condition to proj ref of S.P.SM

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/Infrastructure.Common.Tests.csproj

* For some unknown reason in the VSO build pipeline we get a restore --packages failure if the unit test project for Infrastructure.Common does not have a reference to S.P.SM.
* This un-blocks us for now so we can proceed with updating WCF package versions to the latest.
* Additional changes in the next few days should significantly change how we run tests so this issue will either be addressed there or by-passed entirely.

Removing HELIX condition for ServiceModel project reference.

---

src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509CertificateValidator.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/StreamedFramingRequestChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WindowsStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/AsyncResult.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/InterceptingChannelBase.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/InterceptingChannelFactory.cs

The MessageInterceptor scenario test exposed a product issue where we were not correctly invoking OnOpen or OnClose on custom channels or channel factories.  The test also used a workaround to get past the product issue, and this workaround failed when run on the full framework.
This PR fixes the product issue and removes the workarounds from the MessageInterceptor test.
Fixes #1241

Fix issue where OnOpen and OnClose were not called on custom channels and factories

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs

Conditional code for NET Native was catching all exception types
thrown when initiating an upgrade and and wrapping them in
SecurityNegotiationException. This caused a behavioral change
from the CoreCLR version, causing exceptions thrown by custom
validators to be converted into SecurityNegotiationExceptions.
The fix is to not wrap Exception inside SecurityNegotiationException
unless we see a non-default HRESULT.  The modified code runs only
in NET Native.
Fixes #983
Fixes #1220 
Fixes #1320

Don't wrap all exceptions in SSLStreamSecurityUpgradeProvider

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs

Adds some NET Native versions of ConditionalFact checking to prevent
this test from running under NET Native.

Fix Digest authentication test that should not run on NET Native

---

src/Common/test-runtime/project.json

The ConditionalFact detectors were experiencing failure to load
assemblies when tests were not built with the same dependencies
as those used by the ConditionalFact infrastructure.
This change adds to the shared test-runtime project.json those
entries that ensure tests use the same packages.
Fixes #1353

Add explicit WCF dependencies to test-runtime project.json

---

src/System.Private.ServiceModel/tools/scripts/InstallRootCertificate.sh

Three changes: 
1. We were masking errors by redirecting the result of cURL to /dev/null. I have removed the redirection
2. The endpoint GetRootCertificate was changed to RootCert
3. InstallRootCertificate.sh was edited in Windows, and so it needs to be chmodded to be executable
skip ci please
Replaces #1364

Fixup InstallRotCertificate.sh hitting old endpoint

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.csproj
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTests.Common.csproj
src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj
src/System.Private.ServiceModel/tests/Common/Unit/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

* Facade test.csproj files now use .pkgproj references.
* Facade project.json files have been cleaned-up.
* UnitTests.Common.csproj and project.json files have been cleaned-up.
* Wherever dependent packages need to be referenced use the last stable released version.
* ToDo: Add a run in VSO to run tests against latest-latest (latest dependencies/latest WCF).
* ToDo: Next PR to make same changes to Scenario test projects and related common code.

Update the Facade test projects to use .pkgproj references.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets

This change adds a new entry to TestProperties to capture the
MsBuild property $(TestNugetRuntimeId).  This property is set
by Helix runs to indicate the package name for the runtime to
use when running the tests.  The build tools also already set
this property, so it is correct during the dev experience too.
This provides the extra necessary information for PR #1388 to be
able to provide more accurate values for the OS enum. For example,
we will be able to distintuish Ubuntu 14.04 from 16.04 at test
runtime based on this new TestProperty.
The existing RuntimeInformation support does not provide this
granularity explicitly and would require fragile string matching to
try to extract from the RuntimeInformation's OS description alone.

Add TestNugetRuntimeId to TestProperties

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs

Use WebSockets pkg version supported on unix and enable tests

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalTestDetectors.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/FrameworkHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/FrameworkID.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/ConditionAttribute.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/IssueAttribute.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfFactAttribute.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfFactDiscoverer.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfSkippableAttribute.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestDiscoverer.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTheoryAttribute.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTheoryDiscoverer.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/WcfFactTests.cs

This PR adds WcfFact and WcfTheory attributes and discoverers to take the place of
ConditionalFact and ConditionalTheory.  The new discoverers have
been generalized to reflect onto the test method for any of the new
"skip" attributes (IssueAttribute and ConditionAttribute).
For design discussion on this see issue #1034

Add new [Fact] and [Theory] attributes to generalize ConditionalFact

---

.gitignore
build.override.targets
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json

This PR temporarily puts back the project.json files we removed when moving to a single project.json.  It appears the Build-Test job in VSO does not trigger our logic to copy the project.jsons, and therefore fails to build.  This PR is only temporary to unblock VSO while we decide on the correct fix.

Temporarily put back project.json files to unblock VSO

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/OSAndFrameworkTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/WcfFactTests.cs

This PR improves the granularity of the detection of which
version of Windows is currently running. It also moves the
infrastructure tests for detection into a new file that uses
FactAttribute to ensure they run on NET Native.

Improve detection of Windows OS

---

src/System.Private.ServiceModel/tools/PRService/pr.ashx
src/System.Private.ServiceModel/tools/PRService/web.config

Without the check for a deteached HEAD state, we would attempt to delete some
bogus branches. Now we're a little better about it and so we should see the
PRService fail less often. 
skip ci please

Add better checks for detecting detached HEAD in PRService

---

src/certtest.props

* I'm getting "Command Not Found" error without this fix.
* After this fix, cert tests are passing in Helix for Ubuntu

Add execution permission to the cert installation file

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestDiscoverer.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTheoryDiscoverer.cs

The WcfTheoryAttribute test discover was creating an xunit
test runner that worked only for Fact, but not for Theory.
The solution was to refactor slightly and to create a
theory-based xunit test runner for non-skipped tests.

Fix WcfTheory discoverer to use theory data

---

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs

The Windows platforms we currently test against include Win7,
but the WebSockets protocol is not supported on that OS.
As a result, VSO runs report WebSockets failures on the Win7
runs, forcing us to investigate each time.
With this change, those tests will be skipped on Win7, and any
VSO failures reported will be legitimate issues to investigate.
This new IssueAttribute will not disable these tests anywhere else.

Use IssueAttribute to disable WebSockets tests on Win7

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/IssueAttribute.cs

Setting this property to 'true' means that tests marked
with IssuesAttribute will not be skipped.

Add RunTestsWithIssues TestProperty

---

src/certtest.props

There should be no need to call sudo when attmepting to chmod the InstallRootCertificates.sh
script. The file is owned by the text execution user, not root

Remove call to sudo when chmodding in certtest.props

---

dir.props
src/Common/test-runtime/project.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.csproj
src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.rd.xml
src/System.Private.ServiceModel/tests/Common/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

Preparing to get UWP testing working in Helix discovered
WcfFactAttribute and WcfTheoryAttribute were not working
properly.  One reason was due to mismatched xunit
versions between the UWP runners and our Infrastructure.Common.
Moving to the same xunit version allows that part to work.
The second reason was that our custom Fact and Theory attributes
and their discoverers were not permitted to do Reflection.  The fix
was to add a custom rd.xml that allows that.  With these 2 changes
WcfFact and WcfTheory work in UWP in Helix.

Move to xunit 2.2.0-prerelease to get UWP testing to work

---

src/System.ServiceModel.Duplex/tests/ServiceModel/CallbackBehaviorAttributeTest.cs
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/Channels/HttpRequestMessagePropertyTest.cs
src/System.ServiceModel.Http/tests/Channels/WebSocketTransportSettingsTest.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Http/tests/ServiceModel/SecurityBindingElementTest.cs
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/Channels/TcpConnectionPoolSettingsTest.cs
src/System.ServiceModel.NetTcp/tests/Channels/TcpTransportBindingElementTest.cs
src/System.ServiceModel.NetTcp/tests/ServiceModel/MessageSecurityOverTcpTest.cs
src/System.ServiceModel.NetTcp/tests/ServiceModel/NetTcpBindingTest.cs
src/System.ServiceModel.NetTcp/tests/ServiceModel/NetTcpSecurityTest.cs
src/System.ServiceModel.NetTcp/tests/ServiceModel/TcpTransportSecurityTest.cs
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/Channels/BinaryMessageEncodingBindingElementTest.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/MessageTest.cs
src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs
src/System.ServiceModel.Primitives/tests/Description/ContractDescriptionTest.cs
src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexClientBaseTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.cs
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/ServiceModel/DnsEndpointIdentityTest.cs
src/System.ServiceModel.Security/tests/ServiceModel/MessageSecurityVersionTest.cs
src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs
src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

Modifies all the unit tests to use WcfFact instead of Fact
and WcfTheory instead of Theory.
We retain some conditional code temporarily to allow running
in ToF as well as normally in GitHub.

Change unit tests to use WcfFact

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

OSX certificate install should now work, so we can now allow these tests to run. 
~~There may still be tests failing because we're using SecureTransport instead of OpenSSL, so this PR may be further touched so that such tests point to a new issue instead~~
EDIT: guess not, CI all passed, so this can go ahead

Remove Issue(1398) from tests requiring cert+OSX

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/TestEventListener.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs

* This is to help analyze test failures, especially on non window
platforms

Emit WCF ETW events whenever a test fail

---

src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomBindingTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.cs

Some unit tests were disabled when run against UWP due to
a known issue in the toolchain with InlineDataAttribute(null).
This PR applies a workaround to that toolchain issue and reactivates
the tests.

Reactivate unit tests disabled by issue #1449

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

When converting all ActiveIssueAttributes to IssueAttribute in
preparation for UWP testing, one was accidentally omitted. This
test was supposed to be skipped due to this known issue, not
executed and counted as a failure.

Adds IssueAttribute for NET Native inadvertantly omitted

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.1.0.cs

During the recent migration from using FactAttribute to
WcfFactAttribute, a few files were missed.  This PR just
applies the same manual boiler-plate changes made to all
the others.

Convert FactAttributes to WcfFactAttribute in missed files

---

src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj
src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.rd.xml
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs

Issue #1450 was caused in UWP because the MemberData attribute
was hiding specific Encoding types from the reducer, resulting in
MissingMetadataException when xunit was doing test discovery.
The fix is to add back a custom rd.xml file to the project containing
the TestData class to grant Reflection permissions for types affected by this.
Fixes #1450

Fix UWP issue #1450 and re-enable tests disabled for it.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs

The new logic to Console.WriteLine ETW events for tests that fail
is writing out extraneous empty "Begin" and "End" blocks when run
on UWP.  This is because UWP doesn't currently support ETW, and it
has no events to report.
The fix is to skip the entire Console.WriteLine block of code if
there are no ETW events to report.
Fixes #1465

Omit empty ETW "Begin" and "End" messages if no events to report

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs

Net.Tcp with Certificate security and no client certificate as a valid use case. The assert was presuming this would never happen.
Fixes #1467

Assert was presuming there would always be a client cert which isn't the case

---

src/System.Private.ServiceModel/tools/scripts/InstallRootCertificate.sh

In InstallRootCertificate.sh, redirect the c_rehash stdout to /dev/null, and
continue to allow the stderr to print to console
This will help reduce clutter in output when in our test setup steps,
especially since in our tests we may run this script more than once and c_rehash
output is quite verbose and prints every root cert out

Redirect InstallRootCertificate.sh c_rehash output

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs

This set of tests should work for Debian and Ubuntu, as they by default have libcurl+OpenSSL installed

Enable HttpsTests for platforms that support it

---

src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.4.1.0.cs

* We need the fix for issue https://github.com/dotnet/corefx/issues/9160
* I have verified manually we can now set Explict username/pwd for TCP.
fixes #1262

Depend on current version of System.NetSecurity

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

This test was passing 10 days ago when it was first added,
but over the past 2 days it has been failing in both CI and Helix.
Disabling it with IssueAttribute to return to having clean CI runs.

Disable NetTcp duplex callback test that fails in CI and Helix

---

src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

Refactors the way service hosts are created and started by the self-hosted program.  This simplifies the code to open a endpoint and makes it less error-prone.  It also centralizes the open step so that we can Console.WriteLine which services are running at which address

Cleanup selfhost

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.0.0.cs

* This test was observed to hang back when it was still being run under the ToF infrastructure.
* Failure has not reproduced in current N run environment.
* Fixes Issue #1250

Activate test case, reason for being skipped no longer reproes.

---

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd

* Authentication methods sections need to be unlocked from the root
for individual website to overrid them.
Fixes #1511

Update IIS Server setup scripts to unlock authentication methods

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs

Fixes #1482 
This test doesn't fail and the product fix was done a couple of weeks prior. This must be a test runtime issue pulling in an older build of WCF.

Removing IssueAttribute as test is working fine

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/TestProperties.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/IssueAttribute.cs

Trim test property and environment variable values to avoid
issues we found with accidental whitespace.
UPN_Available was not properly being passed into TestProperties,
so this Condition was always false unless an environment variable
was set for it on the machine where the tests were run.
IssueAttribute parses the IncludeTestsWithIssues TestProperty to
allow multiple issues to be specified.  But if semicolon separated,
it causes a code-gen error in TestProperties.  So change it to allow
a comma separated list.

Miscellaneous test property fixes

---

netci.groovy

Only periodic triggers were running for outerloops - they should have push triggers as well to run after every commit happening

Add push triggers for outerloops

---

src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/SetupValidationTests.cs

Issue #1347 was closed but there was still a test being
skipped on *nix machines due to an IssueAttribute for it.
This PR removes the IssueAttribute to re-enable this test.

Reenable test disabled by #1347

---

netci.groovy

After change to dev workflow, code coverage jobs are failing because we pass in
a WithCategories=OuterLoop parameter. Remove this so we get code coverage again

Update code coverage job

---

netci.groovy

After change to dev workflow, code coverage jobs are failing because we pass in
a WithCategories=OuterLoop parameter. Remove this so we get code coverage again
The ws-trust branch was created before this issue was detected so we need to separately PR to this branch so we get code coverage numbers

Update code coverage job for ws-trust branch

---

src/System.Private.ServiceModel/src/System/IdentityModel/Claims/Claim.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Claims/ClaimComparer.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Diagnostics/SecurityTraceRecordHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/UpnEndpointIdentity.cs
src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs

Fix UpnEndpointIdentity on UWP

---

dependencies.props

*  RemoteDependencyBuildInfo "WCF" needs to match the CurrentRef property but it is case sensitive.

Update caseing in dependencies.props

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs

PR #1502 fixed issue #10 by implementing UpnEndpointIdentity.
But 2 tests were still disabled by issue 10, so this PR just
re-enables those tests.  Both require manual setup to run, so
we will not see them pass or fail in CI or VSO.
Update: the tests still fail in UWP, so this PR only re-enables them for non-UWP frameworks.

Re-enable tests disabled by issue 10

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockAsyncResult.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockCommunicationObject.cs
src/System.ServiceModel.Primitives/tests/Channels/CommunicationObjectTest.cs

CommunicationObject.OnOpen() was not being called properly when the synchronous Open() method was used.   The fix was to make both Open and Close code paths be aware if they were started synchronously or asynchronously and to call their appropriate versions of OnOpen/OnBeginOpen or OnClose/OnBeginClose.
fixes #1544

Fix issue where CommunicationObject.OnOpen was not called.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockAsyncResult.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockCommunicationObject.cs
src/System.ServiceModel.Primitives/tests/Channels/CommunicationObjectTest.cs

Original commit message in master was:
Fix issue where CommunicationObject.OnOpen was not called
Converting the synchronous CommunicationObject open/close paths
introduced a bug that prevented the OnOpen() method to be called
when the synchronous Open() method was used.
The fix is to be aware of whether the caller invoked the synchronous
Open or the asynchronous BeginOpen and invoke the appropriate
synchronous or asynchronous override.
Fixes #1544

Port to release/1.1.0 fix to issue #1544

---

src/System.Private.ServiceModel/src/System/IdentityModel/Claims/Claim.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Claims/ClaimComparer.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Diagnostics/SecurityTraceRecordHelper.cs
src/System.Private.ServiceModel/src/System/ServiceModel/UpnEndpointIdentity.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs
src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs

Fix UpnIdentity
Re-enable tests disabled by issue 10, except for NET Native.
2 tests are still disabled by issue 10, so re-enables those tests. 
Both require manual setup to run, so
we will not see them pass or fail in CI or VSO.
These tests still fail in UWP and so remain disabled there.

Port to 1.1:Fix UpnIdentity

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs

Testing with latest dependencies showed these 2 tests pass in UWP now.

Re-enable tests disabled in UWP for issue #10

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs

* Two tests are failing in Kerberos Manual tests due to known product issue.
* One test need to validate server window credential on the client side,
does not work on non window machines.
Fixes #1564 and issue#1563

Skip tests with known issue or should not get run on Linux

---

src/System.Private.ServiceModel/src/Extensions/X509Certificate2Extensions.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Claims/X509CertificateClaimSet.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509SecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/X509SecurityToken.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityUpgradeProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs

In .NET Core, the X509Certificate2 copy constructor was missing; where WCF code
needed to clone a certificate, we replaced the references to the copy constructor
with code that uses the certificate.Handle instead
However, in Linux, OpenSSL does not provide the private key when using this handle,
meaning the private key goes missing in all subsequent copies; as such, client cert
authentication doesn't work.
This is a stopgap solution only, as we await the inclusion of the X509Certificate2
copy ctor in a future .NET Core version
Relates to #1574

Work around X509Certificate2 copy constructor omission 

---

pkg/baseline/packageIndex.json

Live built packages changed their version to 4.3.0, update assembly maps
to represent this.
Rebase all packages on latest version since 1.1.0 release is shipping as
a set.
/cc @StephenBonikowsky @zhenlan @mconnew

Update index for 4.3.0 packages

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TaskHelpers.cs
src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml
src/System.Private.ServiceModel/src/System/ServiceModel/ChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelFactoryBase.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ConnectionOrientedTransportChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelFactory.cs
src/System.Private.ServiceModel/tests/Common/Unit/IMockCommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockAsyncResult.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockChannelBase.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockChannelFactory.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockCommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockRequestChannel.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockTransportBindingElement.cs
src/System.ServiceModel.Primitives/tests/Channels/CommunicationObjectTest.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomChannelTest.cs

Fixes the issue where OnOpen/OnBeginOpen and
OnClose/OnBeginClose were incorrectly called when
using custom channels.
Fixes the product issue by propagating knowledge of
sync and async open/close requests down the channel
stack so they stay sync or async based on the original
call.
Created mocks and unit tests for custom channels
**READY FOR REVIEW NOW**
Fixes #1544

Fix OnOpen/OnBeginOpen issues with custom channels

---

src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs

* We use try/catch to catch PlatformNotSupported exception
and use the same way to set default user on UWP.
Fix #1569

Fix the issue that we use WindowsIdentity.Current on *NIX

---

src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomBindingTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.cs

The issue behind #1449 has been opened against the
ILC team, and the workaround already in place is adequate.
This PR merely removes the unnecessary comment references to
issue #1449.
skip ci please
Fixes #1449

Remove comments regarding 1449 workaround

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractCommon.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.1.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/CompositeType.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/DigestServiceAuthorizationManager.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ReplyBankingData.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ReplyBankingDataNotWrapped.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/RequestBankingData.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TestServiceHostBase.cs

* We would like to leverge the same test server for WCF connected service
testing.
* I have verified the updated test service can be used for adding service references, both http and net.tcp
bindings.

Fix test services for addding service reference

---

src/System.Private.ServiceModel/tests/Common/Unit/MockChannelInitializer.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockEndpointBehavior.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomChannelTest.cs

Also adds ClientRuntime.ChannelInitializers to public API because
this is needed to register a custom IChannelInitializer.
Also creates new mock initializer and unit tests to verify it
is called properly.
Fixes #1422

Add IChannelInitializer to public API

---

src/System.Private.ServiceModel/tests/Common/Unit/MockClientMessageInspector.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockInteractiveChannelInitializer.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomChannelTest.cs

Also adds ClientRuntime.InteractiveInitializers to public API,
which is the only way to register interactive initializers.
New mocks and unit tests added to verify the interative
initializer is called properly.

Adds IInteractiveChannelInitializer to public API

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/TaskHelpers.cs
src/System.Private.ServiceModel/src/Resources/System.Private.ServiceModel.rd.xml
src/System.Private.ServiceModel/src/System/ServiceModel/ChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelFactoryBase.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ConnectionOrientedTransportChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelFactory.cs
src/System.Private.ServiceModel/tests/Common/Unit/IMockCommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockAsyncResult.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockChannelBase.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockChannelFactory.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockCommunicationObject.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockRequestChannel.cs
src/System.Private.ServiceModel/tests/Common/Unit/MockTransportBindingElement.cs
src/System.ServiceModel.Primitives/tests/Channels/CommunicationObjectTest.cs
src/System.ServiceModel.Primitives/tests/Channels/CustomChannelTest.cs

Cherry-pick of: 96e0c4d137ff583eda836c2448b737bd54a8fb73
Original commit comments:
Fix OnOpen/OnBeginOpen issues with custom channels
Fixes the product issue by propagating knowledge of
sync and async open/close requests down the channel
stack so they stay sync or async based on the original
call.
Created mocks and unit tests for custom channels
Fixes #1544

Port to release/1.1.0 custom channel fix

---

dir.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Common/Scenarios/project.json
src/System.Private.ServiceModel/tests/Common/Unit/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/project.json
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
src/System.ServiceModel.Duplex/tests/project.json
src/System.ServiceModel.Http/tests/project.json
src/System.ServiceModel.NetTcp/tests/project.json
src/System.ServiceModel.Primitives/tests/project.json
src/System.ServiceModel.Security/tests/project.json

* We are going to have to eventually, next step is to move product packages to NetStandard1.7

Updating all tests to run using netcoreapp1.1 test TFM.

---

src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenario.Tests.builds
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.builds
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.builds
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.builds
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.builds
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.builds

* WCF currently supports two TestTFMs, they need to be explicitly listed for test projects now so that the 'FilterToTestTFM' property used in Helix runs works as expected. This "may" fix the netcore50 runs in Helix.

Enabling tests to run against netcore50 test tfm

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs
src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateCreationSettings.cs
src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateGenerator.cs
src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateManager.cs
src/System.Private.ServiceModel/tools/CertificateGenerator/Program.cs
wcf.targets

This is the 2nd of 2 steps to remove the old infrastructure.
The first step deleted all old infrastructure code.
This follow-up PR just renames variables, constants, member names,
etc. to remove "Bridge" from any names.

Rename test properties and members to remove "Bridge"

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/NetHttpTestServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/NetHttpsTestServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

* One test was using the wrong binding, both needed seperate endpoints on the server configured to receive incoming messages using websockets.

Fix Duplex Channel shaped tests using http.

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.4.1.0.cs

* Test case "NetTcp_TransportSecurity_Streamed_TimeOut_Long_Running_Operation" is just testing the 'SendTimeout' property on the binding, to make sure it is working as expected we only pass the test when the elapsed time falls within a narrow range.
* This test has occasionally been failing by taking longer than expected, we don't believe this is a product bug most likely caused because we were not explicitly opening the channel before starting the Stopwatch, by doing this we are remove this small but variable amount of time that was getting added to the elapsed time calculation.

Fixing a flaky test.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs

* The two newly added tests need to be disabled on Windows 7

Disable tests on Windows 7

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IService1.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IStressDataCollector.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/RunReportingService.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/CommonTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexStreamingTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/HelloWorldTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/ITestTemplate.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/DuplexStreamingService.svc.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/Web.config

Refactored tests to support more stress scenarios
Added numerous command line parameters to control both perf and stress tests
Added basic stress results reporting
Tuned perf scenario tests to achieve stable results
Addressed some of the previous PR feedback
Added various security bindings

WCF 1.1 Stress Tests

---

Documentation/developer-guide.md

Due to changes in the build tools, the instructions for how to
run unit and scenario tests as UWP changed slightly.
Fixes #1670 
skip ci please

Update docs to explain how to run tests as UWP

---

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.Tests.sln
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.1.0.cs

* Updated sln with a ref to common.infrastructure to fix intellisense in VS.
* Removed StringBuilder wherever used and replaced with xunit Asserts.
* Added setup/execute/validate/cleanup comments.
* Instantiated most variables at the top of the test case and set to appropriate values in the setup section.

Updating scenario TypeClientTests

---

release-notes/SupportedFeatures-v1.1.0.md

Fix the link to .NET Core 1.1 release notes.

---

src/System.Private.ServiceModel/src/Internals/InternalSR.cs
src/System.Private.ServiceModel/src/Internals/System/Runtime/AsyncResult.cs
src/System.Private.ServiceModel/src/Resources/Strings.resx

Adding the missing message for an exception when an async result is completed twice.

Adding message for AsyncResultCompletedTwice error

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.4.1.1.cs

This scenario currently doesn't work in UWP since the DataContractResolver doesn't work in UWP, which is a serialization bug. Filed a serialization issue https://github.com/dotnet/corefx/issues/14879
#1708 #1709

Disable the DataContractResolver test in UWP. 

---

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/OperationFormatter.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.4.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/TestTypes.4.4.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.4.4.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.4.4.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlElementMessageHeader.cs

XmlElementMessageHeader.OnWriteHeaderAttributes threw PNSE because one required API was not available on NetCore. Adding the implementation for the method as the missing API is available now.
Fix #702.

Fix bug with sending Message with XmlElement MessageHeader

---

dependencies.props
src/Common/test-runtime/project.json
src/System.Private.ServiceModel/src/windows/project.json

* Several dependent packages were out-of-date as compared to corefx.
* This may resolve some F5 infrastructure failures.

Updating infrastructure dependencies.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.4.0.cs

* This test failure is due to an underlying problem in WinRTHttpClient behavior.
* Until that gets fixed we can skip this test on netnative runs.
* Amended this commit to also add an ActiveIssue for test case 'Message_With_MessageHeaders_RoundTrips'.

Adding ActiveIssue to ServiceRestart_Throws_CommunicationException test

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/RunReportingService.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs
src/System.Private.ServiceModel/tests/Stress/readme.md

The changes include:
- adding parameters to control timeouts
- adding a parameter to control channel pool size
- fixing error handling
- adding a missing instruction to readme

Updating stress tests with the latest version.

---

src/System.Private.ServiceModel/src/Resources/Strings.resx

Automated cleanup of unused resources in System.Private.ServiceModel. This removes about 75% of the file or roughly 300kb from the binary. The automated tool scanned for source references to resource strings. Github's diffing is showing additions, but there are no actual additions or edits, just removals. Verification was build+unit tests.

Resource string cleanup

---

src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/ExtensionCollection.cs

* Already used by WCF internally, no tests need to be explicitly written for it.

Add S.SM.ExtensionCollection to public contract.

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/OperationTimeoutTracker.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/RunReportingService.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/CommonTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexStreamingTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/HelloWorldTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/ITestTemplate.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs

This will allow us to detect stuck requests during stress (we saw signs of it in previous stress runs)

Fixing #1760 (timeout tracking)

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/OperationTimeoutTracker.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/CommonTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/HelloWorldTest.cs
src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs

Fixed timeout tracking for the tests that make multiple requests per test call.
Added some useful logging and tracing for detected time outs.
Simplified tests and minor code cleanup.

Fixed timeout tracking for the tests that make multiple requests

---

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs

Save stream in captured request context for streaming test  so to log stream position when detecting timeout.

logging stream position for streaming test

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Description/ContractDescriptionTest.cs

* PR #1836 exposed a method in the ContractDescription class, this commit adds a simple test to validate this method.
* We already have extensive tests that validate the rest of the ContractDescription class.

Adding unit test for ContractDescription.GetContract

---

Documentation/HowToUseWCFInContainers.md

The provided in-place sample code should be enough to create an .NET Core client WCF app and to run it in a container.

Adding a doc on how to use WCF .NET Core in Windows and Linux containers

---

dependencies.props
dir.props
dir.targets
src/Common/test-runtime/project.json
src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.csproj
src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.builds
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.builds
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.builds
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.builds
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.builds
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

Enables building and running tests both for their previous TFM / Target Group combinations as well as NetStandard2.0 / NetCoreApp2.0

Get tests to build and run against NS2.0 package

---

src/Common/test-runtime/project.json

, as having an exclude entry for NS 2.0 broke build.  Big thanks to @ericstj for noticing this.
@StephenBonikowsky, FYI.  This fixes build against packages as it's done on the official builds for me locally.

Fix build against packages

---

dir.targets

* Attempt to import the netstandard2.0 package fails during the sync.cmd step which is trying to do a package restore, at this point the package to import does not yet exist.

Fix test project sync error in VSO

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs

BuildBaseUri() already leaves a trailing slash so we don't need to add an extra one when generating the endpoint address.

Removing extra slash from URLs generated by ServiceUtilHelper

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatSoapTest.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/CompositeType.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfSoapService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfSoapService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpSoapTestServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

The PR enabled WCF to support soap encoded message. WCF now supports `OperationFormatUse.Encoded`.
Exposed XmlSerializerOperationBehavior.GetXmlMappings.
Fix #1549.
Fix #1797.

To support soap encoded message.

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs
src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/ContractDescription.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/DispatcherBuilder.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/OperationDescription.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ChannelHandler.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ClientOperation.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/DispatchOperation.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/DispatchOperationRuntime.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ImmutableDispatchRuntime.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ProxyOperationRuntime.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/TerminatingOperationBehavior.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/SessionTests.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Description/OperationContractAttributeTest.cs

Fixing #1402
Removing IssueAttribute from failing session tests
Exposing OperationContext.GetCallbackChannel in the contract

Fixing #1402

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs

The fix is to add an UnhandledExceptionFrame for timer callback in CallOnceManager.AsyncWaiter

Fix for #1694

---

src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/SetupValidationTests.4.1.1.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs

* Issue #1913: Breaking change from cofefx causing Peer trust scenarios to fail on Linux

Disable tests due to CoreFx breaking change.

---

src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj

* The harvested version of netcore50 (uap10.0) did not yet have API IChannelInitializer.
* Excluding it from compile when target group is uap10.0.

Fixing unit test common project.

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

* Using 4.3.0 baseline for System.Reflection.DispatchProxy and System.Security.Principal.Windows in our NetStandard 1.3 dependency tree.

Updated baseline for non-shared framework CoreFx packages ns1.3

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs

* Re-enable test case NetTcp_SecModeTrans_CertValMode_PeerTrust_Succeeds_In_TrustedPeople to run on any unix.
PR #1950 for Release2.0.

Enable test after Peer trust fix in CoreFx.

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs

* Re-enable test case NetTcp_SecModeTrans_CertValMode_PeerTrust_Succeeds_In_TrustedPeople to run on any unix.
PR #1949 for Master branch, release 2.1
Fixes #1913

Enable test after Peer trust fix in CoreFx (for Release 2.0).

---

src/Common/test-runtime/project.json

* Since we are currently only building and running for ns2.0 and everything else is being harvested we don't need several sections.

Remove unnecessary content from the common project.json in 2.1.

---

src/Common/test-runtime/project.json

* Since we are currently only building and running for ns2.0 and everything else is being harvested we don't need several sections.

Remove unnecessary content from the common project.json.

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Security/X509ServiceCertificateAuthentication.cs

This changes an exception happening deep inside a call stack which is non-obvious to an earlier exception with a message which the customer can easily reason about.

Disable PeerTrust certificate validation on OSX

---

Packaging.props
dependencies.props

Reverts dotnet/wcf#1976
After PR #1977 we can now go back to using the Preview3 label and enabling auto updating.

Revert "Revert "Move to preview3 prerelease label.""

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

After moving to netstandard2.0 netcore50 assets were lost, harvesting the old ones and inserting them to the package for now until we can replace it with newly built versions of WCF for UWP, coming soon.

Harvest old netcore50 asset and insert into package.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/BufferedReadStream.cs

Removing throws from no-op code in BufferedReadStream.

---

external/corefx-runtime/Configurations.props
external/corefx-runtime/corefx-runtime.depproj
external/dir.proj
external/runtime/runtime.depproj
external/test-runtime/XUnit.Runtime.depproj

* Get clrcompression.dll from CoreFX package
* Create corefx-runtime.depproj for specific CoreFX assembly placement
Applied @joperezr's suggestions, and they worked: `build.cmd -framework=uapaot -tests` runs cleanly on my machine.
Something I didn't do is move the `Microsoft.Private.CoreFx.UAP` ref copying into a new depproj: I left it in `netstandard.depproj` for now. For clarity, it makes sense to me to move it to a new depproj (the `uap;` in `netstandard/Configurations.props` seems weird) but it didn't seem needed. I couldn't figure out how to make a single `corefx.depproj` that deploys both ref and runtimes, otherwise I would have done that.
Fixes https://github.com/dotnet/wcf/issues/2019

depproj fixes for uapaot framework testing

---

src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs

The fix is to enable WCF to use ReflectionBased serialization for soap encoded message on uapaot.
Fix #2017

Enable WCF to Use ReflectionBased Serialization on Uapaot

---

external/corefx/Configurations.props
external/corefx/corefx.depproj
external/dir.proj
external/dir.props
external/netstandard/Configurations.props
external/netstandard/netstandard.depproj
src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj

Take the CoreFX ref-copy code out of netstandard.depproj and put it in the CoreFX depproj. The CoreFX depproj now copies runtime bits, but also copies ref bits with a custom target.
See https://github.com/dotnet/wcf/pull/2027

Restore CoreFX runtimes and refs in one depproj

---

Packaging.props
pkg/disableUap10.1.targets

* S.SM packages in 2.0 release do not support UAP 10.1, remove the section in the packages that claim this support.
* Fixes #1942

Remove support section for UAP 10.1

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

* Fixes #1983
* Anyone using the WCF 2.0 package in a UWP app would have failed because it would have been using a netstandard build instead of a netcore50 build.
* Adding a harvested build of Netcore50.

Fix S.P.SM 2.0 package adding harvested netcore50.

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj

System.Private.ServiceModel didn't support uapvNext, which was causing the restore of that TFM to pick the netcore50 assets instead of the netstandard2.0 ones. This change fixes that.
cc: @dagood @StephenBonikowsky @ericstj

Adding uapvNext support to System.Private.ServiceModel

---

src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.4.1.1.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.4.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.4.1.0.cs

The tests were disabled on NetNative. They now pass with NetCore2.0 and the latest UWP toolchain.
Fix #1708
Fix #1745
Fix #1730
Fix #702

Enable a Few Tests on NetNative.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/SessionTests.cs

System.ServiceModel.Channels.SocketConnection.Write calls different methods on different platforms:
On NetCore it calls CoreClrSocketConnection.WriteCore;
On uap/uapaot, it calls RTSocketConnection.WriteCore.
The two WriteCore use different networking APIs. As the networking APIs throw different exceptions, we get different exceptions in error cases. The fix is to let the test accept both exceptions. I opened https://github.com/dotnet/wcf/issues/2035 for tracking the actual issue.
Fix #2018

Modified a test case for uapaot run.

---

dependencies.props
src/System.Private.ServiceModel/src/Configurations.props
src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj

cc: @dagood @StephenBonikowsky @zhenlan 
Ok so this addresses several issues for the System.Private.ServiceModel package:
- References for uap10.0.15138 TFM were wrong, includding things it shouldn't
- We used to have an asset for unix/uap10.0.15138, which should never be the  case, so I removed it.
- We were basically copying the asset from netstandard2.0 into uap, which is wrong, as uap has it's own implementation
With these fixes in, I believe we now should be good to go to consume WCF from core-setup and produce the UWP metapackage.

Fixing System.Private.ServiceModel package for uap consumption with the right asset

---

external/dir.proj
external/wcf/Configurations.props
external/wcf/wcf.depproj

This enables the flow of a build-test build leg that uses `sync -ab` to download the WCF packages from the product build leg, then `sync -- /p:BuildAgainstPackages=true /p:OverridePackageSource=C:\git\wcf\packages\AzureTransfer\Release`.

New depproj for WCF for BuildAgainstPackages

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/FramingChannels.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportDuplexSessionChannel.cs

The base class TransportDuplexSessionChannel writes are already synchronized by its SemaphoreSlim _sendLock. It's grand-grand-child ClientFramingDuplexSessionChannel needs to do the same while writing to the connection in SendPreamble methods.

Synchronizing connection writes in ClientFramingDuplexSessionChannel

---

src/GenerateDepsJson.targets
src/src.builds
src/tests.builds

* Target named GenerateTestSharedFrameworkDepsFile is needed for test but was located in src.builds which is the product build path.
* Moving it to tests.builds which is where it should be.
* This fixes an issue in VSTS where we have to build product and test in separate build definitions.

Move target needed for test.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

Adding IDisposable to ClientBase<TChannel>

---

dependencies.props
src/System.Private.ServiceModel/tests/Scenarios/AllScenarioTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Configurations.props
src/dir.props
src/test.props
src/tests.builds

* Because of how long it takes to run a project through the ILC toolchain, collapse all the scenario test projects into a single test project for uapaot builds.
* Allow this option to be ignored in VSTS so that test result reporting in MC still looks good.
* Can still override locally if separate projects are desired.
* Had to update the expected test ILC package version.
* Fixes #2089

Build single scenario test project for uapaot.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.Tests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj

* Tests that switch threads using Task.Run or similar methods may hang or get the wrong callback.
* May have something to do with the number of cores on the test machine.
* The only way to test this is to merge the possible fix in order to run it through VSTS and the Helix machines.

Fix possible thread issue with some tests.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs

We also need to have the fix in uwp6 branch.
Fix #2145

Fixed NullRef in SocketConnection.CancelSendTimer.

---

external/runtime/runtime.depproj
src/tests.builds

* When syncing Microsoft.TargetingPack.Private.NETNative was pulling in an old version of S.P.SM into the runtime folder which was causing some type not found failures.
* The failure was only observed when building against packages using the OverridePackageSource property which is the Helix scenario, the typical local dev workflow avoided this issue due to how the test bin dirs are put together.
* Also adding a condition so that the new single scenario test project will only be compiled if OuterLoop is true.

Exclude old version of S.P.SM from getting pulled in.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TextMessageEncoder.cs
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/TextEncodingTests.4.1.0.cs

The fix is to simply match the quotes handing logic in IsCharSetSupported() to the one already implemented in GetEncodingFromContentType().
Tests to follow shortly...

Adding support for quoted char set in Content-Type

---

dependencies.props

We have some changes in coreclr doing resource lookup fallback for the missing resources in PRI files. This is needed to be picked up in wcf repo to avoid getting the missing resources and end up with ArgumentNullException

Update the coreclr package version

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/Addressing.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/AddressingVersion.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageHeader.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageVersion.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestReplyCorrelator.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/PrimitiveOperationFormatter.cs
src/System.Private.ServiceModel/src/System/ServiceModel/EndpointAddress.cs
src/System.Private.ServiceModel/src/System/ServiceModel/XD.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.Tests.sln
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/MessageVersionTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/HttpSoap11WSA2004ServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/HttpSoap12WSA2004ServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

This uses PR #2099 by @davidreher as the base. Changes from that PR are:
- Rebased to master
- Fixed the string resource references
- A couple of small fixes to remove throwing some PNSE which were effectively dead code
- Added ended to end scenario tests for SOAP11 and SOAP12 varients

Adding support for AddressingVersion WSAddressingAugust2004

---

dependencies.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs

Move forward the dependent versions to pick up latest networking libraries and modify test security helper to account for differences in behavior on UWP.

Fixes to tests to enable UWP certificate scenarios to succeed

---

netci.groovy

The name of the new job as is conflicted with an existing job, need to make it unique so it creates a separate job.

Ensure new UAP CI Job has unique name.

---

dependencies.props
tools-local/targetgroups.props

* Need to move from netcoreapp2.0 to netcoreapp2.1 in master branch.
* Fixes #2230 
* Also includes the changes to dependencies.props to use the latest corefx and other dependencies.

Support netcoreapp2.1

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.4.1.0.cs

* The UPN test on Linux/Osx is failing because of issue 2147

Exlude test failed by active issue 2147

---

BuildToolsVersion.txt
dependencies.props

With this change BuildTools will automatically get updated to the latest version.
The BuildTools used in wcf is a bit old. Updating to the latest here to ensure the auto-updates will work in the future. I'm hoping no breaking changes happened in the last month.

Update BuildTools automatically when new versions are available.

---

lab/src/Microsoft.ServiceModel.Syndication/src/Microsoft.ServiceModel.Syndication.csproj
lab/src/Microsoft.ServiceModel.Syndication/src/csprojForCodeFormatter.txt
lab/src/Microsoft.ServiceModel.Syndication/tests/Microsoft.ServiceModel.Syndication.Tests.csproj

- Change M.SM.SyndicationFeed to be a .NET Standard 2.0 library
- Change tests to use official .NET Core 2.0 release from preview

Fix ServiceModel.SyndicationFeed project dependencies

---

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/XmlSerializerOperationFormatter.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatSoapTest.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/CompositeType.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfSoapService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfSoapService.cs

XmlSerializerOperationFormatter's ctor did not use XmlSerializerFormatAttribute.IsEncoded value, which was wrong.
Fix #2264

Fix Bug in XmlSerializerOperationFormatter.

---

BuildToolsVersion.txt
dir.props

* to prerelease-02015-01
* Also fixing an issue caused by the new roslyn compiler used in the updated buildtools that will cause errors without this fix.
* See https://github.com/dotnet/corefx/pull/24076

Update BuildTools version, and fix for new roslyn compiler.

---

netci.groovy

* We should enforce Service and Client certificate tests on non windows
platforms as well.
* The change will be in two stages. The first stage is to change the CI
nightly runs that won't affect PRs. If it is reliable for more than one
week, will change the PR runs.

Enforce Service and Client Certificate tests on non windows platforms - Testing CI change

---

dependencies.props
external/corefx/corefx.depproj

* The UAP package in corefx was recently changed to be version 4.6 but the NETCore.App package is still 4.5.
* We were using a single variable for the version of all CoreFx packages, now need to split it so there is a separate one for the UAP package.

Update UAP package version.

---

netci.groovy

* CI Nightly have been green for one week. The CI PR can
be safely enabled.
@dotnet-bot  test ci please

Enable certificate tests on both CI PR and nightly

---

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IXmlSerFormatAttrServices.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlSerFormatAttrServices.cs

**Issue**
In the original implementation , to verify the return void service method in client, a static variable in service was used in the void set method to set the variable and call a get method to return the static variable for result verification.
It caused some problem which looks due to multithreading access to the static variable, test fail intermittently in helix run as the GetIntParamsProperty not always return expected result.
**Fix**
Thanks for Shin's advice, use ConcurrentDictionary(Guid, Object) to set and get value fixes the muti-thread access issue (without involving WCF session).
cc: @shmao , @StephenBonikowsky, @huanwu

Fix XmlSerializerFormatAttribute test issue

---

src/shims/shims.proj

When first creating the ServiceModel shim in 2.0.0 I did not add the section needed to get it signed.

Sign the ServiceModel shim in 2.0.0

---

Packaging.props
pkg/baseline/packageIndex.json

* This will update the nuspecs to show a dependency on 4.4.1 instead of the previous 4.4.0 version.
* Will dual check-in to VSTS

Move package baseline version to 4.4.1

---

dir.props

* See issue #4094 at NuGet: https://github.com/NuGet/Home
Bug in 2.0.0 preview versions of CLI do not like it when the first item in a list of sources to restore is a file path and not a url. By making sure a url is first we work around the issue.

Workaround for path not supported error when syncing sources.

---

dependencies.props
external/test-runtime/XUnit.Runtime.depproj

* CoreFxBaseLinePackageVersion, this was causing us to pull in some old packages of CoreFx.
* XunitNetcoreExtensionsVersion, this older version needed to be updated to work with newer CoreFx packages.
* A couple packages that XUnit depends on also needed to be updated.

Update some dependencies that aren't done by the auto updates.

---

external/corefx/corefx.depproj

* System.ComponentModel.Composition
* Looks like package Microsoft.Private.CoreFx.NETCoreApp is failing to pull this in, manually adding this package reference.

Test syncing fails to pull in this needed assembly.

---

pkg/baseline/packageIndex.json
src/System.Private.ServiceModel/dir.props

* Skipping forward to 4.1.3.2 because the servicing release of uwp6.0 used version 4.1.3.1

Version forward S.P.SM

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs
src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs

This property could be used to disable for each HTTP query keep-alive header.

KeepAliveEnabled property implementation for HttpTransportBindingElement

---

external/test-runtime/XUnit.Runtime.depproj
src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.csproj
src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/OSAndFrameworkTests.4.1.1.cs

* This has been broken since moving to buildtoolsv2 as the 'TestNugetRuntimeId' property that was used for this purpose was removed.
* Also removing a few OS versions that are EOL and adding a couple new ones.
* Adding a test case that can be enabled whenever a new OS version is added to the lab so the RID can be confirmed in a temp run and then added to Infrastructure.Common

Update test infrastructure to detect what OS it is running on.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

Expose ChannelTerminatedException in the S.SM.Primitives contract.

---

src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpSecurity.cs
src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpSecurityTest.cs

* Already public in the implementation.
* If BasicHttpSecurityMode is set to Message or TransportWithMessageCredential throw PNSE.
* Fixes #2365 
* Including a unit test.

Make BasicHttpSecurity default constructor public in the contract.

---

dependencies.props

* Support for UWP is currently broken, disabling the sections of the dependencies.props file that auto updated versions of files needed for UWP.

Disable auto update of ProjectNtfs

---

run.cmd
run.sh

* Restoring buildtools failed with...
* NuGet.Configuration.NuGetConfigurationException: Failed to read NuGet.Config due to unauthorized access.
* This PR in CoreFx fixes the problem.

Port of dotnet/corefx#25644

---

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

* On Win10 machines NuGet is picking win7 instead of win which is technically correct.
* Moving the win7 assets under win/lib/<TFM> fixes the problem.

Move win7 harvested binaries under runtimes/win/lib

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs

* Test Case: ExpectedExceptionTests/ServiceRestart_Throws_CommunicationException

Skipping test case for WCF Issue #2626

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs

* Test case: Binding_Http_BasicHttpBindingTests/HttpKeepAliveDisabled_Echo_RoundTrips_True

Skipping test case for WCF Issue #2624

---

dir.props
pkg/baseline/packageIndex.json
src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj
src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj

cc: @zhenlan @weshaggard @ericstj 
Updating the UAP TFM on WCF to match corefx.
@ericstj I didn't update the packageIndex inboOn for uap RS3, since these guys are a bit special given that we still had assets that applied to RS3 on the packages. Do we want to update the package index and have these guys have a placeholder for RS3 instead? or should we do the TreatAsOutOfBox supression?

Updating UAPvNext TFM

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs

* WCF issue #1886, tracking a core-eng issue dotnet/core-eng#775 which has been closed as fixed.
* The tests should now work.

Issue for skipping these tests has been closed in core-eng

---

UpdatePublishedVersions.ps1

* Needed to publish build info to dotnet/versions.
* See https://github.com/dotnet/core-eng/issues/2734
* See https://github.com/dotnet/core-eng/issues/2772

Workaround for GitHub disabling weak crypto.

---

BuildToolsVersion.txt
external/test-runtime/XUnit.Runtime.depproj
external/test-runtime/optional.json

Lengthy explanation but want to make sure I capture all the info in one place.
In order to move to TLS 1.2 Security Protocol as required by GitHubClient @MattGal created a buildtools branch for uwp6.1 containing [This Fix](https://github.com/dotnet/buildtools/commit/1459748487f6da9be11806fda384f7ab56f5ce4c).
This new buildtools uwp6.1 branch was snapped before [This Fix](https://github.com/dotnet/buildtools/pull/1630) was made in buildtools that fixed a [CoreClr breaking change](https://github.com/dotnet/wcf/pull/2157) for any Repos that have external dependencies.
A PR will be ready in buildtools shortly to update the uwp6.1 branch with the fix from @safern (tracked with dotnet/buildtools#1954)
This PR is a cherry-pick of @tarekgh 's #2151 which is needed together with the buildtools …

Update the buildtools and xunit runner packages

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.CoreClr.Windows.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalTestDetectors.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.props
src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs

Also adds test that's only enabled when setting the Long_Running property. This is to enable running the test in CI and nightly's but not slow down individual local runs.

Fix http timeout on windows

---

pkg/baseline/project.json

* The last servicing release of branch 2.0.0 was simultaneous with the servicing release of 1.1.0, since 2.0.0 is a 'fat package' it also contains 1.1.0 binaries. Because of the simultaneous release the new 1.1.0 packages (4.3.1) were not yet on NuGet, therefore we had to privately provide 2.0.0 the "not-yet released" 1.1.0 package in order to build the package for 2.0.0.
* Updating 2.0.0 so that it pulls down the 1.1.0 packages it needs from NuGet for harvesting.
Fixes #2658

Download packages for harvesting.

---

UpdateDependencies.ps1

* BuildTools change in behavior.
* Thanks @dagood for catching this.

Update MSBuild.exe to MSBuild.dll

---

dependencies.props

Current set of CI failures for PRs in release/2.1.0 are in part because we need to update the buildtools version and the Microsoft.DotNet.Build.Tasks.Feed package.

Update release/2.1.0 to use latest preview2 buildtools version.

---

dependencies.props

Manually updating dependencies to various packages built from release/2.1.0 branches.
These will be different versions in most cases for Master branch.

Stebon/2.1.0/update dep props for2.1 release

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs

#1888 happened due to 2 timeout timers competing to set which operation was aborted. The fix is to simplify the logic that decides whether to throw a timeout exception.

Fixing WCF 1888 by eliminating timing issue

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

This would fix #2708 and unblock further testing of short timeouts

Using local variable to avoid null ref

---

dependencies.props
external/runtime/runtime.depproj

WCF dependencies should now be updated based on the [ProdCon release candidate](https://github.com/dotnet/versions/tree/8f78fc523bfef40b28d4fbf5a0a51d4da7e373cf/build-info/dotnet/product/cli/release/2.1).
@dagood I would like a review of the manual dependencies I'm updating in this PR. I don't remember why these were not part of the auto-update, I updated them now and haven't seen any negative side effects so far.
`<CoreFxBaseLinePackageVersion>2.2.0-preview1-26216-02</CoreFxBaseLinePackageVersion>`
- Used in pkg\baseline\baseline.props
- Used in external\harvestPackages\harvestPackages.netstandard1.6.depproj
`<DotNetHostPackageVersion>2.1.0-preview2-26314-02</DotNetHostPackageVersion>`
- Used in external\runtime\runtime.depproj for packages...
-    Microsoft.NETCore.DotNetHost
- …

Update manual dependencies for release/2.1

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs

Updated with two PRs from @KKhurin 
#2709 
#2704

Squashed commit of Master merge to release/2.1.0

---

src/publish.proj

Based on dotnet/corefx#28991
@weshaggard in VSTS I will also add the "Sign Packages" step in our Publish build definition.
Are there any other changes I have missed that need to be made in order to enable signing our packages?

Enable package signing

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs

Now that SocketsHttpHandler is the HTTP client being used, we can add the Expect header to avoid sending the body twice when there's an authentication challenge.
Also improved error handling for when DNS lookup fails. This was causing a test failure (wrong exception) on win7.

Use Expect 100-Continue header

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs

* Failure is resolved as part of moving to SocketHttpHandler in CoreFx.
* Varified in VSTS test build and run.
* Fixes #2626

Re-enable test case due to issue #2626

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs

Numerous tests were getting skipped in VSTS runs by accident.
After enabling them we found these failing on SLES for an already discovered issue that needs investigation.
See issue #2561

Active issue on tests failing with same issue.

---

dir.props
src/System.Private.ServiceModel/dir.props

* Change the public key of WCF assemblies to MSFT.
* Remove AssemblyKey from library specific dir.props
* We only need to set this once in the root dir.props
(cherry picked from commit 39e11fac133c972ffb97a7e54544fdc1a46bdc78)

Change the public key of WCF assemblies to MSFT. (#2812)

---

build.proj

* Fixes download contentions within nuget that causes occasional errors.
* Back porting from new versions of build.proj in our later branches.

Restore from test-runtime project.json first.

---

pkg/baseline/baseline.packages.props
src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj
src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj
src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.csproj
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj
src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj
src/System.ServiceModel.Http/ref/System.ServiceModel.Http.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj
src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj
src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj
src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj
src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj
src/System.ServiceModel.Security/ref/System.ServiceModel.Security.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj

* Also produces non-stable versioned packages.
The new packages produced look like...
System.Private.ServiceModel.4.1.2-servicing-26227-0.nupkg
System.ServiceModel.Duplex.4.0.3-servicing-26227-0.nupkg
System.ServiceModel.Http.4.1.2-servicing-26227-0.nupkg
System.ServiceModel.NetTcp.4.1.2-servicing-26227-0.nupkg
System.ServiceModel.Primitives.4.1.2-servicing-26227-0.nupkg
System.ServiceModel.Security.4.0.3-servicing-26227-0.nupkg
The assembly versions are...
System.Private.ServiceModel.4.1.2   -   4.1.0.2
System.ServiceModel.Duplex.4.0.3   -   4.0.1.1
System.ServiceModel.Http.4.1.2   -   4.1.0.1
System.ServiceModel.NetTcp.4.1.2   -   4.1.0.1
System.ServiceModel.Primitives.4.1.2   -   4.1.0.1
System.ServiceModel.Security.4.0.3   -   4.0.1.1

Increment WCF packages and assemblies in release/1.0.0

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs

Re-enable tests which use a custom server certificate validation callback handler for HTTPS on platforms which are using a version of libcurl which doesn't use OpenSSL
Fixes #1295
Fixes #2346

Re-enable tests which use a custom server certificate validation callback handler

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs

We were incorrectly directly parsing the User-Agent header when it's a multi-valued header. This change causes `HttpRequestHeaders` to handle the special multi-value parsing that it required for the User-Agent header.
Fixes #2673

Fix user-agent headers

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs

Re-enable tests which use a custom server certificate validation callback handler
(cherry picked from commit aad7e5033213a33577aa7d281b825855e3efbc9b)

Port of PR #2865 from mconnew/EnableHttpsCertCallbackTests

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs

Extend test timeout to 40 secs.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs

Extend test timeout to 40 secs. (release/2.1.0)

---

external/harvestPackages/harvestPackages.netstandard1.6.depproj
pkg/baseline/packageIndex.json
src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj

* For target frameworks netstandard 1.0, 1.1 and 1.3 we should be harvesting assemblies from the latest package released from the 2.0.0 branch, in this case package version 4.3.1. This is because the 2.0.0 branch will continue to be serviced and we should be harvesting those most recent servicing updates.
* The package dependencies between WCF packages should always be of the same version since we now release all the WCF packages in sync.

Fix packaging issues for release of WCF 4.5.1 packages.

---

src/packages.builds

***EDITED***
I included comments with the code, should be pretty self explanatory, here are the scenarios...
1. Nightly builds, local builds not setting any flags.
All WCF and SvcUtil packages get built.
2. Stable packages are needed for either release or for release candidate testing.
-If the flag for stable packages is set but the WCF or SvcUtil flags are not then no packages are built.
-The WCF and/or SvcUtil flags must be set in conjunction with the flag for building stable packages in order to produce the desired packages.
-The reason for this is because we don't want stable packages getting built unintentionally which would then mean we need to clean-up MyGet.

Give more options for deciding which packages to build.

---

src/packages.builds

* In order to be able to modify these properties based on their values, in particular as set in VSTS builds they need to be treated as local properties.

Make properties as local.

---

Packaging.props
pkg/baseline/packageIndex.json
src/System.Private.ServiceModel/dir.props
src/System.ServiceModel.Duplex/dir.props
src/System.ServiceModel.Http/dir.props
src/System.ServiceModel.NetTcp/dir.props
src/System.ServiceModel.Primitives/dir.props
src/System.ServiceModel.Security/dir.props

* Incremented assembly and package versions.
* Update comments in the packageIndex.props.

Roll pkgs and assemblies forward after 2.0.9 servicing release.

---

dir.props
src/System.Private.ServiceModel/dir.props

* Change the public key of WCF assemblies to MSFT.
* Remove AssemblyKey from library specific dir.props
* We only need to set this once in the root dir.props

Change the public key of WCF assemblies to MSFT.

---

UpdatePublishedVersions.ps1

* #2676 added support for TLS 1.2 for updating wcf dependencies.
* This change does the same thing for updating the versions repo.

Fix script to support TLS 1.2 GitHub requirement.

---

dependencies.props

* Only auto-update WCF and NETStandard.Library package updates.
* I will also update the WCF build definition to only update the Versions repo on-demand.

Update dependencies.props file in release/2.0.0

---

dependencies.props

* Only auto-update WCF and NETStandard.Library package updates.
* I will also update the WCF build definition to only update the Versions repo on-demand.
* I updated the commit hashe for StandardCurrentRef and then ran 'UpdateDependencies'.

Update dependencies.props file in uwp6.0 branch.

---

dependencies.props

* Only auto-update WCF, NETStandard.Library and buildtools package updates.
* I will also update the WCF build definition to only update the Versions repo on-demand.

Update dependencies.props file in release/2.1.0

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

*** This is a cherry-pick of #3120 ***
* HttpClientHandler for uap does not support a non-NetworkCredentialManager type.
* #if/#endif ...ing the piece of code that is causing this PNSE error.
* Regression was introduced via: https://github.com/dotnet/wcf/pull/2668

Do not use CredentialCache when building for uap.

---

dependencies.props
external/corefx/corefx.depproj
external/runtime/runtime.depproj

* Renamed variable "PlatformPackageVersion" to "MicrosoftNETCorePlatformsPackageVersion" for clarity.
* Removed "Microsoft.NETCore.TestHost" from the runtime dependency project as it does not appear to be used anywhere.
* Renamed variable "CoreClrPackageVersion" to "MicrosoftNETCoreRuntimeCoreCLRPackageVersion" for clarity.
* Set NETStandard.Library version to the stable 2.0.3 release.
* Remove "System.Net.Http.WinHttpHandler" as we no longer have that dependency.
* Removed "CoreFxExpectedPrerelease" in dependencies.props as it is not used anywhere.
* Remove package reference to "runtime.native.System.Data.SqlClient.sni" as it is not needed for WCF.

Update and cleanup dependencies.

---

src/svcutilcore/src/GenerateThisAssemblyCs.targets

The assembly version in the text will be 1.0.0-preview1 because it read the value https://github.com/dotnet/wcf/blob/f483e9fd6610aefd728aeb76a7df32d707240295/Packaging.props#L5. However we cannot change it to empty string. This change is to workaround this issue for the tool RTM release. Need review this issue later. 
@StephenBonikowsky @mconnew @Lxiamail

Do not use PreleaseLabel when to get the version.

---

dependencies.props

The version for this branch needs to be 2.0.0 not 2.0.3, when this change was initially made CI and VSTS weren't building so the failure was missed.

Was using the wrong NetStandardVersion.

---

src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/CommandLineParser.cs
src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/ToolConsole.cs
src/svcutilcore/src/Resources/Strings.resx
src/svcutilcore/tests/SvcutilTests.cs
src/svcutilcore/tests/dotnet-svcutil.xmlserializer.Tests.csproj

Fixes #2882
With this code change, we only want to support "--" before name and "-" before abbreviation. 
Take command line option "out" for an example:
Before change, argument should start with "/out", "-out", "/o" or "-o"
After change, we only allow "--out" and "-o"

Change svcutil.xmlserializer's command line argument from "/option" to "--option"

---

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs

* Issue tracked by https://github.com/dotnet/wcf/issues/3112

Skip failing test on UAP runs.

---

src/svcutilcore/src/Resources/Strings.resx

Replace all `\r\n` with `&#13;&#10;` in the resource file.
#3241

Use escape characters in resource file

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IXmlSerFormatAttrServices.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlSerFormatAttrServices.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpXmlSerFormatAttrServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config
src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs

These tests are ported from desktop, before test fix, I mistakenly applied the [XmlSerializerFormat] attribute to service implementation class not the contract interface, so the attributes doesn't take effect.

Fix XmlSerilizerFormat test issue

---

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd

* With the move to Arcade the destination bin drop is a little different.
We made this same change to the StartWCFSelfHostedSvcDoWork.cmd script.
We didn't realize it was also needed initially because this script is run on our server machines not locally.
But when it ran on our servers and failed tests started failing due to not being able to find the CRL certificate on the server, which is one of the things that this script does when it builds and runs the certificate generator.

Fix pathing issue.

---

eng/SendToHelix.proj
eng/pipelines/wcf-base.yml

The ServiceUri variable was not set and available to the InstallRootCertificate.sh script at the time it was run.

Provide ServiceUri prop to Helix environment.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

* This test case is know to be failing, we need it to fail on Helix in order to get a repro environment.

Enable broken test for investigation.

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSHttpTransportWithMessageCredentialSecurityTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.0.0.cs

Test cases being skipped...
...Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.0.0.cs
IRequestChannel_Async_Http_BasicHttpBinding
IRequestChannel_Async_Http_CustomBinding
...Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs
IDuplexSessionChannel_Async_Tcp_NetTcpBinding
...Scenarios\Binding\WS\TransportWithMessageCredentialSecurity\WSHttpTransportWithMessageCredentialSecurityTests.cs
Https_SecModeTransWithMessCred_CertClientCredential_Succeeds
...Scenarios\Binding\WS\TransportWithMessageCredentialSecurity\BasicHttpTransportWithMessageCredentialSecurityTests.cs
Https_SecModeTransWithMessCred_CertClientCredential_Succeeds

Skip tests for Issue 3610.

---

src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs
src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/OptionsStatics.cs
src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/ToolRuntime.cs
src/svcutilcore/src/Resources/Strings.resx
src/svcutilcore/tests/SvcutilTests.cs
src/svcutilcore/tests/dotnet-svcutil.xmlserializer.Tests.csproj

Add command-line option "quiet" for svcutil.xmlserializer, and fail the run when customer trying to use the tool directly

---

eng/pipelines/wcf-base.yml

* It only applies to un-official builds, on official builds it was causing a warning due to "A cyclical reference."

Move variable under appropriate condition.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs

Fix SynchronizationContext issue when calling IDuplexSessionChannel.Receive directly.
Fix tests which aren't correctly closing session.

Fix ChannelLayer tests

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityChannelFactory.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs

We have a policy that if a non-default sync context is being used, to avoid potential deadlock (e.g. with a single threaded sync context such as used by winforms and WPF) or thread starvation problems, we forcefully asynchronously continue execution on the worker thread pool.
We had a few code paths where this didn't happen. This fixes those code paths.

Fix some threading issues when using a non-default sync context

---

eng/pipelines/wcf-base.yml
global.json
src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/Binding.Tcp.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/Binding.WS.TransportWithMessageCredentialSecurity.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/Contract.Fault.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/Contract.XmlSerializer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/Extensibility.MessageInterceptor.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.IntegrationTests.csproj
src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

* For sending to Helix use netcoreapp2.1 as the primary scenario.
* Will add netcoreapp3.0 as a secondary test run in Helix as part of the SendToHelix project.

Make test projects support both netcoreapp3.0 and netcoreapp2.1

---

eng/FacadeAssemblies.targets
src/System.ServiceModel.Shim/System.ServiceModel.Shim.csproj

* This project is used to create a binary that is inserted to the System.ServiceModel.Primitives package.
* The package should not have been getting generated.

Stop building a package for the System.ServiceModel.Shim project.

---

eng/pipelines/UpdatePRService.yml

* Between an environment variable being set in one script and used by another script too many things can happen to make the variable not be available to the second script.
* That is what happened, some infrastructure change in Arcade broke this so now changing so that we don't depend on the environment variable persisting.

Fix script logic to not depend on env variable.

---

Directory.Build.props

* Remove copyright made redundant by dotnet/arcade#2635.
* Fixes #3632 , technically this issue was already fixed with the last Arcade update we took, just using this PR to close the issue.

Remove redundant copyright.

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/OSAndFrameworkTests.4.1.1.cs

* Our infrastructure needs to get the RID of the platform it is running on in order to properly support our conditional facts.
* I also updated the error messaging on the OSAndFrameworkTests.OSID_Was_Detected() test so that when we hit this failure in the future the logs tell us what the RID was so we don't have to guess when updating the OSHelper class List<Tuple> like I am this time with "sles.15".

Adding support for Linux platform SLES version 15.

---

src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj

* Update "NETStandard.Library" pkg dependencies to version 2.0.3 to get the latest serviced netstandard packages.
* Explicitly added "System.Net.Security" and "System.Net.WebSockets.Client" to use updated serviced versions not being picked-up implicitly by S.P.SM.

Fix component dependency vulnerabilities.

---

eng/pipelines/linux.yml
eng/pipelines/macos.yml
src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj

* Windows build machines do not have PS v6 so we can't use "pwsh" to run powershell scripts.
* Removing the packing step from the Linux and MacOS builds as we don't need to build packages on those build legs.

Change powershell command back to 'powershell'.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs

This is to fix the issue #38609 (Cloning SecurityBindingElement misses EnableUnsecuredResponse).
Also ref #3653  (EnableUnsecuredResponse flag not supported)

Propagating EnableUnsecuredResponse while cloning

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs

Sometimes DuplexChannelShapeTests were throwing when running locally as the WebSocket was already closed. This fixes the it by not attempting to close and already closed WebSocket.

Fix issue with WebSocket already being closed sometimes

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs

We weren't passing an appropriate CancellationToken when reading from the stream.
Fixes #3590

Fixed problem with HTTP streamed mode timeout

---

src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj

* The S.SM.NetTcp package has a dependency on S.SM.Primitives 4.5.3 for .NETFx 4.6
* S.SM.Primitives 4.5.3 has a dependency on NETStandard.Library 1.6.1 or greater.
* NETStandard.Library 1.6.1 pulls in System.Net.Http version 4.3.0 which has a security advisory dotnet/aspnet#239
* Fixed by explicitly referencing NETStandard.Library version 2.0.3

Fix S.SM.NetTcp dependency on NETStandard.Library v1.6.1

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SslStreamSecurityBindingElement.cs
src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs

* Making this property public and adding it to the public API surface area.
* Fixes #3678

Make SslStreamSecurityBindingElement.RequireClientCertificate public.

---

src/System.Private.ServiceModel/tools/scripts/BuildCertUtil.cmd

* Since converting to .NET 3.0 SDK projects we now need that SDK in order to build.

Fix script to require VS 2019.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs

Fix missing timeout when reading response stream

---

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj

* Arcade infrastructure set the default value to 'MicrosoftShared' which resulted in token 31BF3856AD364E35
* It should have been set to 'Microsoft' for token b03f5f7f11d50a3a
fixes #3787

Fix public key token.

---

src/System.Private.ServiceModel/src/System/ServiceModel/HttpProxyCredentialType.cs
src/System.Private.ServiceModel/src/System/ServiceModel/HttpTransportSecurity.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs

Propagate all relevant properties from HttpTransportSecurity to HttpTransportBindingElement

---

dir.props

BuildTools picks up the old one by default:
https://github.com/dotnet/buildtools/blob/6736870b84e06b75e7df32bb84d442db1b2afa10/src/Microsoft.DotNet.Build.Tasks/PackageFiles/sign.targets#L5
.. .adding this to repos is in the end less work than updating build tools' default, though we could do that too.

Fix Authenticode signing

---

src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.Ref.csproj
src/System.ServiceModel.Http/ref/System.ServiceModel.Http.Ref.csproj
src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.Ref.csproj
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj
src/System.ServiceModel.Security/ref/System.ServiceModel.Security.Ref.csproj

* Reference assemblies also needed to be explicitly told to use the proper public key token.
* Fixes #3829

Fix public key token used for ref assemblies.

---

eng/UpdatePRService.yml

The CI build that happens right after a PR is merged will sync our test service to the head of the branch the PR was merged into.
The logic in the script that gets the name of the branch expected a one word branch name such as "master" and broke when the branch it tried to get the name of was "release/3.0.0".
This is a minor fix to first check if it is one of our 'release' branches so it does the right thing.

Fix script to use the correct branch name for updating the test service.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAlgorithmSuite.cs
src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs

* Also including adding the APIs to the public contract.
* SecurityAlgorithmSuite was already added to the S.SM.Security contract, added the static property TripleDes to this contract.
* Also adding SecurityBindingElement.DefaultAlgorithmSuite to the public surface area since that is how SecurityAlgorithmSuite.TripleDes is being set in this scenario.
This PR handles porting (from full fx) and adding types to the public contract for WSFederation project work item #3759

Port System.ServiceModel.Security.SecurityAlgorithmSuite.TripleDes

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

* The public contract for System.ServiceModel.Description.ClientCredentials needed to have System.ServiceModel.Security.SecurityCredentialsManager added as a base class.
* Added the overriden abstract CreateSecurityTokenManager method from S.SM.Security.SecurityCredentialsManager to the public contract for S.SM.Description.ClientCredentials
* The WSFederation tracking work item is #3879

Support S.SM.Description.SecurityCredentialsManager

---

src/System.ServiceModel.Security/tests/ServiceModel/SecutityBindingElementTest.cs

For #3860. 
@StephenBonikowsky , @mconnew , @HongGit

Unit test for SecurityBindingElement.KeyEntropyMode.

---

src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/KerberosSecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/SecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/UserNameSecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/X509SecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/ClientCredentialsSecurityTokenManager.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/IssuanceTokenProviderBase.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecuritySessionSecurityTokenProvider.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SspiSecurityTokenProvider.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs
src/System.ServiceModel.Primitives/tests/IdentityModel/SecurityTokenProviderTest.cs

Make SecurityTokenProvider APM methods behave the same as full framework and do the right thing with Async methods
This is the implementation for #3853

Implement SecurityTokenProvider APM and Sync methods

---

eng/UpdatePRService.yml

* The existing logic didn't account for a branch name being "release/3.1.0"
* We leveraged the azure devops variable 'Build.SourceBranchName' which returned the "last path segment in the ref string".

Fixing branch name logic.

---

eng/Versioning.props
src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj
src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj

* By default always ship WCF packages.
* By default do not ship dotnet-svcutil.xmlserializer packages.
* Enable or disable either one by setting their respective properties to true or false, can be done from the build definition that produces final release packages.
* Fixes #3975

Enable or disable shipping different packages.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs

* [Changeset 1615113](http://vstfdevdiv.redmond.corp.microsoft.com:8080/DevDiv2/DevDiv/_versionControl/changeset/1615113?_a=compare&path=%24%2FDevDiv%2FFX%2FFeature%2FNetFXDev1%2FNDP%2Fcdf%2Fsrc%2FWCF%2FServiceModel%2FSystem%2FServiceModel%2FChannels%2FSocketConnection.cs) in VSTS.

Port FullFx fix for SocketConnection sync/async timeout ignore problem.

---

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/XmlSerializerOperationFormatter.cs

* This fix was initially produced by @maheshnlrb with PR #3891 but the commit history got sufficiently scrambled that is was easier to reproduce his changes in a clean up-to-date branch.

Add "encodingStyle" attribute to generated SOAP message.

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/Binding.Tcp.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/Binding.WS.TransportWithMessageCredentialSecurity.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/Contract.Fault.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/Contract.XmlSerializer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/Extensibility.MessageInterceptor.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.IntegrationTests.csproj

Address part of issue #4006.
WCF test projects doesn't violate below xunit warnings, so I removed the suppress config from related csproj files in this single PR. 
xUnit1003
xUnit1006
xUnit1013
xUnit1014
xUnit2006
xUnit2010
For the other violations listed below, will address each in separated PR.
xUnit2000
xUnit2009
xUnit1024
xUnit2013

Remove not violated xUnit warnings in wcf test projects.

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/Binding.Tcp.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/Binding.WS.TransportWithMessageCredentialSecurity.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/SessionTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/Contract.Fault.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/Contract.XmlSerializer.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/Extensibility.MessageInterceptor.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.IntegrationTests.csproj

Fix xUnit warning #2000 for wcf test projects.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

@mconnew I believe we discussed this, I don't see any reason why we can't add this to the public contract.
FYI @wouterroos

Add the default ctor for FaultException<TDetail>

---

src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj

Changing the pre-release label in Versions.props only affects the WCF packages.
To affect the dotnet-svcutil.xmlserializer package it has to be done in the project file.
This package ships on an entirely different cadence which is why it is handled separately like this.

Change release lablel for non-shipping package to rtm.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.IntegrationTests.csproj
src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.IntegrationTests.csproj

For #4006 .
Fix notes: renamed the private/static overloads method name by adding name suffix "_TestImpl".

Fix xUnit warning #1024 : Test method cannot have overloads.

---

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/Channels/HttpRequestMessagePropertyTest.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpsBindingTest.cs
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/Channels/TcpConnectionPoolSettingsTest.cs
src/System.ServiceModel.NetTcp/tests/ServiceModel/NetTcpBindingTest.cs
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/Channels/CustomBindingTest.cs
src/System.ServiceModel.Primitives/tests/Channels/MessageTest.cs
src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

Warning detail:  the generic overloads of Assert.Equal or Assert.StrictEqual are used with string. There is an optimized overload of both Assert.Equal and Assert.StrictEqual for string arguments.
For #4006 .

Fix xUnit warning #2006 for test projects.

---

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/Description/OperationContractAttributeTest.cs
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

[Detail](http://xunit.net/xunit.analyzers/rules/xUnit2009.html): Check substrings with Assert string methods like string.Contains, string.StartsWith and string.EndsWith, instread of Assert.True or Assert.False.
For #4006 .

Fix xUnit warning #2009 in test projects.

---

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj
src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj
src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj
src/System.ServiceModel.Primitives/tests/Description/ContractDescriptionTest.cs
src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs
src/System.ServiceModel.Primitives/tests/Security/SecurityNegotiationExceptionTest.cs
src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj
src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj

For #4006 .
**Warning detail:** Do not use boolean check to check for string equality. Assert.Equal should be used because it give more detailed information upon failure.

Fix xUnit warning #2010 in test projects.

---

src/svcutilcore/files/dotnet-svcutil.xmlserializer.targets
src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs
src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj
src/svcutilcore/tests/dotnet-svcutil.xmlserializer.IntegrationTests.csproj

Instead of making assumptions and parsing strings I get the location of the needed assemblies from the built-in msbuild 'ResolvePackageAssets' Task.
Fixes #4090
Cherry-pick this to the 3.1 servicing branch once it has been fully tested.

Fix pathing issues with the dotnet-svcutil.xmlserializer tool.

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs

* Uap was removed from TargetFrameworkMonikers in Arcade.
* Since we no longer run tests on this TFm we can just remove these conditional skips.

Remove UAP from test attribute skipping logic.

---

src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj

Currently released package is version 1.1.0 with assembly version 1.1.0.0
The package version had already been updated to 1.2.0
I've updated the assembly 'patch' digit since the only fix/change in the assembly is #4145

Update assembly version of xmlserializer tool.

---

NuGet.config

dotnet-tools-internal is no longer in use.

[release/3.1.0] Add dotnet-eng feed

---

src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs
src/svcutilcore/tests/dotnet-svcutil.xmlserializer.IntegrationTests.csproj

List of assemblies passed on cmd line are now semi-colon delimited instead of colon delimited.

Add some missed changes for svcutilcore

---

src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs

This exposes `LocalClientSecuritySettings.DetectReplays` which is needed for SCT support in WsFederationHttpBinding.

Expose LocalClientSecuritySettings.DetectReplays

---

src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs

Exposing GenericXmlSecurityKeyIdentitfierClause is needed for WsFederationSecurityBinding effort as WsTrustChannelSecurityTokenProvider needs to set this clause type.
Exposing CloneCore() is needed so the derived WsTrustClientCredentails.CloneCore() will be called.

Exposing GenericXmlSecurityKeyIdentifierClause and virtual CloneCore().

---

src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs

For issue #3984 .
@HongGit ,@mconnew , @StephenBonikowsky
I am not sure if mark the FaultException class as Serializable is enough to make the scenario function work, let me know your concerns.

Mark FaultException as Serializable

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.0.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs

@HongGit , This is to skip the 4 failing tests for UWP run. Please review.

Skip 5 failing and unspport test on UAP runs.

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs
src/System.Private.ServiceModel/src/Internals/System/Runtime/IOThreadScheduler.cs
src/System.Private.ServiceModel/src/Internals/System/Runtime/ServiceModelSynchronizationContext.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CommunicationObject.cs

Scheduling a delegate via overlapped to the IO thread pool wasn't available when this project started. It is now available on Windows so bringing back this functionality to prevent extra thread creation.

IOThreadScheduler using IO Threads on Windows

---

azure-pipelines-arcade.yml

This was causing problems with release build due to the AudienceUri not matching in case.

Fix release build, WSFed is case sensitive on URI's

---

Directory.Build.props
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelSecurityTokenManager.cs

This allows RSTs to be generated with null token types (to match NetFx behavior) and includes a requested ComputedKeyAlgorithm in combined entropy scenarios.

Fix RST generation issues in WsFederation

---

global.json

The version of .NET 5 we were using had a bug which caused Windows auth with default credentials over https to fail.

Use NET5 version with Http auth bug fixed

---

src/dotnet-svcutil/lib/src/Shared/FrameworkInfo.cs

@HongGit, this is to split PR #4341 to contain product change only as suggested. 
Code change in this PR alone would enable the tool to support .Net5, the referenced WCF client packages would be still version 4.4.*, same as the released tool.
However, we happen to uncover a bug when publishing a WCF test project after running the tool, if the referenced WCF package version is 4.4.*, the published project binaries would be missing System.Private.ServiceModel.dll which cause the published .exe run fail, with error like below:
> Unhandled exception. System.IO.FileNotFoundException: Could not load file or assembly 'System.Private.ServiceModel, Version=4.1.2.4, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.
> File name: …

Make dotnet-svcutil tool support .net5.

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs
src/System.Private.ServiceModel/src/System/ServiceModel/HttpClientCredentialType.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/ClientCredentialsSecurityTokenManager.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs
src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs

When the server responds with both Negotiate and NTLM as supported authentication types, HttpClient will look in the credential cache for Negotiate credentials but not NTLM. This change allows specifying AuthenticationSchemes.IntegratedWindowsAuthentication on the HttpTransportBindingElement.AuthenticationScheme and WCF will add the credentials to the CredentialCache for Negotiate and NTLM.
Fixes #3694

Add support for AuthenticationSchemes.IntegratedWindowsAuthentication

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/IOThreadScheduler.cs

With recent changes to improve performance on Windows by bringing back use of IO completion ports, a bug was introduced on non-Windows platforms where cleaning up an IOThreadScheduler resulted in an exception due to attempting to free a null overlapped.

Fix IOTS cleanup on non Windows

---

src/System.Private.ServiceModel/src/System/ServiceModel/CallbackBehaviorAttribute.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfDuplexService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfDuplexService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/DuplexTestServiceHosts.cs
src/System.ServiceModel.Duplex/tests/ServiceModel/CallbackBehaviorAttributeTest.cs
src/dotnet-svcutil/lib/src/FrameworkFork/System.ServiceModel/System/ServiceModel/Description/TypeLoader.cs

For issue #1959.
@mconnew I've added the public property, it seems the feature should work as it's applied in the attribute implementation:
```
void IEndpointBehavior.ApplyClientBehavior(ServiceEndpoint serviceEndpoint, ClientRuntime clientRuntime)
{
...
dispatchRuntime.ConcurrencyMode = _concurrencyMode;
...
}
```
Regarding test scenario, I need your guidance on how to test it, what kind of combination for instance mode and concurrency mode would you suggest to use to test the feature? Thank you.

Expose ConcurrencyMode property in CallBackBehaviorAttribute.

---

src/System.Private.ServiceModel/src/System/IdentityModel/CryptoHelper.cs

The method `GenerateRandomBytes` has no callers. Removing it.
This was found while auditing the _dotnet_ repo code bases for calls to `RandomNumberGenerator.GetNonZeroBytes`. See also https://github.com/dotnet/wcf/issues/4377.

Remove some dead RNG code paths

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/FederationHttp/WSFederationHttpBindingTests.cs
src/System.ServiceModel.Federation/ref/System.ServiceModel.Federation.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsFederationBindingElement.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsFederationHttpBinding.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelClientCredentials.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelSecurityTokenManager.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs

Fix casing for WCF owned classes WsXxxx->WSXxxx

---

src/System.Private.ServiceModel/src/Resources/Strings.resx
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ClientWebSocketTransportDuplexSessionChannel.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportSecurityHelpers.cs
src/System.ServiceModel.Http/tests/ServiceModel/HttpIdentityTests.cs

Add limited support for SpnEndpointIdentity with HTTP

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ReliableOutputSessionChannel.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/ReliableSession/NetHttpBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/ReliableSession/NetTcpBindingTests.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/ReliableSession/WSHttpBindingTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfReliableService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfReliableService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/ReliableSessionOneWayTestServiceHost.cs

Fix OneWay only contracts with ReliableSessions

---

src/System.Private.ServiceModel/src/System/ServiceModel/Security/WSTrust.cs

For issue #4377. Have run tests locally with the change applied, see no regression.
@HongGit , @mconnew .

Remove dead code.

---

Directory.Build.props
NuGet.config
src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/FederationHttp/WSFederationHttpBindingTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/TestDefinitionHelper.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/Federation/FederationSTSServiceHost.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/Federation/SelfHostSecurityTokenService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/Saml2IssuedTokenTestServiceHost.cs
src/System.ServiceModel.Federation/ref/System.ServiceModel.Federation.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/LogHelper.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsFederationHttpBinding.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelClientCredentials.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelSecurityTokenManager.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs

This PR contains all the changes from #4398

WSFed static helpers and expanded tests

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/FederationHttp/WSFederationHttpBindingTests.cs

Internal build system does a credscan check to prevent accidentally committing real credentials. Recent tests added fake credentials in the code. This suppresses the resulting error.

Suppress credscan error for fake credentials

---

README.md

Update README.md to correct link to .NET Foundation projects, because dotnet.github.io is pointing to dotnet.microsoft.com instead of dotnetfoundation.org project page.

Update README.md to correct link to .NET Foundation projects

---

src/dotnet-svcutil/src/dotnet-svcutil.csproj

@HongGit, @mconnew 
On machine with .net5 installed only, dotnet-svcutil throw error like below:
This PR fixed the issue.

Support running dotnet-svcutil on machine with only .net5 installed

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/IOThreadScheduler.cs

Fix IOTS non windows condition in Cleanup

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/MruCache.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs

When using SecureConversation, an inner channel factory is used to obtain the Secure Conversation token. When using a load balancer, this can result in the session establishment and service request being made to different backend hosts resulting in the service call failing.

Make SecureConversation inner channel factory share the same HttpClient as outer factory

---

src/System.Private.ServiceModel/src/Internals/System/Runtime/FatalException.cs
src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs
src/System.Private.ServiceModel/src/System/IdentityModel/SecurityMessageSerializationException.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenException.cs
src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenValidationException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ActionMismatchAddressingException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ActionNotSupportedException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ChannelTerminatedException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectAbortedException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectFaultedException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/InvalidBodyAccessException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/EndpointNotFoundException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/InvalidMessageContractException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/MessageHeaderException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/MustUnderstandSoapException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ProtocolException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/QuotaExceededException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/MessageSecurityException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAccessDeniedException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityNegotiationException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SessionKeyExpiredException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/Tokens/SecurityContextTokenValidationException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ServerTooBusyException.cs
src/System.Private.ServiceModel/src/System/ServiceModel/ServiceActivationException.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs

Fixes #4448
Also improves the use of DataContractSerializer with FaultException\<TDetail\> so you don't need to provide typeof(TDetail) to DataContractSerializer.

Make all WCF exceptions serializable

---

src/Common/src/Internals/System/Runtime/Diagnostics/EventTraceActivity.cs
src/Common/src/Internals/System/Runtime/WcfEventSource.cs
src/Common/src/System/ServiceModel/Diagnostics/ExceptionUtility.cs
src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs
src/System.Private.ServiceModel/src/SMDiagnostics/System/ServiceModel/Diagnostics/ExceptionUtility.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityProtocol.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecuritySessionClientSettings.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs
src/System.ServiceModel.Federation/src/Resources/Strings.resx
src/System.ServiceModel.Federation/src/System/IdentityModel/Security/WrapperSecurityCommunicationObject.cs
src/System.ServiceModel.Federation/src/System/Runtime/TaskHelpers.cs
src/System.ServiceModel.Federation/src/System/Runtime/WcfEventSource.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Diagnostics/SecurityTraceRecordHelper.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelSecurityTokenManager.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Security/ISecurityCommunicationObject.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/ServiceDefaults.cs

Implemented BeginGetTokenCore and EndGetTokenCore to provide async implementation and fixed memory leak around ChannelFactory and channel lifetime.
Fixes #4462
Fixes #4461

Make federation implementation async and fix memory leak

---

release-notes/SupportedFeatures-v2.1.0.md

Its not supported so even the red xs are informative.

Documentation: Add line for WebHttpBinding

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs

Fixed Check for SecurityTokenManager initialization for web proxies with NTLM authentication: 
When using BasicHttpClient Bindings with additional authentication for enterprise style web proxies, a NullReferenceException was raised because of missing initialization of SecurityTokenManager (resulting member field was NULL). 
By extracting the AuthenticationScheme passed by the used binding and using it for deciding  whether SecurityTokenManager is needed or not, the NRE is removed and NTLM auth can be used successfully within the HTTP channel factory.

Fix NullReferenceException when using BasicHttpBinding and NTLM web proxy authentication

---

azure-pipelines-arcade.yml

Documentation (pending merge into arcade) can be found [here](https://github.com/jonfortescue/arcade/blob/OneLocBuildDoc/Documentation/OneLocBuild.md).
Sample of this task working in a build [here](https://dev.azure.com/dnceng/internal/_build/results?buildId=1048347&view=results).

Migrate to OneLocBuild

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportDefaults.cs

Fix #4562
- update HttpTransportBindingElement with Proxy property 
- update HttpChannelFactory to enable _proxy configuring with bindingElement.Proxy 
this commit enables clients to configure binding with fully specified IWebProxy object:
- address , 
- credentials 
- etc.

Update HttpTransportBindingElement with Proxy property to enable client to specify IWebProxy

---

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs

On slow CI machines concurrency tests were failing.

Fix callback concurrency tests

---

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj

Make dotnet-svcutil-lib InternalsVisibleTo MS.VS.WCF.ServiceReferences

---

src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs
src/dotnet-svcutil/lib/src/HelpGenerator.cs
src/dotnet-svcutil/lib/src/SR.resx
src/dotnet-svcutil/lib/src/xlf/SR.cs.xlf
src/dotnet-svcutil/lib/src/xlf/SR.de.xlf
src/dotnet-svcutil/lib/src/xlf/SR.es.xlf
src/dotnet-svcutil/lib/src/xlf/SR.fr.xlf
src/dotnet-svcutil/lib/src/xlf/SR.it.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ja.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ko.xlf
src/dotnet-svcutil/lib/src/xlf/SR.pl.xlf
src/dotnet-svcutil/lib/src/xlf/SR.pt-BR.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ru.xlf
src/dotnet-svcutil/lib/src/xlf/SR.tr.xlf
src/dotnet-svcutil/lib/src/xlf/SR.zh-Hans.xlf
src/dotnet-svcutil/lib/src/xlf/SR.zh-Hant.xlf

@HongGit , @mconnew,  
Fixing issue #4359,  to throw meaningful error when running dotnet-svcutil to update service reference in global tool context but from unexpected working directory (projectFile not found under the dir).

dotnet svcutil - add example for update option usage

---

src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.Ref.csproj
src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj
src/System.ServiceModel.Http/ref/System.ServiceModel.Http.Ref.csproj
src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj
src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.Ref.csproj
src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
src/System.ServiceModel.Security/ref/System.ServiceModel.Security.Ref.csproj
src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj

Fixes https://github.com/dotnet/wcf/issues/4237
See https://github.com/dotnet/designs/pull/222#issuecomment-861617052 for context.
@mconnew I verified these packages restore using the `net6.0` assets in the HelloAndroid sample from https://github.com/dotnet/maui-samples and at least a basic call to a SOAP webservice works.

Add .NET 6.0 TFM to packages

---

src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs

Allow dotnet-svcutil referenced package name end with dll.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
src/System.ServiceModel.Security/tests/IdentityModel/GenericXmlSecurityKeyIdentifierClauseTest.cs
src/System.ServiceModel.Security/tests/IdentityModel/GenericXmlSecurityTokenTest.cs

Adding api's which are missing from the contract for GenericXmlSecurityToken and GenericXmlSecurityKeyIdentifierClause. This is needed to support the WSTrustChannelFactory usage case where customers will need to access the returned security token's TokenXml property in some cases.

Add more apis for generic xml security token

---

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MtomMessageEncodingBindingElement.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

Fixes #1810
Specifically the comment [here](https://github.com/dotnet/wcf/issues/1810#issuecomment-930535649).

Add MtomMessageEncodingBindingElement to reference assembly

---

azure-pipelines-arcade.yml
eng/SendToHelix.proj

Same as https://github.com/dotnet/wcf/pull/4733 but on release/3.2.

Switch to 1ES servicing pools on release/3.2

---

src/System.ServiceModel.Federation/src/Resources/Strings.resx
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.cs.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.de.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.es.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.fr.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.it.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.ja.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.ko.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.pl.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.pt-BR.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.ru.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.tr.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.zh-Hans.xlf
src/System.ServiceModel.Federation/src/Resources/xlf/Strings.zh-Hant.xlf
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/IWSTrustChannelContract.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannel.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelFactory.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustRequestBodyWriter.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustUtilities.cs
src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs
src/System.ServiceModel.Federation/tests/System.ServiceModel.Federation.Tests.csproj
src/System.ServiceModel.Federation/tests/WSTrustChannelFactoryTest.cs
src/System.ServiceModel.Federation/tests/WSTrustChannelTest.cs

This is similar to what existed in .net framework with some small changes.
WSTrustChannel ctor takes a ChannelFactory rather than a WSTrustChannelFactory.
The new Async model has replaced the Begin / End model found in the original WCF release.
Common methods that were used in WSTrustSecurityTokenProvider and WSTrustChannel were moved to WSTrustUtilities.
An additional constructor was added that takes a separate IRequestChannel.

Adding support for WSTrustChannelFactory and WSTrustChannel

---

src/System.Private.ServiceModel/src/Internals/TraceCore.cs

Fix issue#4775 EventSourceException single event payload too large.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj
src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
src/System.ServiceModel.Primitives/tests/IdentityModel/SymmetricSecurityKeyTest.cs

This is to enable merging of PR using latest arcade versions which purposefully breaks builds using netcoreapp2.1

Remove netcoreapp2.1 usage and fix test compile error for obsolete crypto type

---

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/OperationSelectorBehavior.cs
src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ProxyOperationRuntime.cs

This fixes #4789 
Use MethodHandle.Value instead of the MethodInfo object. 
I'm not sure if anything else needs to be done, but Hot Reload is working now 🥳

Fix for Hot Reload in .NET 6 (issue #4789) - Use MethodHandle.Value

---

eng/SendToHelix.proj

I'm going to merge with skipping the regular checks as this only affects internal builds.

Update helix queue name for internal builds

---

eng/SendToHelix.proj
src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAppliedMessage.cs
src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpsTransportSecurityMessageCredentialsUserNameTestServiceHost.cs

Fix TransportWithMessageCredentials with TransferMode.Streamed missing security header

---

eng/Versions.props
release-notes/System.ServiceModel.Duplex.md
release-notes/System.ServiceModel.Federation.md
release-notes/System.ServiceModel.Http.md
release-notes/System.ServiceModel.NetTcp.md
release-notes/System.ServiceModel.Primitives.md
release-notes/System.ServiceModel.Security.md
release-notes/System.Web.Services.Description.md

According to [this article](https://github.com/dotnet/arcade/blob/e7ede87875f41a9b3df898ae08da5ebc96e24f56/Documentation/RestoreSourcesUpdateStatus.md), RestoreSources is already replaced by Nuget.config. 
Also update release notes to WCF Core 4.10 release.

remove RestoreSources and update release notes

---

src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs

It's already public in the implementation. This mirrors #2572 from years ago.

Make BasicHttpsSecurity default constructor public in the contract

---

src/dotnet-svcutil/lib/src/FrameworkFork/System.Runtime.Serialization/System/Runtime/Serialization/DataContract.cs

In my tests the DataContractAttribute could not be found, because Globals.TypeOfDataContractAttribute is a DataContractAttribute with ref. to the Framework Fork.
Because this Framework Fork won't be used in "real live" projects, the DataContractAttribute could not be evaluated.
To fix this, the code now searches for the same FullName and read the properties via reflection in order to build the DataContractAttribute used by the Framework Fork.
This fix will probably fix, because namespace will now be evaluated correctly
[#3812](https://github.com/dotnet/wcf/issues/3812)

Fix for DataContractAttribute evaluation

---

azure-pipelines-arcade.yml
eng/common/templates/job/source-build.yml
eng/common/templates/job/source-index-stage1.yml

This change is required to continue building PRs in the dotnet public repo.  The agents and images used in the new project / organization are identical and build regressions are not expected.  Updating files under eng/common is intentional to move as much as possible over to viable build agents (normally this is not done).
For questions / concerns, please stop by the .NET Core Engineering Services [First Responders Teams Channel](https://teams.microsoft.com/l/channel/19%3aafba3d1545dd45d7b79f34c1821f6055%40thread.skype/First%2520Responders?groupId=4d73664c-9f2f-450d-82a5-c2f02756606d&tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47).

Update public pool names

---

azure-pipelines-arcade.yml
eng/SendToHelix.proj

This change moves all of the docker images to the latest tag as part of https://github.com/dotnet/arcade/issues/10377.

Use latest docker containers

---

src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj

The primitives package wasn't shipping a reference assembly which resulted in over exposing implementation api's.

Add reference assembly to System.ServiceModel.Primitives package

---

release-notes/dotnet-svcutil-notes.md

This adds a hint to the release page for future versions and versions > v2.0.1
Addresses #4986
/cc @HongGit

Update dotnet-svcutil release notes

---

src/System.ServiceModel.Http/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Security.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/MtomMessageEncoder.cs

Fixes #4831
Also exposes UserNameSecurityToken as without it you can't use the token returned from the SecurityTokenProvider when using UserName credentials.

Mtom fixes

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Channels/MessageTest.cs

Expose CreateMessage method overloads with FaultCode parameter

---

src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/Description/ContractDescriptionTest.cs

Public OperationDescription.Begin/End/SyncMethod properties and add unit test

---

src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs

dotnet-svcutil: support vb and fsharp project dependencies

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Security.cs
src/System.ServiceModel.Security/tests/ServiceModel/SecutityBindingElementTest.cs

Relates to #4817, #3705. 
**Note:**
#4817 mentioned to expose both AllowInsecureTransport & EnableUnsecuredResponse,  this PR only exposes EnableUnsecuredResponse since the impementation of property AllowInsecureTransport doesn't exist in the class on WCF core, it needs to be discussed whether to add it.

Expose EnableUnsecuredResponse in SecurityBindingElement and add unit test

---

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.4.1.0.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Duplex.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs

Expose DuplexChannelFactory<TChannel> constructor with Type overloads

---

src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs

Unblock dotnet-svcutil if user project referenced .vcxproj

---

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj

Fix ci warning for release/4.10 branch: upgrade Nuget.xxx package version in dotnet-svcutil-lib.csproj

upgrade dotnet-svcutil-lib.csproj's Nuget package version

---

eng/Versions.props
src/System.ServiceModel.NetFramingBase/src/System.ServiceModel.NetFramingBase.csproj

System.Security.Principal.Windows's package shouldn't be referenced anymore as it got ingested into the .NETCoreApp shared framework with .NET 6.

Remove System.Security.Principal.Windows reference

---

src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs

dotnet-svcutil: differentiate dependencies with full path instead of assembly name

---

src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomVisitors/AddAsyncOpenClose.cs

Fixing issue #5282 . 
The bug is caused by commit https://github.com/dotnet/wcf/commit/97f9f4d019df9b496052b74f291ef65c0499a961 when addressing CloseAsync() code generation for multitarget project. The fix is when there's no .csproj in the working directory, it will take the else code path as before.

Fix obj null reference exception when run dotnet-svcutil from directory without existing csproj 

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

The MessageVersion properties Soap11WSAddressing10 & Soap12 were missing from the ref.
Also removed the non-existing file System.ServiceModel.Primitives.netframework.cs from the project file.

Update MessageVersion ref

---

src/System.ServiceModel.Primitives/src/System/ServiceModel/Dispatcher/InvokerUtil.cs

Use Expressions to generate InvokeDelegate. This is a performance improvement which will make callback dispatch slight faster by removing MethodInfo.Invoke calls and using LINQ expressions to compile a delegate which is strongly typed.

Use Expressions to generate InvokeDelegate

---

eng/Versions.props

Prepare for 6.2 preview release.

prepare main branch to be 6.2 branding

---

dotnet-svcutil.xmlserializer.sln
src/svcutilcore/src/Resources/xlf/Strings.cs.xlf
src/svcutilcore/src/Resources/xlf/Strings.de.xlf
src/svcutilcore/src/Resources/xlf/Strings.es.xlf
src/svcutilcore/src/Resources/xlf/Strings.fr.xlf
src/svcutilcore/src/Resources/xlf/Strings.it.xlf
src/svcutilcore/src/Resources/xlf/Strings.ja.xlf
src/svcutilcore/src/Resources/xlf/Strings.ko.xlf
src/svcutilcore/src/Resources/xlf/Strings.pl.xlf
src/svcutilcore/src/Resources/xlf/Strings.pt-BR.xlf
src/svcutilcore/src/Resources/xlf/Strings.ru.xlf
src/svcutilcore/src/Resources/xlf/Strings.tr.xlf
src/svcutilcore/src/Resources/xlf/Strings.zh-Hans.xlf
src/svcutilcore/src/Resources/xlf/Strings.zh-Hant.xlf
src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj

Description:
1. Increase version: 1.2 -> 1.2.1
2. Add resource xlf files
2. Move dotnet-svcutil.Xmlserializer.sln file to repository root to enable build by default (originally the solution's projects are part of System.ServiceModel.sln and was removed since [PR #4791](https://github.com/dotnet/wcf/pull/4791))

Prepare dotnet-svcutil.Xmlserializer tool build

---

src/System.ServiceModel.Http/src/System/ServiceModel/NetHttpBinding.cs
src/System.ServiceModel.NetTcp/src/System/ServiceModel/NetTcpBinding.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Duplex.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/ChannelFactory.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/ClientBase.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/DuplexChannelFactory.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/DuplexClientBase.cs

Shall we remove the [ConfigurationName](https://github.com/dotnet/wcf/blob/f229469c67dc1d46978833f72332d3ef16b3a75a/src/System.ServiceModel.Primitives/src/System/ServiceModel/ServiceContractAttribute.cs#L21C6-L21C6) property from ServiceContractAttribute as well?

Remove configuration api.

---

src/dotnet-svcutil/src/dotnet-svcutil.csproj

Support net8 SDK in dotnet-svcutil

---

src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs

The fix added .esproj to be a valid dependency project of a .csproj which runs dotnet-svcutil against.
Issue from the community: https://developercommunity.visualstudio.com/t/incompatibility-in-the-WCF-Web-Service-m/10595594

dotnet-svcutil: treat .esproj as a valid dependency project extension.

---

src/dotnet-svcutil/lib/src/FrameworkFork/System.Runtime.Serialization/System/Runtime/Serialization/DataContract.cs

Related issue from the VS community: https://developercommunity.visualstudio.com/t/Not-able-to-add-wcf-service-in-1786-re/10578713

dotnet-svcutil: fix IsTypeSerializable to enable type reusing serializable type

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/Binding.UDS.IntegrationTests.csproj

The latest release of CoreWCF.UnixDomainSocket package doesn't reference the latest release of CoreWCF.NetFramingBase, so force referencing version 1.5.2 of CoreWCF.NetFramingBase to address the security warning.

Fix CG issue in UDS test proj that referenced corewcf pkg.

---

src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/ServiceChannelProxy.cs

So that channels created through a `ChannelFactory<T>` without inheriting from `ClientBase<T>` can also benefit from the asynchronous disposal improvements introduced in #4865.
Fixes #5270

Make ServiceChannelProxy implement IAsyncDisposable

---

src/dotnet-svcutil/lib/src/Shared/TargetFrameworkHelper.cs

.NET7.0 is missing in the key-value table and will reference WCF 8.* packages after code generation.  This is a problem because WCF 8.* packages are not compatible with .NET 7.0, so add the mapping to reference WCF 6.2 packages for NET7.0 target to address this issue.

dotnet-svcutil: add reference to wcf 6.* library instead of 8.* for net7.0 target project.

---

azure-pipelines-arcade.yml

Currently WCF source isn't appearing on https://source.dot.net. This change should hopefully get it indexing again. We won't be able to verify until after an internal build has completed.

Enable source indexing for internal builds

---

src/dotnet-svcutil/lib/src/Metadata/MetadataDocumentLoader.cs

This update addresses a bug in the WCF Connected Services Tool where switching between different service URL addresses would consistently cache the initial input, resulting in inaccurate display within the Services tree view.

dotnet-svcutil: update metadataSourceFiles for URL input to correctly compute hash for caching ServiceDescriptor

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs

For issue #5553. 
Class `FaultException<TDetail>` now expose the same api surface as .NET Framework.

Add missing constructors for FaultException<TDetail> and add unit test.

---

eng/SendToHelix.proj
src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs

Recent checks on Linux fails due to Centos.7 was set for removal. 
Addressing this by referring to PR #5369.

[release/6.1] Update Linux image pool.

---

eng/SendToHelix.proj
src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs

Recent checks on Linux fails due to Centos.7 was set for removal. 
Addressing this by referring to PR #5369.

[release/4.10] Update Linux image pool.

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.4.0.0.cs
src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/IdlingCommunicationPool.cs
src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/SingletonConnectionReader.cs
src/System.ServiceModel.Primitives/src/Internals/System/Runtime/InputQueue.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/ServiceChannel.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Dispatcher/DuplexChannelBinder.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Dispatcher/TerminatingOperationBehavior.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Security/TimeBoundedCache.cs

Reference bug: https://github.com/CoreWCF/CoreWCF/issues/1391

Fix Streamed Timeout TimeSpan.MaxValue Exception 

---

src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/UDSBindingTests.cs
src/System.ServiceModel.UnixDomainSocket/src/System/ServiceModel/Channels/UnixDomainSocketChannelFactory.cs

Addresses issue #5621.
Note: 
The fix and the associated test case have been verified locally. It requires the Windows_Authentication_Available condition to be set.

Fix UnixDomainSocketBinding default security issue on Windows.

---

src/dotnet-svcutil/lib/Microsoft.Svcutil.NamedPipeMetadataImporter/NamedPipeMetadataImporter.cs
src/dotnet-svcutil/lib/src/Metadata/ServiceDescriptor.cs

**Description:**
WCF CS tool invokes dotnet-svcutil-lib, which uses reflection to download metadata from a net.pipe URL. If an exception occurs during this reflection process and it isn't properly caught, Visual Studio may crash.
The fix is wrapping the reflection code's return type and any potential exceptions with `TaskCompletionSource<TheType> `instance. This approach ensures that exceptions are available to WCF CS tool, preventing VS crash and providing a more user-friendly exception message.

Fix for WCFCSTools issue - invalid namedPipe URL throws uncatchable exception in VS.

---

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs

Addresses https://github.com/dotnet/wcf/issues/5202#issuecomment-2048100444:
class `HttpRequestMessageProperty `implements `IMessageProperty `and `IMergeEnabledMessageProperty`, `IMergeEnabledMessageProperty `does not exist in `System.ServiceModel.Primitives.ref.csproj`.

Add IMergeEnabledMessageProperty to S.S.Primitives

---

azure-pipelines-arcade-PR.yml

Converted the _RunWithCoreWcfService from a variable into a parameter. The variable defined on the pipeline definiton was being overwritten by the yml file so wasn't actually applying. If you look at existing CoreWCF runs in the run tests step, you'll see that _RunWithCoreWcfService is being set to false instead of the expecgted true.  
The pipeline definition will need to be edited to remove the variable, instead it becomes a check box like shown here:
This can't be done until after this change is merged. I manually kicked off a dotnet-wcf-with-corewcf--ci pipeline run with this new parameter checked which validates this PR. It's the only way to apply the parameter before this is merged as the existing pipeline definition can't see the parameter as it's not merged, so can't be edited to …

Fix suppressing running the UpdatePRService steps

---

azure-pipelines-arcade-PR.yml

Due to Azure DevOps not trusting my GitHub account to make changes to the yml for the corewcf ci run, the PR triggered build will fail due to not being able to use the access token. I've kicked off a manual build for the same commit which can use the access token (because Azure DevOps trusts my Azure authenticated account). You can verify this is doing the right thing by seeing that the step "Update 
_updateService variable" is skipped. This is the step which populates the service url and sets a variable telling a later step to update the test servers to be in line with the PR. We still have tests failing due to still ramping up CoreWCF for tests, so looking at this step is the easiest way to check if the _RunWithCoreWcfService variable is working as expected. …

Make _RunWithCoreWcfService a variable again

---

src/System.ServiceModel.Http/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs

Simplest possible fix for null inputStream when ContentLength is 0.
Addresses #2999

Handle current null-ref situation that can occur when Content-Type is present but Content-Length is 0.

---

src/System.ServiceModel.NetTcp/src/System/ServiceModel/Channels/SocketConnection.cs
src/System.ServiceModel.Primitives/src/Internals/System/Runtime/AsyncResult.cs

Preserves the original stacktrace when AsyncResult is throwing stored exception
Fix order of null checks so that SocketConnection actually throws stored exception when failing to connect
Fixes #5697

Fix some exception handling

---

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs
src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs
src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/CallbackErrorHandlerTests.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/CompositeType.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfDuplexService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfDuplexService.cs
src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/DuplexTestServiceHosts.cs
src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Netcoreapp.cs

Expose IErrorHandler and add test case.

---

eng/Versions.props

NuGet.ProjectModel 6.11.1 has a transitive dependency on System.Formats.Asn1 6.0.0, which contains a critical security vulnerability.
CC: @HongGit , @mconnew

Upgrade the version of the dotnet-svcutil-lib dependencies.

---

src/System.ServiceModel.Http/src/System/ServiceModel/Channels/HttpChannelFactory.cs
src/System.ServiceModel.Primitives/src/Internals/System/Runtime/TimeoutHelper.cs
src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/ProducerConsumerStream.cs

We coalesce cancellation tokens to reduce timer registration and cancellation. We were capturing the execution context which was capturing the OperationContext which is stored in an AsyncLocal. By calling CancellationToken.UnsafeRegister, it prevents the execution context from being captured. This was showing up as a pseudo memory leak (not actually leaking memory, but holding on to it for an extended period).

Fix CancellationToken registration capturing the OperationContext

---

eng/Versions.props
src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/Binding.UDS.IntegrationTests.csproj

The latest pending arcade package version changes can't be applied due to explicit referencing some packages which are built into the runtime now, causing error NU1510.

Fix unnecessary package references which is breaking latest build

---

src/dotnet-svcutil/lib/src/SR.resx
src/dotnet-svcutil/lib/src/xlf/SR.cs.xlf
src/dotnet-svcutil/lib/src/xlf/SR.de.xlf
src/dotnet-svcutil/lib/src/xlf/SR.es.xlf
src/dotnet-svcutil/lib/src/xlf/SR.fr.xlf
src/dotnet-svcutil/lib/src/xlf/SR.it.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ja.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ko.xlf
src/dotnet-svcutil/lib/src/xlf/SR.pl.xlf
src/dotnet-svcutil/lib/src/xlf/SR.pt-BR.xlf
src/dotnet-svcutil/lib/src/xlf/SR.ru.xlf
src/dotnet-svcutil/lib/src/xlf/SR.tr.xlf
src/dotnet-svcutil/lib/src/xlf/SR.zh-Hans.xlf
src/dotnet-svcutil/lib/src/xlf/SR.zh-Hant.xlf

Fixes spelling in the `dotnet-svcutil --help` output

Fix spelling of "references"

---

src/dotnet-svcutil/lib/src/FrameworkFork/Microsoft.Xml/Xml/schema/XmlSchemaException.cs

Fixed "Value cannot be null. (Parameter 'args')"

---

src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfCurrentCultureAttribute.cs
src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs

Before this commit, two tests would fail with this error (FaultExceptionTest.Serializable_TDetail and FaultExceptionTest.Serializable_Default):
```
Xunit.Sdk.EqualException
Assert.Equal() Failure
↓ (pos 1259)
Expected: ···:text><a:xmlLang>en-US</a:xmlLang></a:FaultException.FaultRea···
Actual:   ···:text><a:xmlLang>fr-CH</a:xmlLang></a:FaultException.FaultRea···
↑ (pos 1259)
```
Explicitly setting the expected culture with a `BeforeAfterTestAttribute` solves this issue.

Fix some tests that would fail when running under a non en-US culture

---

src/dotnet-svcutil/lib/tests/Baselines/FederationServiceTest/Saml2IssuedToken_mex/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicHttpsTransSecMessCredsUserName/BasicHttpsTransSecMessCredsUserName/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttp/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttps/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttp/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttpWebSockets/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttps/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttpsWebSockets/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNettcpTransSecMessCredsUserName/TcpTransSecMessCredsUserName/Reference.cs
src/dotnet-svcutil/lib/tests/Baselines/WsHttpBindingAndws2007HttpBindingTransSecMessCredsUserName/HttpsTransSecMessCredsUserName/Reference.cs

A follow-up fix for PR #5788:
The WCF operation name EchoMessageResquestWithMessageHeader, which contains the typo "Resquest," is truncated in the generated client code, causing some places to be missed when attempting to fix it by finding and replacing the entire word.
Additionally, the reordering of two generated FaultContractAttribute attributes is included. Since the baseline file is tool-generated, the order of the attributes may vary if the service changes. However, for a fixed service, the order appears to be consistent, so this change has been applied here.

[dotnet-svcutil] Add missing test baseline fix for a previous service typo fix

---

eng/SendToHelix.proj

Instead of hardcoding this in the Helix image, see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1391

Set OPENSSL_ENABLE_SHA1_SIGNATURES=1 in SendToHelix.proj
