src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
Added AssemblyVersion 4.0.0.0 to be consistent with CoreFx.
Removed CodeAnalysisRuleSet to eliminate a warning building mirrored sources in TFS.
Removed unnecessary source control properties.
=> Cleanup System.Private.ServiceModel.csproj

README.md
Update the link of reference source to pointing to github repo
=> Fix reference source link

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs
*Replaced the skip attribute with the ActiveIssue attribute.
Fixes #57
=> Updated tests that were using the skip attribute.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/App.config, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/IWcfCustomUserNameService.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/Program.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfService.csproj, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfUserNameService.cs, src/System.ServiceModel.Tests.Common/src/Endpoints.cs, src/System.ServiceModel.Tests.Common/src/ServiceInterfaces.cs
* Eliminate the dependency on a domain user by using a custom user name/pwd validator
Fixes #69
=> Enable Basic Authentication test in OSS

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/App.config, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/IWcfDuplexService.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfDuplexService.cs
* Adding a typed proxy variation using DuplexChannelFactory
* Fixes #118
=> Adding additional duplex scenario test.

src/System.Private.ServiceModel/tests/Unit/System.Private.ServiceModel.Tests.csproj
=> Removing the condition: Exclude="Scenarios*\

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs
* This test was first added with PR #119.
* On the following day PR #121 deleted the test.
* This was not intentional, looks like the branch the PR came from was not synced with my PR from the day before.
* Adding it back.
=> Adding back test accidentally removed.

src/System.Private.ServiceModel/tests/Common/src/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Common/src/TestTypes.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyDuplexTests.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/IWcfDuplexService.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfDuplexService.cs
* Test currently fails, opened Issue 194 and added the ActiveIssue attribute to the test.
Fixes #169
=> Adding FaultContract negative test for Duplex scenario.

src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/TestResources/EndpointResource.cs
@roncain  @hongdai  does this allow you to override the host part? for #205
=> Test fix to expose all parts of the host listener uri for #205

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/TestResources/HttpWindowsResource.cs, src/System.Private.ServiceModel/tests/Scenarios/SelfHostWcfService/WcfService.csproj, src/System.Private.ServiceModel/tests/Scenarios/ServiceModel.Scenarios.Common/Endpoints.cs
* Make self-hosted test service works for Kerberos
* Integrate with Bridge
* Make the existing test work on single machine
Fix #193
=> Make self-hosted test service works for Kerbero

dir.props, src/.nuget/packages.Windows_NT.config
Follows change from dotnet/corefx.
=> Update build tools to 1.0.25-prerelease-00063

Documentation/manualtest-guide.md
=> Document how to run Kerberos test

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IService1.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.xproj, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.lock.json
Updated with the initial PR feedback and re-formatted.
Cherrypicked @KKhurin 's commit. 
@roncain  please merge since I might be on the bus :)
=> This is the initial commit for the stress tests.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
* Add a test to cover incorrect password.
* Add a test to cover empty user name
Fix #88
=> Add Test Coverage

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
* Helpful to pinpoint issue #237
=> Add HResult trace to help identify intermittent test failure

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
Issue #166 looks like it's a race condition which I can't duplicate on my local machine. There are inner exceptions with call stacks that are needed in order to debug this problem. This adds additional information to the exception message so that when this test fails on our CI machine, I will have the required call stacks to understand what's causing this.
=> Add additional logging to help diagnose Issue #166

src/System.Private.ServiceModel/src/Resources/Strings.resx
* Removed resource strings related to configuration files.
* Removed resource strings related to reliable messaging and reliable sessions.
=> Cleaning up ServiceModel string resources.

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
Added tests covering TransferMode.Streamed using SynchronizationContext. 
Fixes #223.
=> Tests for Streamed Mode in SynchronizationContext

src/System.Private.ServiceModel/src/System/ServiceModel/ClientBase.cs
* In cleaning up ClientBase<TChannel> I removed two properties that were in the public contract. Adding them back.
=> Fixing build break caused by PR #252

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
* The related product bug are fixed
* I have verified both of the tests are passing now.
=> Enable NTLM test and Basic Auentication negative test

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.lock.json, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/ComplexCompositeType.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CompositeType.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfDuplexService.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/DuplexResources.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfDuplexService.cs
=> Adding test cases to resolve Issues 250 and 251

src/System.ServiceModel.Security/tests/ServiceModel/DnsEndpointEntityTest.cs
* Enable Ctor for DnsEndpointIdentity
* Add unit tests.
* I have verified the unit tests on ProjectN as well.
Fix issue #234
=> Enable Ctor for DnsEndpointIdentity

src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs
See Issue 301 for my analysis of every test that was disabled and my proposed action for each.
The three tests in this PR are the only ones I suggest re-enabling at this point.
Fixes #301
=> Fix and re-enable disabled tests due to Issue #301

src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs
This fixed the issue in my testing and doesn't require changes to EventSource or renumbering the event ids.
=> Fix to the WCF event source that will alleviate the problems with ToF CHK tests

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IService1.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/HelloWorldTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/ITestTemplate.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.lock.json
- added more stress scenarios
- added support for duplex
- added support for streaming
=> Updating stress tests

src/System.Private.ServiceModel/src/System/ServiceModel/Description/ServiceReflector.cs, src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs
=> Fix for Issue #315

src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/DispatchOperation.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.cs
=> Fix XmlSerializer to work on NetTcp/Duplex MEP

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClient.cs, src/System.Private.ServiceModel/tools/test/Bridge/Bridge/JsonSerializer.cs, src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceController.cs, src/System.Private.ServiceModel/tools/test/Bridge/Bridge/ResourceInvoker.cs
Part of a change which will enable listing all available resource of the bridge. 
```
$ curl -X  PUT http://localhost:44283/resource/WcfService.TestResources.BasicHttpResource -d .
{
uri : "http://localhost:8081/BridgeAppDomain0/Basic"
}
```
=> Allow addressable resource URIs

README.md
=> Update badges to use the new jobs

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs
BridgeClientCertificateManager took a dependency on S.Net.NameResolution, but
.NET Native doesn't support the contract
We can get away with a non-machine named cert on the client side for now
Fixes #397
=> Remove dependency on S.Net.NameResolution for UWP in BridgeClient

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs
Whenever a CancelationToken is created with timeout, a timer object is created. Disposing a massive amount of timer object would cause thread contention. This change borrow the concept from @stephentoub's idea of coalescing timeout tokens (http://blogs.msdn.com/b/pfxteam/archive/2011/12/03/10244004.aspx) and ends up resolves huge amount of thread contention.
I have observed throughput improvement of 80% in my experiment.
=> Used CoalescedTimeoutTokens to cut down thread contention

run-test.sh
Prior to this change, run-test.sh overwrote all the binaries
from the CoreFx packages with those built in the CoreFx repo.
After this change, it relies mostly on the binaries from the
packages except for select list of binaries that are not correct
in their package.
=> Update run-test.sh to overwrite minimal CoreFx binaries

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs
I need to make the change to only use what it supports.
=> Fix test failure on TOF

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestHelpers.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/MyX509CertificateValidator.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpTransportSecuritySslCustomCertValidationResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
* Fixes #367
* Added a Constants file to WcfTestBridgeCommon as little by little I see more and more variables being used that could be put here.
=> Adding test case for X509CertificateValidator scenario

src/System.Private.ServiceModel/src/Internals/System/Runtime/TimeoutHelper.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrClientWebSocketFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTSocketConnection.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TimeoutStream.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportDuplexSessionChannel.cs
Fixed a build issue from https://github.com/dotnet/wcf/pull/427
=> resubmit: Allow caller to await on TimeoutHelper.CancelationToken

Documentation/RC1SupportedScenarios.md
First pass at specifying the features available in RC1.
Fixes #493
=> Fill in table of supported RC1 features

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs, src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateGenerator.cs, src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateResourceHelpers.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateRevocationListResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpRevokedServerCertResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
* Add a test to check client call will fail if service cert is revocated.
Fixes #369
=> Implement NetTcpBinding Security.Transport Certification authority revokes a certificate

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestHelpers.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/WebSocketResources.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WSRequestReplyService.cs
* Fixes Issue #532
* Includes some minor formatting changes and one bug in other WebSocket tests in the same file.
=> Adding additional Web Socket tests.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportDefaults.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WebSocketTransportSettings.cs, src/System.ServiceModel.Http/tests/Channels/WebSocketTransportSettingsTest.cs
=> Make WebSocketSettings.DisablePayloadMasking throw PNSE.

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
* Using Asserts instead of StringBuilder for validation.
* Adding comments to compartmentalize the test into separate sections.
=> Updating existing tests with updated syntax and validation checking.

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
* Removing the active issue, need to keep our eye on it to make sure it is no longer flaky.
* Fixes #273
=> Underlying issue fixed in PR #3000 in dotnet/corefx.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs, src/System.ServiceModel.Http/tests/ServiceModel/SecurityBindingElementTest.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexChannelFactoryTest.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/DuplexClientBaseTest.cs
Enables CreateChannel_Using_NetTcpBinding_Defaults() test after #300 got merged
Fixes #301
=> Enable CreateChannel_Using_NetTcpBinding_Defaults test

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/BinaryMessageEncoder.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelHelpers.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageEncoder.cs
Also improved async-ness of streamed response.
Fixes #589
=> Receiving chunked response when buffered is now async.

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceKnownTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CompositeType.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs
Added a scenario test for XmlSerializerFormat & MessageContract.
Added scenario tests for ServiceKnownTypeAttribute.
Fix #557.
Fix #569.
=> Added scenario tests for MessageContractAttribute and  ServiceKnownTypeAttribute.

src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs
* Updated existing test to get this coverage.
* Fixes #127
=> Adding test coverage for XmlDictionaryReaderQuotas.CopyTo method

src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MessageHeaderAttribute.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
=> Add MessageHeaderAttribute into the Contract.

src/System.Private.ServiceModel/src/System/IdentityModel/Claims/X509CertificateClaimSet.cs
Exceptions happening on static ctors will be silently swallowed. This makes bugs really hard to find. Change X509CertificateClaimSet to throw when one of the properties is accessed and initialization was not successful. 
//cc @mconnew
=> Change X509CertificateClaimSet to throw if static ctor thows

src/System.Private.ServiceModel/src/ExceptionHelper.cs, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/Claim.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/ClaimComparer.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/ClaimSet.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/WindowsClaimSet.CoreCLR.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/WindowsClaimSet.NetNative.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Claims/X509CertificateClaimSet.cs, src/System.Private.ServiceModel/src/System/IdentityModel/SecurityUtils.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Selectors/WindowsSecurityTokenAuthenticator.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/WindowsSecurityToken.CoreCLR.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/WindowsSecurityToken.NetNative.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/WindowsStreamSecurityUpgradeProvider.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/Tokens/WindowsSidIdentity.cs, src/System.Private.ServiceModel/src/System/ServiceModel/UpnEndpointIdentity.cs, src/System.Private.ServiceModel/src/project.json, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
=> Exclude System.Security.Principal.Windows for *NIX builds

src/System.Private.ServiceModel/src/System/ServiceModel/Description/DataContractSerializerOperationBehavior.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractCommon.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/IWcfService.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/ReplyBankingDataNotWrapped.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.cs
=> Add Tests for MessageHeaderAttribute.

src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateGenerator.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateAuthorityResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/CertificateResources/CertificateResource.cs
See individual commits for change description
=> Modify CertificateGenerator to fix Linux testing issues

release-notes/SupportedFeatures-v1.0.0-rc2.md
* This is just to clone RC1 release note. Once RC2 test completes, it will
be updated. All related release notes will be updated once we complete RC2 testing.
=> Create supported-feature matrix

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/Message.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageHeader.cs
=> Call Dispose() on the XmlWriter after use.

build.proj, dir.props, dir.traversal.targets, run-test.sh, src/System.Private.ServiceModel/src/System.Private.ServiceModel.builds, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.builds, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.builds, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.builds, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.builds, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Primitives/tests/project.json, src/System.ServiceModel.Security/src/System.ServiceModel.Security.builds, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj
* Once this looks good we can do the same work for the rest of the WCF projects.
* Fixes #637
=> Adding .builds file and applying new conventions to S.P.SM.csproj

release-notes/SupportedFeatures-v1.0.0-rc2.md
*Per Zhenglan's feedback, explicitly call out this is a work in progress.
=> Add In Progress

src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.cs
=> Use Assert instead of errorBuilder in MessageContractTests.cs

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTSocketConnection.cs
Here is this sequence of events when the data is supposed to be sent immediately.  
* _socket.WriteAsync is called and returns a task (t1)
* t1.ContinueWith is called on this task where the delegate calls FlushAsync. ContinueWith returns a task t2.
* If t2 is Completed immediately, return AsyncCompletionResult.Completed
The problem is the FlushWriteImmediate method was an async void method so we weren't waiting on the flush completing and t1.ContinueWith would complete immediately which caused us to report the Write had completed. Another Write would then be called which would cause the new data to be appended to the write buffer which hadn't been cleared yet from the previous Flush. FlushAsync would then be called again and the entire buffer including the data from the first Write call …
=> Fix bug where async write was reporting completion before the Flush completed

src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/TypedProxyTests.cs
=> Remove ActiveIssue for ServiceContract_TypedProxy_DuplexCallback

Documentation/HowToUseETW.md
* This is to document how customers should collect and analyze ETW traces
Fixes #562
=> Document how to collect and analyze ETW traces

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportDuplexSessionChannel.cs
=> Fix WebSockets duplex streaming when it completes async

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj
=> Updating package version of S.Private.ServiceModel

netci.groovy
This change allows us to use build.sh on Linux rather than using build.cmd on
a Windows machine and then using a build flow to propagate the binaries to a
Linux box for testing
It allows us to run CI against published packages rather than built packages
from the latest CI run from corefx
=> Change CI to use build.sh on Linux

README.md
* Now that our Linux builds are working consistently, let's show it off. 
* Change the package links to reference the enterprise myget feed at dotnet.myget.org
skip ci please
=> Update README.md to reflect new builds / packages

dir.props, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.builds, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Duplex/src/netcore50/project.json, src/System.ServiceModel.Duplex/src/project.json, src/System.ServiceModel.Http/src/System.ServiceModel.Http.builds, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.Http/src/netcore50/project.json, src/System.ServiceModel.Http/src/project.json, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.builds, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.NetTcp/src/netcore50/project.json, src/System.ServiceModel.NetTcp/src/project.json, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.builds, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Primitives/src/netcore50/project.json, src/System.ServiceModel.Primitives/src/project.json, src/System.ServiceModel.Security/src/System.ServiceModel.Security.builds, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj, src/System.ServiceModel.Security/src/netcore50/project.json, src/System.ServiceModel.Security/src/project.json
Includes a fix to a path issue related to newlines in dir.props.
=> Update json files for xplat nuget

src/System.ServiceModel.Primitives/tests/ServiceModel/ChannelFactoryTest.cs
=> Added a Unit Test Covering ChannelFactory.BeginOpen

netci.groovy
* Note that this isn't tested as I haven't found a way to test without checkin.
* I aslo add an optional PR trigger.
=> Add a job for nightly runs against the latest dependencies

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/CallStats.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/IService1.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/PoolOfThings.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/SharedPoolsOfWCFObjects.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/TestHelpers.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/CommonTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexStreamingTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/DuplexTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/HelloWorldTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/ITestTemplate.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/DuplexService.svc.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/DuplexStreamingService.svc.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/IDuplexService.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/IDuplexStreamingService.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/IService1.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/IStreamingService.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/Service1.svc.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/App_Code/StreamingService.svc.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/DuplexService.svc, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/DuplexStreamingService.svc, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/Properties/AssemblyInfo.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/Service1.svc, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/StreamingService.svc, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjectsServer/Web.config
Parity between sync and async coverage
Merged with Hong's duplex changes for NetHttp binding
Added Duplex NetHttp streaming scenario
Added the server source code (will provide the instructions on how to setup the IIS server)
=> Refactored stress tests and adopted them to run perf

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ConnectionOrientedTransportChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SingletonConnectionReader.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/StreamedFramingRequestChannel.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpStreamedNoSecurityResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
These changes enable streamed transfer mode in NetTcp to fix a release-blocking issue.
Fixes #713
=> Enable nettcp stream

src/System.Private.ServiceModel/tools/test/Bridge/WcfTestBridgeCommon/CertificateManager.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/EndpointResource.cs
=> Revert "Fix FQDNs if the server hosted on a Cloud machine"

build.cmd
* Pull request 860 remove %* accidently. Adding it back to fix
the issue that outerloop does not get run
=> Fix build script to pass command line parameters

build.sh, init-tools.sh, run-test.sh
* Wrapping all sections where we differ with the corefx version with a WCF start/end comment so it is easier to see expected differences.
* Will open either Issue or PR in corefx to make some content be more generic and not specifically say "corefx" unless necessary.
* Will open another PR in corefx to update their myget feed links to use the enterprise feed.
=> Updating WCF version of .sh files

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/TcpTransportSecurityStreamedResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
=> Add tests for NetTcp TransferMode.Streamed and SecurityMode.Transport

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.Private.ServiceModel/src/System/ServiceModel/Security/IdentityVerifier.cs, src/System.Private.ServiceModel/src/System/ServiceModel/SpnEndpointIdentity.cs, src/System.Private.ServiceModel/src/System/ServiceModel/UpnEndpointIdentity.cs, src/System.Private.ServiceModel/src/project.json, src/System.ServiceModel.Security/tests/ServiceModel/DnsEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs
Using this to test build only, please do not merge. 
Testing out #592
=> Turn on build include NegoStream

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.Private.ServiceModel/src/System/ServiceModel/SpnEndpointIdentity.cs, src/System.Private.ServiceModel/src/System/ServiceModel/UpnEndpointIdentity.cs, src/System.Private.ServiceModel/src/project.json, src/System.ServiceModel.Security/tests/ServiceModel/DnsEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs
Reopening this since #852 caused a build break in .NET Native
=> Implement supported parts of Spn/UpnEndpointIdentity

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json
* We want to use as many stable versions of packages as possible in our default building environment.
=> Updating some packages to use stable versions.

clean.cmd
* The script was updated to check for and kill the long running VBCSCompiler.exe task before continuing cleaning tasks.
=> Syncing to the latest version of the Clean script.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
Stress tests revealed a race condition during an async close
of RequestChannel.  A TCS used to signal completion of the close
could become null if the final pending request completed
asynchronously during the close.
Fixes #885
=> Fix async close race condition in RequestChannel

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
PR #920 fixed issue #885 in master.  This PR cherry-picks
that fix into the RC2 branch.
Original description was:
Stress tests revealed a race condition during an async close
of RequestChannel. A TCS used to signal completion of the close
could become null if the final pending request completed
asynchronously during the close.
=> Port to RC2 the fix to the async close issue #885

src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/CoreClrSocketConnection.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RTSocketConnection.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs
Performance improvements resulting from investigation of issue #764
=> Performance improvements related to ETW events

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
The regression test added to verify the fix for #931 failed on
NET Native due to the way it was written.  By aborting the channel
before timing out, the underlying NET Native HttpClient code
terminated the connection rather than cancelling the cancellation
token, so a TimeoutException was not thrown.  By reversing the
order in the test to timeout, then abort, the cancellation token
was properly cancelled, and a TimeoutException was thrown.
The test was manually verified in the debugger to determine it
still executed the code path fixed by #931.
A 2nd test as added to test only the timeout scenario without
an explicit abort.
Fixes #939
=> Fix async stream timeout and abort test for NET Native

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
* Two tests using active issue #544 have been updated to different and more accurate issues.
* Fixes #544
=> Updating active issue numbers on two tests.

Documentation/manualtest-guide.md
=> Update manual test guide for Linux HTTPS/Kerberos tests

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs
* Also updating it to use more recent test syntax and to use Assert.Throw to verify expected exceptions.
* Fixes #835
=> Updating test to be a little clearer about what it is doing.

src/System.Private.ServiceModel/tools/PRService/pr.ashx
This replaces the earlier SHA functionality. We'll need this to be able to check out feature or "master" branches for testing, for example. 
Note that we currently by design limit ourselves to allowing only "master" branch checkout. 
skip ci please
=> Add ability to use PRService on branches

netci.groovy
Identified some issues with os / osGroup mappings in the previous change to netci.groovy; fixing here
=> Modify netci.groovy ${osGroup} vs ${os} mapping

netci.groovy
Disable the outerloop builds that require an external server because the server
has not yet been fully provisioned
=> Disable non Windows_NT outerloops in netci.groovy

netci.groovy
... but for now, keep the command around as a comment in case we need it for
the near future. We can remove the comment later should we find that we haven't
needed it for a long time
=> Remove latest dependences build from netci.groovy

src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TcpDefaultResourceTestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/App.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Properties/AssemblyInfo.cs, src/System.Private.ServiceModel/tools/SelfHostedWcfService/SelfHostedWCFService.csproj, src/System.Private.ServiceModel/tools/SelfHostedWcfService/SelfHostedWCFService.sln, src/System.Private.ServiceModel/tools/SelfHostedWcfService/dir.props, src/System.Private.ServiceModel/tools/SelfHostedWcfService/dir.targets, src/System.Private.ServiceModel/tools/SelfHostedWcfService/packages.config, src/System.Private.ServiceModel/tools/setupfiles/BuildWCFSelfHostedService.cmd
* Also add missing TcpDefault service activation. It has caused several security
tests failures.
=> Init check in self host service

src/Common/src/System/SR.cs, src/System.Private.ServiceModel/System.Private.ServiceModel.sln, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/BinaryMessageEncoder.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpResponseMessageHelper.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageEncoder.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ReadAheadWrappingStream.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TextMessageEncoder.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/StreamFormatter.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/CustomTextMessageBindingElement.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/CustomTextMessageEncoder.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/CustomTextMessageEncoderFactory.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/TextTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/App.config, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/CustomBindings/CustomTextMessageBindingElement.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/CustomBindings/CustomTextMessageEncoder.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/CustomBindings/CustomTextMessageEncoderFactory.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/CustomTextEncoderBufferedResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/TestResources/CustomTextEncoderStreamedResource.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.cs, src/System.Private.ServiceModel/tools/test/SelfHostWcfService/WcfService.csproj
I also passed through a cancellation token from higher layers to improve timing out scenarios with chunked encoding.
=> Implementing async readahead with sync read on StreamFormatter

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs
* The previous method does not work for Self host cross machine.
=> Change the way we identify if it's IISHosted

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/TestProperties.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs
This PR creates some new conditional evaluators that can be used by [ConditionalFact] and applies them to the tests that currently need them.
=> Apply [ConditionalFact] to some tests

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/BridgeClientCertificateManager.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Common/Unit/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/TextTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs
Merges the infrastructure branch back to master.
The first commit of this PR is a feature branch off the Infrastructure branch that has been rebased onto the current master.  It contains no other changes other than a couple manual merges that could not be merged automatically, notably Endpoints.cs.
=> Merge infrastructure branch to master

build.cmd, build.sh, dir.props, dir.targets
* Porting corefx PR #7724
* Removing some WCF specific code that is no longer needed.
=> Updating shared scripts.

build.cmd
* With recent infrastructure changes we no longer need the bridge to be started by the build script.
* At the same time PR dotnet/corefx#7894 adds setup and cleanup extension points to the build script.
* As soon as this is merged in corefx I will port it to wcf.
=> Removing Bridge related code from build script.

netci.groovy
This will remove us from the shackles of having only one machine to test our Windows outerloops on :smile:
=> Change windows-elevated runs to use autoscaling pool

init-tools.cmd
cc: @StephenBonikowsky
related: dotnet/corefx#8002
=> Fix issues in init-tools when path to git repo contains spaces

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelFactory.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs
The asynchronous channelfactory close path executed
synchronous close logic, leading to a sync/async
"sandwich" and eventual thread starvation.
These changes adds helper methods and makes the async
close stay asynchronous.
It also adds functional tests for async opens and closes
of both channelfactories and proxies because those code
paths were not being covered yet.
Fixes #1022
=> Make async channelfactory close stay asynchronous

src/System.Private.ServiceModel/tools/scripts/WcfTestServerSetup.cmd
- Changed to setup PRService only if the id is "Master"
- Changed to grant app pool access to folders by inheritance instead of explicit-set
- Other cosmetic fixes
=> Update server setup script to use one central PRService only

netci.groovy
PR #1083 adds support for testing outerloops against SelfHostedWcfService, so we need a similar mechanism to do so in CI as well
=> Modify netci.groovy to support selfhosted outerloop

build.sh, publish-packages.sh
* Just bringing them up-to-date.
=> Syncing .sh scripts with corefx

build.proj, dir.props, dir.targets, run-test.cmd
* Corefx PR dotnet/corefx#8129
* Corefx PR dotnet/corefx#8088
* Other small changes.
=> Continuing updates to shared scripts between wcf and corefx.

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs
* Scenario/Binding/Custom tests.
* Scenario/Binding/Http tests.
* Scenario/Client/ChannelLayer tests.
* Scenario/Client/ClientBase tests.
=> Updating scenario tests with standard programming model.

dir.props, sync.cmd
=> Update shared corefx shared scripts may9

build.override.targets, build.proj, src/System.Private.ServiceModel/tools/scripts/StartWCFSelfHostedSvcDoWork.cmd, src/System.Private.ServiceModel/tools/scripts/StopWcfSelfHostedSvc.cmd
Enables the clean target to close the SelfHost WCF service if it is running.
=> Clean target

src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalTestDetectors.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ConditionalWcfTest.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/ServiceUtilHelper.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/src/testproperties.targets, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs
As per discussions in #958, this adds some new ConditionalFact
conditions and renames some others.  The implementations of the
detectors are mostly simple heuristics for now.  Actual detector
implementations will follow in other PR's.
=> Adds/renames some ConditionalFact conditions

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.cs
Enhanced Scenarios\Client\ChannelLayer by adding async versions of each of its tests.
Fix #1082.
=> Add async scenario tests to Client.ChannelLayer

src/System.Private.ServiceModel/System.Private.ServiceModel.sln
* Solution folders were missing and/or did not contain all the files.
=> Updating folders and content for Scenario TransportSecurity tests.

src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.4.0.0.cs
PR #1044 removed new tests added by 3fe60c1. This PR is to add the tests back. I verified these tests worked with 4.0.0 packages, so I am adding them to the 4.0.0 file.
/cc: @roncain
=> Added back tests removed by PR #1044.

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Add rc2 to version history for all contract packages

release-notes/SupportedFeatures-v1.0.0-rc2.md
I'd like to keep this as an open PR until the doc is completely finished with all the final details for rc-2.
Please provide feedback and I'll update regularly.
=> Update rc2 release notes

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/NetHttpsTestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
* Adding tests for NetHttpsBinding.
* Fixes #507
=> Add NetHttpsBinding test coverage.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs
As HttpClient has a timeout set, it creates a linked cancellation token and calls CancelAfter on that linked token. By setting the default timeout to Infinite, HttpClient skips the call to CancelAfter. We were getting about 5% CPU usage updating the global TimerQueue because of this.
Also fixed an issue where we weren't unregistering a callback on our cancelation token which would have caused an unnecessary no-op callback.
=> Prevent HttpClient from setting a timer on internal cancellation token

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/RequestChannel.cs
=> Ensure _closedTcs is set and fix issue where first request to complete is closing the channel

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageFault.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/FaultFormatter.cs
* Add comments to explain why the classes are made public, but not on contract
=> Add comments for recently made public classes do not match contract

Documentation/developer-guide.md
Finish a sentence I forgot to finish in my last PR for a feedback.
skip ci please
=> Update dev guide doc

netci.groovy
@iamjasonp please suggest if we need to add anything else to support RTM branch in CI. I guess we need to merge to be able to test this?
=> Add the support of RTM branch to the CI

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.NetNative.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceModelHttpMessageHandler.cs
=> Wait until message has been sent before completing HttpClient.SendAsync

src/System.Private.ServiceModel/tools/scripts/StartWCFSelfHostedSvcDoWork.cmd
Adds an environment variable that can be set to alter whether the
self-hosted WCF services starts under the user account (default)
or runs as Local System.
=> Enable self-host startup script to run as Local System conditionally

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd
=> Unlock the IIS config section to allow sslFlags to be overriden

src/Common/test-runtime/project.json, src/System.Private.ServiceModel/tests/Common/Infrastructure/tests/project.json, src/System.Private.ServiceModel/tests/Common/Scenarios/project.json, src/System.Private.ServiceModel/tests/Common/Unit/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json, src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json, src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json, src/System.ServiceModel.Duplex/tests/project.json, src/System.ServiceModel.Http/tests/project.json, src/System.ServiceModel.NetTcp/tests/project.json, src/System.ServiceModel.Primitives/tests/project.json, src/System.ServiceModel.Security/tests/project.json
* Adding support for fedora, opensuse and ubuntu.16
=> Update project.json files to support additional runtimes.

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.cs
* Added a new constant variable only in ToF to if/def against in order to get around ConditionalFact not being supported as well as conditional ActiveIssue attribute.
* Fixes #1221
=> Fixing issues related to full xunit not being supported in ToF.

UpdatePublishedVersions.ps1
* File is UpdatePublishedVersions.ps1 and it should have no diffs to the version in corefx.
=> Adding PS script needed to publish packages via VSO pipeline.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs
* The issue is already fixed on the test server side, this is to enable
the test.
=> Enable test as issue 1248 is fixed

src/System.Private.ServiceModel/tools/setupfiles/BridgeCertificateInstaller.sh
Adds support to BridgeCertificateInstaller.sh to install root certificates on non-Ubuntu OSes
=> Automate certificate install for OSX, other *nixes

README.md
=> Add code of conduct to README.md

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/DigestServiceAuthorizationManager.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/AuthenticationResourceHelper.cs
=> Re-enable digest no-domain tests

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Update documentation of WCF package versions for .NET core 1.0

netci.groovy
* Change netci.groovy to auto-trigger all builds except code coverage on all builds rather than excluding outerloops as we currently do
* ~~Change netci.groovy to put PR queues into folders rather than one monolithic folder in dotnet-ci Jenkins dashboard~~
* Sync netci.groovy OS definitions to what we see in the dotnet/corefx repo
=> Auto-trigger outerloop CI builds upon PR

netci.groovy
To be paired with dotnet/dotnet-ci#342
=> Branchify repo CI queues

release-notes/SupportedFeatures-v1.0.0.md
* Update known issue link to the WCF release note.
* Simplify SPN and UPN columns. The detail has been added to the acutal issue.
=> Update feature table

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/DigestServiceAuthorizationManager.cs
=> Modify digest authenticator to accept realm\\username username

netci.groovy
This is to maintain CI test capability of the RTM branch after making branchify changes to the master branch. See 58a3bb5
/cc: @mmitche
=> Copy branchified netci.groovy from master branch

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MessageContent.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ProducerConsumerStream.cs
=> Fix issue with ProducerConsumerStream/MessageContent not completing after entire request has been sent

dir.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/project.json, src/System.Private.ServiceModel/tests/Common/Scenarios/project.json, src/System.Private.ServiceModel/tests/Common/Unit/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/project.json, src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/project.json, src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/project.json, src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/project.json, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/project.json, src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/project.json, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/project.json, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/project.json
This will move us to the latest package version that contains both @roncain's and @mconnew's recent product PRs that several tests need.
=> Update to version 24308-02

.gitignore, GenerateBuilds.ps1, Packaging.props, build-packages.sh, build.sh, dir.traversal.targets, init-tools.sh, run-test.cmd, run-test.sh
* Covers numerous small changes.
=> Latest CoreFx changes to various shared scripts.

dir.props, dir.traversal.targets
* Essentially a port of Karthik's CoreFx PR #10042
=> Adding default value for FilterToTestTFM property used in VSO runs.

src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfChannelExtensibilityService.cs
* Removing server side Console logging.
=> Clean-up MessageInterceptor test.

netci.groovy
Add new platforms for CI testing, e.g. other versions of Ubuntu, RedHat, etc.
Defaults still to run only 'Windows_NT', 'Ubuntu14.04', 'CentOS7.1', 'OSX' every
PR, and allows one to call:
* "test all outerloop please" - to test all outerloops
* "test all innerloop please" - to test all innerloops
* "test {inner|outer}loop {os} please" - to test a particular innerloop
=> Add new platforms for CI testing

src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj, src/certtest.props, src/test.props
Not ready for review, testing CI.
CI test completes. Ready for review.
=> Automate cert installation

src/certtest.props, src/test.props
* Move the file copy to certtest.props
* Change from taget to Content Copy for Helix to work
=> Change to use Content copy installRootCertificate

src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WSDuplexService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WSRequestReplyService.cs
=> Make WS tests concurrent safe

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd
Usage:
/p: If an existing WCF repo is preferred to be used, use this parameter to provide
the path to a WCF repo.
Examples:
SetupWcfIISHostedService 42 /p:"c:\my\existing\wcf\repo"
:Create IIS hosted service named 'wcfService42' by using existing WCF repo located at "c:\my\existing\wcf\repo"
fixes #1085
=> Add support to use existing repo for IIS hosted WCF test service

netci.groovy
Add switches
/p:SSL_Available=true /p:Root_Certificate_Installed=true
/p:Client_Certificate_installed=true
to CI so tests will always run certificate tests
=> Update netci.groovy to enforce certificate tests in CI

src/System.Private.ServiceModel/src/project.json, src/System.Private.ServiceModel/src/windows/project.json
Consume change made in https://github.com/iamjasonp/corefx/commit/72394d61d5508ca46a42dfb69a476e824d25f216 to get rid of certificate-related issues in WCF
=> Update project.json to take in X509Certificate fix

src/Common/test-runtime/project.json, src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj, src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.rd.xml, src/System.ServiceModel.Duplex/tests/ServiceModel/CallbackBehaviorAttributeTest.cs, src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj, src/System.ServiceModel.Duplex/tests/project.json, src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs, src/System.ServiceModel.Http/tests/project.json, src/System.ServiceModel.NetTcp/tests/project.json, src/System.ServiceModel.Primitives/tests/Channels/CustomBindingTest.cs, src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.cs, src/System.ServiceModel.Primitives/tests/project.json, src/System.ServiceModel.Security/tests/ServiceModel/UpnEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/project.json
The unit tests won't run against netcore50 by default. To run them go to the test project and run...
msbuild  /p:TestTFM=netcore50 /p:TestNugetRuntimeId=win10-x64-aot /t:RebuildAndTest /p:UseDotNetNativeToolchain=true /p:TestWithCore=true
=> Testing xunit for uwp

src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
RuntimeInformation.OSDescription is hard-coded to return a generic
"Microsoft Windows" description when compiled for NET Native. This
masks from our OSID detection which version of Windows is running.
Prior to this fix, we returned "AnyWindows" to indicate we did not
know, but this caused some IssueAttributes to skip Win7 tests.
The fix is to refine the OSID detection slightly when the hard-coded
"Microsoft Windows" description is returned.
Fixes #1459
=> Enhance OSID detection when running under NET Native

src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs
=> Fix reporting for ETW traces in testing

src/System.Private.ServiceModel/tools/CertificateGenerator/App.config, src/System.Private.ServiceModel/tools/scripts/RefreshServerCertificates.cmd, src/System.Private.ServiceModel/tools/scripts/ScheduledRestartWcfSelfHostedService.cmd
Test infrastructure requires that the self-hosted WCF Service be restarted periodically
Commit this script so that it's in source control rather than in somebody's file share
internally :) 
Note that this file is designed to live outside the repo - by convention we place this file into C:\wcftest
skip ci please
cc: @roncain
=> Add script for scheduled self-hosted service restart

netci.groovy
* Add a help job to wcf repo
* Add msbuild.log to archived outerloop jobs
=> Update netci.groovy scripts

Documentation/certificate-generation-resources.md, Documentation/manualtest-guide.md
=> Update certificate generation documentation

src/System.Private.ServiceModel/tools/PRService/pr.ashx
The merge step to get master into a good state was causing an indefinite hang in
certain cases, which would result in 1) git.exe to hang and 2) the PRService to return
a 500 error and cause CI to fail intermittently
This change removes the merge step and replaces it with a force checkout, deletes all
branches, and then checks out to origin/master during the cleanup step. This results in
a clean repo as well as sidesteps the merge step causing the hang
skip ci please
Fixes #1066
=> Update PRService to deal with issues at merge

netci.groovy
=> Update netci.groovy for new branches for outerloop

src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs
=> Add WCF channel keywords to ETW events

dir.props, dir.traversal.targets
=> Fix TestTFM filtering so it works for all and not just netcoreapp

src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs
These lines were altered when I was doing testing of the coreclr EventSource changes and shouldn't have been checked in.
=> Fixing mistake from earlier ETW event source fix

Packaging.props, dir.traversal.targets, init-tools.cmd, init-tools.sh
Just part of the continuing effort to stay in sync with CoreFx.
=> Updates to build scripts from CoreFx.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.4.1.0.cs
* I've done a manual verification and verifed this test now pass in
the manual test.
=> Enable test disabed by active issue 1260

src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/FaultExceptionTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/FaultExceptionTests.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/SynchronizedCollection.cs
* Expose System.ServiceModel.Dispatcher.FaultContractInfo
* Additonal APIs needed for customers to access FaultContractInfo
* Add a scenario test and Unit test for SynchronizedCollection
Fixes #1421
=> Add API System.ServiceModel.Dispatcher.FaultContractInfo

src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd
- Ensure HTTPS binding is created during setup
- Add more output information for better diagnosis
fixes #1514 
skip ci please
=> Improvement of IIS hosted service setup script

Documentation/developer-guide.md, Documentation/scenario-test-guide.md
This PR also includes more detailed instructions
for running tests as UWP.
skip ci please
Fixes #1505
=> Update documentation for new dev workflow

src/System.Private.ServiceModel/src/System/ServiceModel/MessageHeaderArrayAttribute.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MessagePropertyAttribute.cs
First PR for this just adds the classes.  Later PR's will add to contract and test it.
=> Add MessageHeaderArrayAttribute and MessagePropertyAttribute

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/PeerHelpers.cs, src/System.Private.ServiceModel/src/System/ServiceModel/PeerHopCountAttribute.cs
Adds the implementation of PeerHopCountAttribute.
Later PR's will add to public contract and add tests.
This is the first part of issue #1426.
=> Add PeerHopCountAttribute

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ChannelPoolSettings.cs
First step of issue #1416 
Later PR's will add to contract and unit test
=> Add ChannelPoolSettings

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Update docs of package versions for .NET Core 1.1 Preview 1 release

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs
* Root problem was fixed in corefx with issue: dotnet/corefx#4429
* Fixes Issue #470
=> Remove active issue 470.

UpdatePublishedVersions.ps1
* Without these changes the publishing step fails to update the versions repo.
=> Update ps1 script with needed changes.

UpdatePublishedVersions.ps1
* Causing unexpected failure running the script.
=> Remove extra BOM at beginning of file.

src/System.Private.ServiceModel/src/System/ServiceModel/Description/TypeLoader.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Unit/MockEndpointBehavior.cs, src/System.Private.ServiceModel/tests/Common/Unit/TestHelpers.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.4.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/TestTypes.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ReplyBankingData.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/RequestBankingData.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpTestServiceHost.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/MessageContractTest.4.4.0.cs, src/System.ServiceModel.Primitives/tests/TestTypes.4.4.0.cs
Adds MessageHeaderArrayAttribute and MessagePropertyAttribute to public API
Also adds unit tests to verify ContractDescription is correct with these attributes
present.  And adds scenario test to verify fields with new attributes round-trip.
Fixes #1410
=> Add message attribute APIs

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/MessageInspectorTestHelpers.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/MessageInspectorTests.4.4.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/mahjong.cs
* From the old mahjong app code.
=> Add message inspector tests.

Documentation/using-prerelease-wcf-packages.md
Documents how to use WCF packages from myget as well as privately built from the repo.
Fixes #1607
skip ci please
=> Add documentation on using pre-release packages

release-notes/SupportedFeatures-v1.1.0.md
- Note that all links are not working yet as v1.1.0 tags etc are
not there yet.
- I will do a final update once all links are available
Fix #1613
=> Support feature table for v1.1.0

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Update docs of package versions for 1.1 release

src/Common/test-runtime/project.json
* Expected to fix an "exceeds Max_Path" error.
=> Fix a break to UWP runs.

Documentation/building/cross-platform-testing.md
=> Update instructions on running tests cross platform

dependencies.props
* Need to add AppXRunnerVersion to dependencies.props file.
=> Fix UWP F5 runs.

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
* Updating with comments.
* Removing StringBuilder wherever used.
* Use Asserts correctly.
=> Updating ExpectedException tests.

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ChannelBaseTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTestHelpers.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/ClientBaseTests.4.0.0.cs
This class is part of ClientBase<T> and provides a mechanism
for custom channels that do not use dynamic proxy generation.
=> Add tests for ChannelBase<T>

src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/FaultExceptionTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.4.1.0.cs
* Remove StringBuilder
* Add Asserts for validation.
=> Update scenario contract tests.

src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/BinaryEncodingTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/TextEncodingTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/MessageVersionTests.4.0.0.cs
* Remove StringBuilder usage.
* Add Asserts for validation.
=> Updating scenario encoding tests.

src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestHelpers.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.4.1.0.cs
*Remove StringBuilder usage.
*Add Asserts for validation.
=> Updating scenario security tests.

src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.4.1.1.cs
Remove the stringbuilder
Replace the "catch" with a Finally only to do some channel cleanup.
=> Remove the stringbuilder and do some cleanup in DataContractResolverTest

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
* Removed usage of StringBuilder.
* Added comments to better explain what the test does.
* Fixes #398
=> Fixing and updating test to use best practices.

src/System.Private.ServiceModel/tests/Stress/readme.md
Adding readme with a brief overview of the stress and perf tests and instructions on how to setup and start running them.
=> adding readme.md

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfRestartService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfRestartService.cs
* This test can be remove later once it has helped us understand the issue being investigated.
=> Adding a test to validate certain behavior on NetNative.

src/System.Private.ServiceModel/src/Internals/InternalSR.cs
* These static strings are not used anywhere in our code base.
=> Remove internal static strings in InternalSR.cs

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/StreamedFramingRequestChannel.cs
This is a fix for per request leak of nettcp connections in streaming scenario.
=> Fixing #1504 leaking connections in nettcp streaming.

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/Channels/UnderstoodHeadersTest.cs
* Add UnderstoodHeaders to the list of public APIs, implementation already exists.
* Add a unit test to validate the class.
=> Add UnderstoodHeaders API and unit test.

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/MessageContractTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IUnderstoodHeaders.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/UnderstoodHeaders.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/UnderstoodHeadersServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
* UnderstoodHeaders API was recently added to the public contract, was missing scenario tests for it.
=> Add scenario test for UnderstoodHeaders API

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
* It is already fully implemented, just needed to be added to the public contract.
=> Adding SecurityNegotiationException to the public contract.

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
* It looks to be already fully implemented. Testing will be needed to verify functionality.
=> Add ContractDescription.GetContract method to public contract.

src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Program.cs, src/System.Private.ServiceModel/tests/Stress/SharedPoolsOfWCFObjects/Tests/StreamingTest.cs
=> Adding a new Rolling Stress mode

src/System.Private.ServiceModel/src/System/ServiceModel/OperationContractAttribute.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/Description/OperationContractAttributeTest.cs
- System.ServiceModel.Primitives
- System.Private.ServiceModel
=> Adding Session-related methods and types to

src/System.Private.ServiceModel/src/System/ServiceModel/OperationFormatUse.cs, src/System.Private.ServiceModel/src/System/ServiceModel/XmlSerializerFormatAttribute.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
Add `System.ServiceModel.OperationFormatUse` into the contract.
Ref #1549.
=> Add System.ServiceModel.OperationFormatUse.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs
* Enable http ambient credential test as corefx fix is in.
=> Enable tests

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/SetupValidationTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.4.1.0.cs
* Fix certificate installation on OSX10.12  #1886
=> Active issue test cases failing due to issue #1886

README.md
=> Fixes readme.md

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
Fixes #1906 
@dotnet-bot skip CI please
=> Update docs of package versions for 2.0 Preview 1 release

src/Common/test-runtime/project.json, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatSoapTest.cs
=> Enable Test EchoComositeType_XmlSerializerFormat_Soap

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.builds, src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.builds
* Enabling Duplex and Http unit tests first.
=> Enabling UWP tests

Packaging.props, pkg/baseline/packageIndex.json, src/System.Private.ServiceModel/dir.props, src/System.ServiceModel.Duplex/dir.props, src/System.ServiceModel.Http/dir.props, src/System.ServiceModel.NetTcp/dir.props, src/System.ServiceModel.Primitives/dir.props, src/System.ServiceModel.Security/dir.props
Eric and Wes, I particularly want your review for this.
I'm not sure that my changes to packageIndex.json are correct, especially for S.Private.ServiceModel, I got it to pass validation, but...
=> Rev package version to 4.5

pkg/baseline/packageIndex.json
* Added comments for clarity as well.
=> Fix assembly to package version mapping.

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj
* For System.Reflection.DispatchProxy and System.Security.Principal.Windows.
=> Update baseline version of CoreFx packages for ns 1.3.

src/Common/test-runtime/project.json, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs
=> Enable tests that were disabled with CoreFx blocking bugs.

src/System.Private.ServiceModel/src/Internals/System/Runtime/FatalException.cs, src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs, src/System.Private.ServiceModel/src/System/IdentityModel/SecurityMessageSerializationException.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenException.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenValidationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ActionMismatchAddressingException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ActionNotSupportedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ChannelTerminatedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectAbortedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectFaultedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/InvalidBodyAccessException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/EndpointNotFoundException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/InvalidMessageContractException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MessageHeaderException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MustUnderstandSoapException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ProtocolException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/QuotaExceededException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/MessageSecurityException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAccessDeniedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityNegotiationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ServerTooBusyException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ServiceActivationException.cs
* Specifically on WCF Exceptions
=> Remove serializable attribute and throw PNSE.

Packaging.props, dependencies.props
=> Revert "Move to preview3 prerelease label."

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/SessionTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ISessionTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/SessionTestsService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TcpSessionTestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
Had to disable and modify a few tests because of #1962 #1959.
=> Adding duplex session tests

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
Fixes #2007
@dotnet-bot skip ci please
=> Doc update for .NET Core 2.0.0 preview2 release

netci.groovy
* PR #1989 updated the WCF Master branch to all the latest changes needed for buildtoolsv2.
* While this was validated on local environments netci.groovy file changes were necessary for CI.
* Using this PR to identify CI issues and fix them.
=> PR for validating and fixing CI issues.

Packaging.props
release/uwp6.0 will use preview1
=> Update prerelease label to preview2

src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/OSAndFrameworkTests.4.1.1.cs
=> Skip infrastructure test until logic is fixed.

BuildToolsVersion.txt, dir.props, dir.targets, external/corefx/corefx.depproj, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj, tools-local/targetgroups.props
cc: @dagood @StephenBonikowsky @ericstj @weshaggard  
FYI: @zamont 
Same changes made in https://github.com/dotnet/corefx/pull/21836 for corefx, but now in WCF.
=> Renaming uap10.1 to uap10.15138

lab/src/Microsoft.SyndicationFeed/src/ISyndicationFeedFormatter.cs, lab/src/Microsoft.SyndicationFeed/src/ISyndicationFeedReader.cs, lab/src/Microsoft.SyndicationFeed/src/ISyndicationImage.cs, lab/src/Microsoft.SyndicationFeed/src/Rss20/Rss20FeedFormatter.cs, lab/src/Microsoft.SyndicationFeed/src/Rss20/Rss20FeedReader.cs, lab/src/Microsoft.SyndicationFeed/src/SyndicationCategory.cs, lab/src/Microsoft.SyndicationFeed/src/SyndicationLink.cs
Adding Image Interface.
Adding Link Parser Implementation.
Adding Category Parser Implementation.
=> Syndicationfeed Reader - Add Image interface, Link parser, Category Parser

src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.Tests.csproj
* Force these tests to not run in parallel.
* Fixes #2124
=> Fix tests hanging waiting for async responses.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SocketConnection.cs
=> Fixed NullRef in SocketConnection.CancelSendTimer. (#2146)

dependencies.props
This should pick up a fix made by @shmao to serialization in CoreFx.
=> Update to latest CoreFx version to pick-up needed fixes.

external/runtime/runtime.depproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.Tests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.Tests.csproj, src/tests.builds
Al three commits are in Master and have been validated to work as expected.
They are now needed in release/uwp6.0 to enable additional test scenarios in VSTS.
https://github.com/dotnet/wcf/pull/2148
https://github.com/dotnet/wcf/pull/2141
https://github.com/dotnet/wcf/pull/2130
=> Cherry pick prs2148 2141 2130

netci.groovy
This job is producing a build failure...
```
17:00:31   Got manifest file appxmanifest.xml
17:00:31   
17:00:31   FAILED 0x80080204 (The Appx package's manifest is invalid.
17:00:31   
17:00:31   )
```
Disabling until we have time to investigate and fix.
=> Disable UAP CI Job while investigating build failure.

dependencies.props
This just enables test ilc to get autoupdated.
=> Auto update test ILC in dependencies.props

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Doc update for .NET Core 2.0.0 release

release-notes/SupportedFeatures-v2.0.0.md
* 2.0 -> 2.0.0 for all links
* Fix the link to supported OSs.
* Fix the mis-align.
=> Fix feature table

src/System.Private.ServiceModel/tests/Common/Infrastructure/CertificateManager.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalTestDetectors.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/SafeKeychainHandle.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.OSX.cs
Also improved OS detection on OSX and fixed client certificate installation on OSX
=> Sample certificate auth on OSX similar to peer channel

BuildToolsVersion.txt, dependencies.props
Replacement for https://github.com/dotnet/wcf/pull/2251 since I can't update @dotnet-maestro-bot's fork.
=> Master update dependencies

CONTRIBUTING.md
* I get VSO git failures due to using a git command that expects there to be a 'HEAD' which does not yet exist until after the first commit.
* Making a non-intrusive commit to get passed this.
=> First commit to release/1.0.0 after creating new VSO 1.0.0 branch.

init-tools.cmd, init-tools.sh
* Matches changes made in CoreFx in release/1.0.0
=> Updating the init tools scripts with better error checking.

dependencies.props, src/Common/test-runtime/project.json, src/System.ServiceModel.Duplex/ref/project.json, src/System.ServiceModel.Http/ref/project.json, src/System.ServiceModel.NetTcp/ref/project.json, src/System.ServiceModel.Security/ref/project.json
=> Revert "Update CoreFx, CoreSetup, Standard, WCF to servicing-25714-01, servicing-25715-02, preview3-25714-01, stable, respectively (release/2.0.0)"

src/Common/test-runtime/project.json
=> Updating runtime version of Suse being used for tests.

src/Common/test-runtime/project.json
Reverts dotnet/wcf#2330
This didn't complete fix the issue in VSO, so want to revert it and work on the fix in that environment until I get it working then will add a PR here.
=> Revert "Updating runtime version of Suse being used for tests."

release-notes/WCF-Web-Service-Reference-notes.md
=> Release notes for WCF CS in VS2017 15.5 Preview 1

src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs
* Need to detect from OS description
=> Fix OS Detect logic

src/packages.builds, src/publish.proj
* We have to add the packages we wish to build in packages.builds and I needed to have a LKG file in versions repo.
=> With these changes I get successfull builds in VSO.

release-notes/WCF-Web-Service-Reference-notes.md
=> WCF CS release notes for VS 15.5 Preview 2

src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs
@shmao, could you please help review the fix? Thanks!
=> Fix for issue #2356

Packaging.props, pkg/baseline/packageIndex.json, src/packages.builds
* At this point no assembly changes, just making sure we can package and publish new package versions end-to-end including to MyGet via VSTO.
@weshaggard we would like to confirm through our VSTO build pipeline that we can successfully build and publish these packages to MyGet. This gets us ready for the upcoming servicing release.
=> Version forward release/1.1.0 packages for servicing.

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.cs, src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj, src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj, src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj, src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj, src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj, src/packages.builds
* Building non-stable package versions.
=> Package new servicing versioned packages.

dependencies.props
* "Microsoft.xunit.netcore.extensions"
* "Microsoft.DotNet.BuildTools.TestSuite"
=> Update version of some test dependencies.

release-notes/WCF-Web-Service-Reference-notes.md
=> Release notes for WCF CS update in VS 15.6 Preview 1

pkg/baseline/packageIndex.json, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
*Also incremented the version of S.P.SM, facades stayed the same as they have no API changes.
=> Update package versions to stable for next months servicing release.

dependencies.props, pkg/baseline/packageIndex.json, src/System.Private.ServiceModel/dir.props
This pulls in a few last updates made in VSTS but not in GitHub.
=> Porting infrastructure changes made in VSTS.

dependencies.props, init-tools.msbuild, src/publish.proj
* dotnet/corefx/pull/24784
* dotnet/corefx/pull/25031
* dotnet/corefx/pull/26192
=> Porting CoreFx changes to enable publishing to azure feeds.

netci.groovy
Cherry-picking commit "55aac942f9c40f6b0d3f51cdf6db04b637904676" in release/2.1.0 to master.
=> Enable CI tests for PRs in release/2.1.0

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpTransportBindingElement.cs
=> Fix support for using proxies with HTTP transport

src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs
=> Skip test WebSocket_Https_Duplex_TextStreamed

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/ClientBaseTest.cs
=> Expose the Close method on ClientBase<TChannel>

netci.groovy
=> Start PR ID serial numbers at 400 for uwp6.1

netci.groovy
=> Updating netci serial numbers for supported branches.

netci.groovy
* Updating the serial number section of all netci.groovy file in all branches to be the same.
=> Update netci.groovy file WcfPRService starting count.

pkg/baseline/packageIndex.json, pkg/descriptions.json, src/svcutilcore/pkg/GenerateNupkgProps.targets, src/svcutilcore/pkg/svcutilcore.pkgproj
=> Add package for svcutilcore

src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
I went through each of the references. This is the minimum set required for building UAP.
=> Fix references for building UAP

dependencies.props
* Missed one update section in previous PR, this causes an auto-update error.
=> Comment out update step for ProjectNTfsTestILC

Packaging.props
This is to help us differentiate it from the packages built by release/2.1
=> Change from preview1 to uwp60

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Update release notes for 2.1 preview 1

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Fix the tag of 2.1 preview1 in release notes

dependencies.props
* This package was broken recently in CoreFx, use last known good version and disable auto update until it has been fixed.
=> Use LKG version of Microsoft.Private.CoreFx.UAP

UpdateDependencies.ps1
* See dotnet/coreclr#16868 and dotnet/versions#263
=> Adding script to work around TLS 1.2 requirement.

dependencies.props
* Issue #27805 in CoreFx fixed the problem they were having.
* This fixes #2660
=> Re-enable auto update for Microsoft.Private.CoreFx.UAP

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs
Added scenario tests for no auth, digest auth and client certificates.
=> Adding Expect 100-Continue header for client certificates plus tests

src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/ExpectedExceptionTests.4.1.0.cs
Re-enable test case due to issue #2626
=> Cherry-pick of #2787 from master to release/2.1.0

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs
* Replacing HttpClientHandler with SocketsHttpHandler in CoreFx fixes the problem.
=> Remove active issue #2624

src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs
Cherry-pick of Remove active issue #2624
=> Cherry-pick of PR #2798

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs
Active issue on tests failing with same issue.
=> Port of pull request #2796 from Master to 2.1.0

src/System.Private.ServiceModel/tests/Common/Infrastructure/CertificateManager.cs
Expected exception changed on Linux machines
(cherry picked from commit 79f2b91681aebbd805026cacd352e754188118d0)
=> Merge PR #2837 from StephenBonikowsky/stebon/master/FixInfraCertMngr

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs
Re-enable tests fixed by PR #2837
(cherry picked from commit 4b01a8a822d7cf40128d542d968b1fe6163eeb04)
=> Merge PR #2842 from StephenBonikowsky/stebon/master/EnableSkippedTests

Packaging.props, pkg/baseline/baseline.props, src/packages.builds
For supporting building of stable packages.
=> Cherry-picking master changes.

src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/DigestServiceAuthorizationManager.cs
With the new SocketsHttpHandler, the username is now correctly formed when using Digest authentication. This change reverts the workaround in our custom Digest authentication component in our WCF services.
This change validates that #1332 has been fixed.
=> Revert earlier test change which made username validation less strict

src/svcutilcore/pkg/dotnet-svcutil.xmlserializer.pkgproj, src/svcutilcore/src/Configurations.props, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj
Fix #2854
@mconnew @Lxiamail @zhenlan
=> Target dotnet-svcutil.xmlserializer app at dotnetcore.

Packaging.props, src/svcutilcore/dir.props
=> Remove PreleaseLabel for svcutil. Update the overall PreRelaseLabel to preview1.

dependencies.props, dir.props, external/corefx/corefx.depproj, pkg/baseline/packageIndex.json
* Added the feed containing the final packages of dependencies.
=> Update WCF pks and assemblies to stable versions for 2.1 release.

src/svcutilcore/tools/scripts/UpdateSvcutilDotXmlSerializerPackage.ps1
=> Update the version of dependent NetCore version.

src/svcutilcore/tools/scripts/UpdateSvcutilDotXmlSerializerPackage.ps1
=> Update the version of dependent NetCore version. (#2915)

src/svcutilcore/pkg/files/dotnet-svcutil.xmlserializer.runtimeconfig.json
=> Update Microsoft.NETCore.App version in runtimeconfig.json

src/svcutilcore/pkg/files/dotnet-svcutil.xmlserializer.runtimeconfig.json
=> Update Microsoft.NETCore.App version in runtimeconfig.json (#2921)

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs
* Issue #2870, solutions are being investigated, need CI to be green again.
=> Skip tests failing on OSX for known issue.

release-notes/dotnet-svcutil.xmlserializer-notes.md
=> Release notes for dotnet-svcutil.xmlserializer

src/packages.builds
Give more options for deciding which packages to build.
(cherry picked from commit d93b11187f01e7b83b5fa59ca22d1ddb1537626a)
=> Merge PR #2943 from StephenBonikowsky/stebon/2.1.0/ServicePackagesSeparately

release-notes/dotnet-svcutil-notes.md
=> Notes for v1.0.1 release

src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj
* The package version is set using the <PackageVersion> property in Packaging.props
=> Remove old package version element.

pkg/baseline/baseline.packages.props, src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj, src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj, src/System.ServiceModel.Http/ref/System.ServiceModel.Http.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj, src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj
* Increment assembly and package versions.
* Set baseline to just released packages.
partial fix for #3012
=> Post release updates of servicing branch 1.0.0

Packaging.props, dir.props, pkg/baseline/packageIndex.json
* Increment assembly and package versions.
* Added back in comments to the packageIndex.json that had been lost.
=> Roll pkgs and assemblies forward after servicing release.

pkg/baseline/packageIndex.json
* This package hasn't released a stable version yet.
=> Remove section for svcutil in packageIndex.json

src/publish.proj
* From CoreFx: https://github.com/dotnet/corefx/pull/29615
=> Add support for signing of packages in 2.0.0

src/publish.proj
* From CoreFx: https://github.com/dotnet/corefx/pull/29618
=> Add support for signing of packages in 1.1.0

src/publish.proj
* From CoreFx: https://github.com/dotnet/corefx/pull/29619
=> Add support for signing of packages in 1.0.0

pkg/baseline/baseline.packages.props, src/System.Private.ServiceModel/pkg/System.Private.ServiceModel.pkgproj, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/pkg/System.ServiceModel.Duplex.pkgproj, src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Http/pkg/System.ServiceModel.Http.pkgproj, src/System.ServiceModel.Http/ref/System.ServiceModel.Http.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.NetTcp/pkg/System.ServiceModel.NetTcp.pkgproj, src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.Primitives/pkg/System.ServiceModel.Primitives.pkgproj, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Security/pkg/System.ServiceModel.Security.pkgproj, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj
=> Version forward pkgs and assemblies for 1.0.0 branch.

release-notes/WCF-Web-Service-Reference-notes.md
=> D15.8P5 release notes

UpdatePublishedVersions.ps1
This script needed to be modified specifically for the 1.0.0 branch.
=> Update the script for use in the 1.0.0 branch

release-notes/dotnet-svcutil-notes.md
=> v1.0.2 release notes.

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/MessageVersionTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/HttpSoap11WSA10TestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/HttpSoap12WSANoneTestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TcpSoap11WSA10TestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/TcpSoap12WSANoneTestServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
=> Add MessageVersion scenario tests.

netci.groovy
* Broken by buildtools change: https://github.com/dotnet/buildtools/pull/2152
* Ensuring we run on machines with at lease VS 15.7 installed should fix the problem.
=> Specify machine queue to use for Windows CI runs.

netci.groovy
=> Fix queue ids used

src/svcutilcore/pkg/files/dotnet-svcutil.xmlserializer.targets, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/ExportModule.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/InputModule.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/OptionsStatics.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Tool.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/ToolConsole.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/TypeResolver.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/XmlSerializerGenerator.cs, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj, src/svcutilcore/tests/SvcutilTests.cs, src/svcutilcore/tests/dotnet-svcutil.xmlserializer.Tests.csproj
=> Use reflection to call the method in SM.

netci.groovy
* This is causing Jenkins CI to not run.
=> Remove SuSE Linux due to EOL.

eng/install-native-dependencies.sh
* Per https://github.com/dotnet/corefx/blob/master/Documentation/building/unix-instructions.md
=> Also install cmake and pkgconfig for OSX runs.

eng/install-native-dependencies.sh
* cmake 3.12.3 was already installed, I can upgrade the version but don't think I need to.
=> Remove installation of cmake from OSX run.

src/System.Private.ServiceModel/src/Resources/Strings.resx
=> Fix string escaping.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Http/ClientCredentialTypeTests.4.1.0.cs
* Opened git hub issue #3333
* Skipping the test while investigation occurs.
=> Digest test case fails on UWP.

eng/Version.Details.xml, eng/Versions.props, eng/common/PublishToPackageFeed.proj, eng/common/build.ps1, eng/common/build.sh, eng/common/darc-init.ps1, eng/common/darc-init.sh, eng/common/internal/Directory.Build.props, eng/common/internal/Tools.csproj, eng/common/sdk-task.ps1, eng/common/templates/job/job.yml, eng/common/templates/job/publish-build-assets.yml, eng/common/templates/jobs/jobs.yml, eng/common/templates/phases/publish-build-assets.yml, eng/common/templates/steps/send-to-helix.yml, eng/common/templates/steps/telemetry-end.yml, eng/common/templates/steps/telemetry-start.yml, eng/common/tools.ps1, eng/common/tools.sh, global.json
=> Continued changes to AdoptArcade 2/28-1

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IXmlSerFormatAttrServices.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlSerFormatAttrServices.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpXmlSerFormatAttrServiceHost.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/Web.config, src/System.Private.ServiceModel/tools/SelfHostedWcfService/Program.cs
Cherry-pick XmlSerializerFormat test fix from master branch to 2.1.0 branch.
=> Fix XmlSerilizerFormat test issue

src/System.Private.ServiceModel/src/System/ServiceModel/Description/DataContractSerializerOperationBehavior.cs, src/System.ServiceModel.Primitives/ref/Configurations.props, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Netcoreapp.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Primitives/tests/Description/OperationBehaviorTest.cs, src/System.ServiceModel.Primitives/tests/TestTypes.4.4.0.cs
=> Add ISerializationSurrogateProvider api to DataContractSerializerOperationBehavior

src/System.Private.ServiceModel/src/Configurations.props, src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs, src/System.Private.ServiceModel/src/Internals/System/Runtime/InternalBufferManager.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/DataContractSerializerOperationFormatter.cs, src/System.Private.ServiceModel/src/System/ServiceModel/NetTcpBinding.cs
This allows us to go to a single implementation binary
=> Cleaned up #if code and converted to runtime check for NET_NATIVE

eng/pipelines/wcf-base.yml
Change Helix timeout to 10 minutes.
Change build definition timeout to 15 minutes.
=> Update timeouts to reasonable values.

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSHttpTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.0.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.0.0.cs
=> Narrow down test hang issue in Helix.

src/System.Private.ServiceModel/tests/Common/Infrastructure/OSHelper.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/OsID.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/CustomBindingTests.4.1.0.cs
*Use the new OSID for just a couple tests first to verify it works.
=> Add new Mac OS 10.14 to the OsID list.

eng/pipelines/macos.yml, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/NetHttpsBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/DuplexChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/RequestReplyChannelShapeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/WebSocketTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeCertificateCanonicalNameTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/ClientCredentialTypeTests.4.1.1.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/IdentityTests.4.1.1.cs
Add the remaining number of tests to be skipped due to issue #2870
=> Skip tests on Mac OS 10.14

eng/Version.Details.xml, eng/Versions.props, eng/common/CheckSymbols.ps1, eng/common/PublishToSymbolServers.proj, eng/common/SigningValidation.proj, eng/common/SourceLinkValidation.ps1, eng/pipelines/wcf-base.yml, global.json
* Needed for signing validation.
=> Updating to latest Arcade Validation tools.

azure-pipelines-arcade.yml, eng/pipelines/wcf-base.yml, eng/pipelines/windows.yml
* Add the step to publish the builds to the dotnet-core blob storage.
=> Publish builds to feed.

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSHttpTransportWithMessageCredentialSecurityTests.cs
These may be failing in Helix runs only.
Will open an issue for investigation if that is the case.
=> Enable Scenarios/Binding/WS tests

eng/SendToHelix.proj, eng/pipelines/wcf-base.yml
* We need to install certificates on test machines before tests are run on Linux and MacOS machines.
=> Add setup steps for Linux and MacOS test runs.

eng/pipelines/wcf-base.yml
=> Amending prior commit, wrong file edited.

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSHttpTransportWithMessageCredentialSecurityTests.cs
...Scenarios\Binding\WS\TransportWithMessageCredentialSecurity\WSHttpTransportWithMessageCredentialSecurityTests.cs
Https_SecModeTransWithMessCred_UserNameClientCredential_Succeeds
...Scenarios\Binding\WS\TransportWithMessageCredentialSecurity\BasicHttpTransportWithMessageCredentialSecurityTests.cs
Https_SecModeTransWithMessCred_UserNameClientCredential_Succeeds
=> Additional tests skipped for Issue 3610

eng/Version.Details.xml, eng/Versions.props, eng/common/build.ps1, eng/common/build.sh, eng/common/cross/build-rootfs.sh, eng/common/dotnet-install.cmd, eng/common/dotnet-install.ps1, eng/common/dotnet-install.sh, eng/common/init-tools-native.ps1, eng/common/init-tools-native.sh, eng/common/templates/job/job.yml, eng/common/tools.ps1, eng/common/tools.sh, global.json
* ran: darc update-dependencies --channel ".NET Tools - Latest"
=> Updated to latest Arcade tooling.

eng/pipelines/wcf-base.yml, global.json
* Updating due to issue dotnet/arcade#2638
=> Update version of .NET SDK

src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateGenerator.cs
Change certificates to be generated by CertificateGenerator with SHA256WithRSAEncryption signature algorithm
=> Update certs to SHA256WithRSA

eng/Version.Details.xml, eng/Versions.props, eng/common/PublishToPackageFeed.proj, eng/common/cross/arm64/sources.list.buster, eng/common/cross/arm64/sources.list.stretch, eng/common/cross/build-rootfs.sh, eng/common/darc-init.ps1, eng/common/darc-init.sh, eng/common/tools.ps1, eng/common/tools.sh, global.json
* Ran: darc update-dependencies --channel ".NET Tools - Latest"
=> Update to latest versions of .NET Tools

src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecuritySessionClientSettings.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/xunit/WcfTestCase.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSHttpTransportWithMessageCredentialSecurityTests.cs
Also includes a small test infrastructure fix when developing in VS.
=> Fix WS HTTP Sync Context problem

src/System.Private.ServiceModel/tools/scripts/BuildWCFSelfHostedService.cmd, src/System.Private.ServiceModel/tools/scripts/ScheduledRestartWcfSelfHostedService.cmd
* Needed to be updated to account for new "artifacts" folder location.
* Also updating to use newer VS command prompt and tools.
=> Update scripts used on server for updating service changes.

azure-pipelines-arcade.yml, eng/pipelines/linux.yml
* Created a docker file based off of a powershell image so that powershell v6 is built in and can be used by WCF projects.
=> Use docker container for linux build.

eng/pipelines/wcf-base.yml, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj
* Update yaml to fail the "Build Product and Test, Pack and Sign" if there is an error.
=> Change powershell command to use pwsh and update yaml.

src/System.ServiceModel.Security/tests/ServiceModel/SecutityBindingElementTest.cs
Add unit test for SecurityBindingElement.CreateUserNameOverTransportBindingElement().
=> Add unit test for fix of issue1257.

eng/Version.Details.xml, eng/Versions.props, eng/common/post-build/nuget-validation.ps1, eng/common/post-build/promote-build.ps1, eng/common/post-build/trigger-subscriptions.ps1, eng/common/sdl/extract-artifact-packages.ps1, eng/common/templates/job/execute-sdl.yml, eng/common/templates/post-build/channels/internal-servicing.yml, eng/common/templates/post-build/channels/public-dev-release.yml, eng/common/templates/post-build/channels/public-release.yml, eng/common/templates/post-build/channels/public-validation-release.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/post-build/promote-build.yml, eng/common/templates/post-build/trigger-subscription.yml, global.json
* Also added restore sources section to versions.props due to the move to .NET Core SDK Preview5.
=> Update dependencies from dotnet/arcade

eng/pipelines/wcf-base.yml, eng/pipelines/windows.yml
* Only run this for the Windows build.
* Also changed it so that the release build is the one getting published.
=> Add condition to publish-build-assets.yml

eng/pipelines/macos.yml
=> Remove EOL Mac OS version 10.12

eng/pipelines/linux.yml
=> Removed EOL machine queue.

eng/Version.Details.xml, eng/Versions.props, global.json
=> Revert "[master] Update dependencies from dotnet/arcade"

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
=> Update the contract release notes.

release-notes/WCF-Web-Service-Reference-notes.md
Update WCF Web Service Reference release notes for VS 2019 16.3 Preview 2.
=> Update WCF Web Service Reference release notes

azure-pipelines-arcade.yml
Updating the yaml to trigger for the new 3.0 release branch.
=> Update trigger values to reflect the correct branch name.

eng/Versions.props, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.Ref.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj, src/System.ServiceModel.Http/ref/System.ServiceModel.Http.Ref.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj, src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.Ref.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.Ref.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj
* Pkg version is now 4.7.0
* Assembly versions are now 4.7.0.0
=> Update pkg & assembly versions for 3.1

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
* For .NET Core release preview9.final
=> Updating public contract release notes.

src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> [P2] Support System.ServiceModel.Security.SecurityKeyEntropyMode #3862

src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> Add S.SM.S.SecurityTokenParameters to the public contract.

src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> [P2] Support System.ServiceModel.Channels.SecurityBindingElement #3860

src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SymmetricSecurityKey.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
* Also had to make the class public in the implementation.
=> Add S.IM.T.SymmetricSecurityKey to the public contract.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/SecurityBindingElement.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/Tokens/IssuedSecurityTokenParameters.cs, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> Add IssuedSecurityTokenParameters class and SecurityBindingElement.CreateIssuedTokenOverTransportBindingElement

src/System.ServiceModel.Security/tests/ServiceModel/SecureConversationSecurityTokenParametersTest.cs
=> Unit Test for SecureConversationSecurityTokenParameters class

src/System.ServiceModel.Security/tests/ServiceModel/SecurityKeyEntropyModeTest.cs
=> Add unit test for SecurityKeyEntropyMode.

src/System.ServiceModel.Primitives/tests/Channels/BinaryMessageEncodingBindingElementTest.cs
=> Add Unit Test For MaxReadPoolSize and MaxWritePoolSize

src/System.ServiceModel.Security/tests/ServiceModel/SupportingTokenParametersTest.cs
Add Unit Test for issue #3867 
=> add unitest for issue #3867

src/System.Private.ServiceModel/src/System/ServiceModel/Security/Tokens/IssuedSecurityTokenParameters.cs, src/System.ServiceModel.Security/tests/ServiceModel/SecutityBindingElementTest.cs
=> unit test for method CreateIssuedTokenOverTransportBindingElement

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
=> Adding S.SM.FaultException ctor to the public contract.

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Netcoreapp.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
Includes formatting cleanup of System.ServiceModel.Primitives.cs.
Modified project file to show the NetCore only contract source in VS as it doesn't appear normally.
=> Add SecurityTokenProvider Async methods to NetCore

azure-pipelines-arcade.yml
* The new Arcade defined property is 'validateDependsOn'.
=> Update parameter used to trigger 'post-build.yml'.

src/System.ServiceModel.Security/tests/ServiceModel/ServiceModelSecurityTokenRequirementTest.cs
=> Unit Test for ChannelParametersCollectionProperty.

src/System.ServiceModel.Primitives/tests/Security/securityKeyTest.cs
Add unit test for issue #3856 
=> Unit Test for property KeySize and method EncryptKey.

src/System.ServiceModel.Primitives/tests/Security/SecurityTokenRequirementTest.cs
Add unit test for issue #3854 
=> Unit Test for SecurityTokenRequirement.

src/System.ServiceModel.Security/tests/ServiceModel/IssuedSecurityTokenParametersTest.cs
=> Unit test for IssuedSecurityTokenParameters.

src/System.ServiceModel.Primitives/tests/Description/SecurityCredentialsManagerTest.cs
For item #3879.
@StephenBonikowsky , @mconnew , @HongGit
=> Unit test for abstract class SecurityCredentialsManager

src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs
=> Unit test for ctor of FaultException_TDetail

src/System.ServiceModel.Security/tests/ServiceModel/RequireDerivedKeysTest.cs
Add unit test for issue #3865  
=> Unit test for property RequireDerivedKeys.

eng/Versions.props
=> Update preview version for next release.

src/System.ServiceModel.Primitives/tests/IdentityModel/SecurityTokenSerializerTest.cs
For #3855. 
@StephenBonikowsky , @mconnew , @HongGit .
=> Unit test for SecurityTokenSerializer

azure-pipelines-arcade.yml
DevDiv changed the bug area path.
@sunandabalu created a variable group to use.
=> Add group to get SDL validation params.

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/MethodCall.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/ServiceChannelProxy.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/MessagePartDescription.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/ProxyOperationRuntime.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.4.0.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ServiceContractAsyncInterfaces.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/ServiceContractAsyncServices.cs
=> Fix contract methods which use out parameters

eng/Versions.props
Packages for 3.1 preview2 are complete. Re-branding for preview3.
=> Update preview version to preview3.

src/System.ServiceModel.Primitives/tests/IdentityModel/SecurityTokenManagerTest.cs, src/System.ServiceModel.Primitives/tests/IdentityModel/SecurityTokenSerializerTest.cs
For #3852 , and class name fix for SecurityTokenSerializerTest.cs.
=> Unit test for SecurityTokenManager.

src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.cs, src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs, src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> Added EditorBrowsable attribute to unsupported methods to hide from intellisense

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
* They were added initially so it would be easier to enable them later if needed but at this point we are done with adding new APIs for the current WSFederation project.
=> Removed commented out code in public contract source.

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
Wait for release day before merging.
Cherry-pick to release/3.1.0 once it is merged.
Tracked with #4008
=> Update release notes for 3.1 preview2

src/System.Private.ServiceModel/tests/Scenarios/Binding/Custom/Binding.Custom.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/Binding.Http.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/Binding.Tcp.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/Binding.WS.TransportWithMessageCredentialSecurity.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ChannelLayer/Client.ChannelLayer.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/Client.ClientBase.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/ClientBase/DuplexClientBaseTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/Client.ExpectedExceptions.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Client/TypedClient/Client.TypedClient.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Fault/Contract.Fault.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Message/Contract.Message.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/Contract.Service.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/Contract.XmlSerializer.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Encoding/Encoders/Encoding.Encoders.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Encoding/MessageVersion/Encoding.MessageVersion.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageEncoder/Extensibility.MessageEncoder.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/MessageInterceptor/Extensibility.MessageInterceptor.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Extensibility/WebSockets/Extensibility.WebSockets.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Infrastructure/Infrastructure.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Security.TransportSecurity.IntegrationTests.csproj
=> Fix xUnit warning #2009 in test projects.

src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/Contract.Data.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Contract/Data/DataContractTests.4.1.1.cs
=> Fix xUnit warning #2013 for test projects.

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj, src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj, src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj, src/System.ServiceModel.Primitives/tests/ServiceModel/ClientBaseTest.cs, src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj, src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj
=> Fix xUnitWarning #1003 for test projects.

src/System.ServiceModel.Duplex/tests/System.ServiceModel.Duplex.Tests.csproj, src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpBindingTest.cs, src/System.ServiceModel.Http/tests/ServiceModel/BasicHttpsBindingTest.cs, src/System.ServiceModel.Http/tests/System.ServiceModel.Http.Tests.csproj, src/System.ServiceModel.NetTcp/tests/Channels/TcpConnectionPoolSettingsTest.cs, src/System.ServiceModel.NetTcp/tests/System.ServiceModel.NetTcp.Tests.csproj, src/System.ServiceModel.Primitives/tests/Channels/BinaryMessageEncodingBindingElementTest.cs, src/System.ServiceModel.Primitives/tests/Channels/MessageTest.cs, src/System.ServiceModel.Primitives/tests/Channels/TextMessageEncodingBindingElementTest.cs, src/System.ServiceModel.Primitives/tests/System.ServiceModel.Primitives.Tests.csproj, src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj
=> Fix xUnit warning #1014 for test projects.

src/System.ServiceModel.Security/tests/ServiceModel/SpnEndpointIdentityTest.cs, src/System.ServiceModel.Security/tests/System.ServiceModel.Security.Tests.csproj
=> Fix xUnit warning #1019.

src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs
Add scenario test for issue #4005 
=> Scenario Test for "encodingStyle" attribute to generated SOAP message.

build.cmd, eng/build.ps1
This should make building a lot simpler
=> Add build scripts copied from dotnet/runtime

src/System.Private.ServiceModel/src/System/ServiceModel/Description/XmlSerializerOperationBehavior.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IXmlSerFormatAttrServices.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlSerFormatAttrServices.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/XmlSerializerRpcEncWithMessageHeadersServiceHost.cs, src/System.Private.ServiceModel/tools/SelfHostedWcfService/SelfHostedWCFService.csproj
Added a test for scenario.
This change is for #3750
=> Allow message headers with Rpc document and Encoded use

src/svcutilcore/files/dotnet-svcutil.xmlserializer.targets, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj, src/svcutilcore/tests/dotnet-svcutil.xmlserializer.IntegrationTests.csproj
Cherry-picking the commit from PR #4145 that went into master.
We have done package testing and provided a private package to customers.
=> Fix pathing issues with the dotnet-svcutil.xmlserializer tool.

src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj
(cherry picked from commit 8a7fd4f99dd588b2142f5d5bcb80c41896dcd7cd)
This is the cherry pick from PR #4209 into master
=> Update assembly version of xmlserializer tool.

src/svcutilcore/tests/dotnet-svcutil.xmlserializer.IntegrationTests.csproj
=> Fix a build issue with dotnet-svcutil-xmlserializer test

eng/Versions.props, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.Ref.csproj, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj, src/System.ServiceModel.Http/ref/System.ServiceModel.Http.Ref.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj, src/System.ServiceModel.NetTcp/ref/System.ServiceModel.NetTcp.Ref.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.Ref.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj
=> Port PR#4221 to release/3.1.0

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IService1.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/Service1.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpService1Host.cs
@dasetser this is one of the service for test, it's simple and be used for testing the tool against uri with various MetadataQuery format, I think code in this commit should be enough to port the wcf service.
=> Port service for test

src/System.Private.ServiceModel/tests/Common/Infrastructure/Infrastructure.Common.csproj, src/System.Private.ServiceModel/tests/Common/Unit/UnitTests.Common.csproj
This is blocking updating of versions pulled in by Aracade
=> Remove IsTest=true from some utility projects

src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/StreamFormatter.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/Service/ServiceContractTests.4.0.0.cs
=> Fix Read() with count=0 exhausting MessageBodyStream

src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs
=> Fix HttpsChannelFactory to use GetToken as a spinwait was happening

eng/Versioning.props, src/dotnet-svcutil/src/dotnet-svcutil.csproj
add Ship_SvcUtilPackages variable to release pipeline
=> add Ship_SvcUtilPackages variable to release pipeline

eng/Versioning.props
need to align the variable name and value
=> need to align the variable name and value

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj
all need to apply the variable to dotnet-svcutil lib
=> all need to apply the variable to dotnet-svcutil lib

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/Channels/TransportBindingElementTest.cs
For #4265.
@HongGit, @mconnew.
=> Add TransportBindingElement.set_MaxBufferPoolSize.

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs
For issue #4267  [MRS] add M:System.ServiceModel.FaultException.#ctor(System.String).
=> Add FaultException ctor_string

eng/Versions.props, src/System.Private.ServiceModel/src/Internals/System/Runtime/ExceptionTrace.cs, src/System.Private.ServiceModel/src/SMDiagnostics/DiagnosticUtility.cs, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/HttpsChannelFactory.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Channels/TransportSecurityHelpers.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/ServiceUtilHelper.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Https/HttpsTests.4.1.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/TestHost.cs, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> Add support for X509CertificateIdentity with https

src/System.Private.ServiceModel/src/Internals/System/Runtime/ExceptionTrace.cs, src/System.Private.ServiceModel/src/SMDiagnostics/DiagnosticUtility.cs
Build was broken because of two different PR's making the same change in different places a file so duplicate definitions
=> Fix build break

src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf.sln, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/BenchmarksEventSource.cs, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/CertificateInstallUtil.cs, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/ClientContracts.cs, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/Program.cs, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/WCFCorePerf.csproj, src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/benchmarks.wcfcore.Perf.yml
=> WCF Core Perf Testing With Crank

src/System.Private.ServiceModel/src/System/ServiceModel/Description/ContractDescription.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/FaultDescription.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/MessageDescription.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/OperationDescription.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Description/ServiceEndpoint.cs
Fix issue #3987 .
@HongGit , @mconnew .
=> Fix DebuggerDisplay attribute property unavailable issue.

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
Fixing issue #4420. 
@HongGit , @mconnew .
=> Expose Open method for ClientBase<TChannel>

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/FederationHttp/WSFederationHttpBindingTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/Saml2IssuedTokenTestServiceHost.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs
=> Fixed WS2007 helper to use SymmetricKey by default

src/dotnet-svcutil/lib/tests/Baselines/MetadataQuery/mexParam/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/MetadataQuery/mexParam/dotnet-svcutil.params.json, src/dotnet-svcutil/lib/tests/Baselines/MetadataQuery/noQuery/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/MetadataQuery/singleWsdlQuery/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/MetadataQuery/wsdlQuery/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/TFMBootstrapGlobal/tfmGlobal100/SvcutilBootstrapper/SvcutilBootstrapper.csproj, src/dotnet-svcutil/lib/tests/Baselines/TFMBootstrapGlobal/tfmGlobalCoreapp20/SvcutilBootstrapper/SvcutilBootstrapper.csproj, src/dotnet-svcutil/lib/tests/Baselines/TFMBootstrapGlobal/tfmGlobalDefault/SvcutilBootstrapper/SvcutilBootstrapper.csproj, src/dotnet-svcutil/lib/tests/Baselines/TFMBootstrapGlobal/tfmGlobalNetstd20/SvcutilBootstrapper/SvcutilBootstrapper.csproj, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttp/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpDocLitDualNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpDocLitSingleNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpRpcEncDualNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpRpcEncSingleNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpRpcLitDualNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpRpcLitSingleNs/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttpSoap/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttp_4_4_0/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttp/Reference.cs, src/dotnet-svcutil/lib/tests/src/FixupUtil.cs
Supplement to #4473. Fix #4467.
@mconnew, @HongGit
=> dotnet svcutil test baseline fix.

src/System.Private.ServiceModel/src/Internals/System/Runtime/FatalException.cs, src/System.Private.ServiceModel/src/Internals/System/Runtime/Fx.cs, src/System.Private.ServiceModel/src/System/IdentityModel/SecurityMessageSerializationException.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenException.cs, src/System.Private.ServiceModel/src/System/IdentityModel/Tokens/SecurityTokenValidationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ActionMismatchAddressingException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ActionNotSupportedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ChannelTerminatedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectAbortedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/CommunicationObjectFaultedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/InvalidBodyAccessException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/EndpointNotFoundException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/FaultException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/InvalidMessageContractException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MessageHeaderException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/MustUnderstandSoapException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ProtocolException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/QuotaExceededException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/MessageSecurityException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAccessDeniedException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityNegotiationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SessionKeyExpiredException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/Tokens/SecurityContextTokenValidationException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ServerTooBusyException.cs, src/System.Private.ServiceModel/src/System/ServiceModel/ServiceActivationException.cs, src/System.ServiceModel.Primitives/tests/ServiceModel/FaultExceptionTest.cs
Co-authored-by: Matt Connew <matt.connew@microsoft.com>
=> Make all WCF exceptions serializable (#4466)

README.md
It's been a while since it was ASP.NET 5 😅
=> ASP.NET 5 -> ASP.NET Core

src/Common/src/Internals/System/Runtime/Diagnostics/EventTraceActivity.cs, src/Common/src/Internals/System/Runtime/WcfEventSource.cs, src/Common/src/System/ServiceModel/Diagnostics/ExceptionUtility.cs, src/System.Private.ServiceModel/src/Internals/WcfEventSource.cs, src/System.Private.ServiceModel/src/SMDiagnostics/System/ServiceModel/Diagnostics/ExceptionUtility.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityProtocol.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecuritySessionClientSettings.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityUtils.cs, src/System.ServiceModel.Federation/src/Resources/Strings.resx, src/System.ServiceModel.Federation/src/System/IdentityModel/Security/WrapperSecurityCommunicationObject.cs, src/System.ServiceModel.Federation/src/System/Runtime/TaskHelpers.cs, src/System.ServiceModel.Federation/src/System/Runtime/WcfEventSource.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Diagnostics/SecurityTraceRecordHelper.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustChannelSecurityTokenManager.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Security/ISecurityCommunicationObject.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/ServiceDefaults.cs
* Fix memory leak and add async token getting impl
* Make WSFed implementation async and fix memory leak
Co-authored-by: Matt Connew <matt.connew@microsoft.com>
=> Make federation implementation async and fix memory leak (#4481)

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Federation.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
Update release notes in release/3.2 branch
=> update release notes in release/3.2 branch

release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Federation.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md
update release notes for 3.2.1 RTM release
=> update release notes for 3.2.1 release

src/System.Private.ServiceModel/tests/Benchmarks/WCFCorePerf/WCFCorePerf/Program.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfUserNameService.cs
=> fix for two Credscan bugs

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
Fixes #4549
@mconnew, @HongGit.
=> Expose CLientOperation.SyncMethod, BeginMethod, and EndMethod

src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpsBinding.cs, src/System.Private.ServiceModel/src/System/ServiceModel/BasicHttpsSecurity.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/BasicHttpsTransportWithMessageCredentialSecurityTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/BasicHttpsBindingTransportWithMessageCredentialsCertTestServiceHost.cs
For #4469 .
@mconnew , @HongGit.
=> Support for TransportWithMessageCredential in BasicHttpsBinding.

src/System.ServiceModel.Duplex/ref/System.ServiceModel.Duplex.cs
@mconnew Turns out I was missing some change in this PR #4348, could you please help confirm that and review?
=> Make CallbackBehaviorAttribute's ConcurrencyMode property publicly accessible

src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
Adds public api to contract assembly for issue #4562
=> Add HttpTransportBindingElement.Proxy property

src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs
Support targetframewrok net5.0-windows.
=> Support targetframewrok net5.0-windows.

src/dotnet-svcutil/lib/src/Bootstrapper/SvcutilBootstrapper.cs
Fix for support of type-reuse feature (use bootstrapper) in WCF CS context.
co-author: @ZhaodongTian
=> Fix for support of type-reuse feature (use bootstrapper) in WCF CS context

src/dotnet-svcutil/lib/src/Shared/Options/WCFCSUpdateOptions.cs, src/dotnet-svcutil/lib/tests/Baselines/UpdateServiceRefWCFCS/CSServiceReferenceRoundtrip/Connected Services/CSServiceReferenceRoundtrip/ConnectedService.json
=> Fix for support on WCFCS tool.

src/dotnet-svcutil/lib/src/Bootstrapper/SvcutilBootstrapper.cs
=> Update from private to internal for fixing wcf cs authentication issue.

src/System.Private.ServiceModel/src/System/ServiceModel/Security/SecurityAlgorithmSuite.cs, src/System.ServiceModel.Security/ref/System.ServiceModel.Security.cs
=> Add api to SecurityAlgorithmSuite.

src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs, src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs, src/dotnet-svcutil/lib/src/Shared/ProjectDependency.cs
Two fixes:
1. Type loading issue of type reuse authentication scenario in WCF CS
2. Fix #4093
=> Fix type reuse authentication issue in WCF CS context

azure-pipelines-arcade.yml
Will enable automated localization PRs from OneLocBuild. Documentation [here](https://github.com/dotnet/arcade/blob/main/Documentation/OneLocBuild.md).
=> Turn on automated PRs from OneLocBuild

src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs, src/dotnet-svcutil/lib/src/Shared/TargetFrameworkHelper.cs
This is addressing #4387 for dotnet-svcutil tool.
=> Support net6.0-windows and add more netcoreVersion-wcfDependency match pair

src/dotnet-svcutil/lib/src/DebugLogger.cs, src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj
Update the version of packages
=> Update the version of  packages

azure-pipelines-arcade.yml, eng/SendToHelix.proj
Switched MacOS test builds to build on Windows and send to MacOS helix queues.
=> Fix MacOS Builds

eng/Versions.props, release-notes/System.ServiceModel.Duplex.md, release-notes/System.ServiceModel.Federation.md, release-notes/System.ServiceModel.Http.md, release-notes/System.ServiceModel.NetTcp.md, release-notes/System.ServiceModel.Primitives.md, release-notes/System.ServiceModel.Security.md, release-notes/System.Web.Services.Description.md
- get ready for rc2 release
- update rc1 release notes
=> Update rc1 release notes and update release to rc2

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj, src/dotnet-svcutil/src/dotnet-svcutil.csproj
update version for dotnet-svcutil 2.0.3 rtm release
=> update version for dotnet-svcutil 2.0.3 rtm release

src/System.ServiceModel.Http/ref/System.ServiceModel.Http.cs
=> Add missing property BasicHttpsSecurity.Message to public pkg.

eng/Versions.props, src/System.Private.ServiceModel/src/Internals/System/Xml/XmlMtomReader.cs, src/System.Private.ServiceModel/src/System.Private.ServiceModel.csproj
Prompted by issue at dotnet/runtime#59807
While trying to find source of usage of problematic package, I discovered unnecessary security attributes on new MTOM implementation.
=> Update dependencies, small Mtom cleanup

azure-pipelines-arcade.yml
Per https://github.com/dotnet/core-eng/issues/14276.
=> Switch to 1ES R&D pools on main

azure-pipelines-arcade.yml, eng/Versions.props
update branding for the next release
=> update branding for the next release

src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Http/BasicHttpBindingTests.4.0.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfDecompService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfDecompService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/WcfDecompServiceHost.cs
=> Add test for HttpTransportBindingElement.DecompressionEnabled property.

Directory.Build.props, src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalTestDetectors.cs, src/System.Private.ServiceModel/tests/Common/Infrastructure/ConditionalWcfTest.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Tcp_Tests.4.1.0.cs, src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Tcp/StreamingTests.4.1.0.cs
Skip some tests for Linux IIS credential issue till we have a good solution.
=> Fix Linux IIS credential issue.

src/System.Private.ServiceModel/tests/Scenarios/Security/TransportSecurity/Negotiate/NegotiateStream_Http_Tests.4.1.0.cs
=> Fix non standard port test issue on net5 on Linux OS

Directory.Build.props
=> Upgrade the version of the dependented Newtonsoft.json in project.

eng/build.ps1
=> Support specify test project via testscope option.

eng/Versions.props
=> get ready for 4.10 RTM

src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs
=> Support updating the service reference of specified project file.

src/System.Private.ServiceModel/src/System/ServiceModel/Description/CallbackDebugBehavior.cs, src/System.Private.ServiceModel/src/System/ServiceModel/Dispatcher/InvokerUtil.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/Endpoints.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ScenarioTestTypes.cs, src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Client/ExpectedExceptions/CallbackDebugBehaviorTests.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfDuplexService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfDuplexService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/testhosts/DuplexTestServiceHosts.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs
=> Expose ChannelDispatcher and CallbackDebugBehavior.

src/dotnet-svcutil/lib/src/CodeDomFixup/CodeDomVisitors/NamespaceFixer.cs, src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs, src/dotnet-svcutil/lib/src/TypeLoader.cs
Exclude the unavailable types from assembly
=> Typereuse issue

eng/Versions.props
=> Upgrade SystemSecurityCryptographyXmlPackageVersion

eng/Versions.props
Prepare for 6.0.0 preview release.
=> Update to 6.0.0 branding

global.json
Revert SDK version back to 7.0.100-rc.1.22431.12 to see if this could fix the sign issue.
=> revert back to SDK version of 7.0.100-rc.1.22431.12

src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfDuplexService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs, src/System.Private.ServiceModel/tools/scripts/CertificatePrivateKeyPermissions.ps1, src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd
PR to fix WCF tests failure using IIS ApplicationPoolIdentity account.
=> Fix IIS Tests using ApplicationPoolIdentity

src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WSTrustChannelSecurityTokenProvider.cs, src/System.ServiceModel.Federation/src/System/ServiceModel/Federation/WsTrustTokenParameters.cs, src/System.ServiceModel.Federation/tests/WSTrustChannelSecurityTokenProviderTest.cs
=> Enable add Claims and AdditionalRequestParameters to request

eng/Versions.props
Fixes https://github.com/dotnet/wcf/issues/4877
=> Updated netcore System.Security.Cryptography.Xml to 6.0.1

src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.csproj, src/System.ServiceModel.Federation/src/System.ServiceModel.Federation.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.csproj, src/System.ServiceModel.NetFramingBase/src/System.ServiceModel.NetFramingBase.csproj, src/System.ServiceModel.NetNamedPipe/src/System.ServiceModel.NetNamedPipe.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.csproj, src/System.Web.Services.Description/src/System.Web.Services.Description.csproj
See https://twitter.com/davidfowl/status/1547936507821928455 for context 😄
=> Add package descriptions for Nuget packages

src/System.ServiceModel.Primitives/src/Internals/System/Runtime/ExceptionTrace.cs, src/System.ServiceModel.Primitives/src/Internals/System/Xml/XmlMtomWriter.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/Message.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Dispatcher/StreamFormatter.cs
Reference issue: https://github.com/dotnet/wcf/issues/4984
=> Update XmlMtomWriter and StreamFormatter

azure-pipelines-arcade.yml, src/System.ServiceModel.Duplex/src/System.ServiceModel.Duplex.Facade.csproj, src/System.ServiceModel.Federation/src/System.ServiceModel.Federation.csproj, src/System.ServiceModel.Http/src/System.ServiceModel.Http.Facade.csproj, src/System.ServiceModel.NetTcp/src/System.ServiceModel.NetTcp.Facade.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj, src/System.ServiceModel.Security/src/System.ServiceModel.Security.Facade.csproj, src/System.Web.Services.Description/src/System.Web.Services.Description.csproj
In release/4.10
- add package description
- track release/4.* branch
=> updates to release/4.10

src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.Ref.csproj, src/System.ServiceModel.Primitives/src/System.ServiceModel.Primitives.Facade.csproj
=> Remove accidental adding of net7.0 ref

src/System.ServiceModel.NetNamedPipe/src/Resources/strings.resx, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.cs.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.de.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.es.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.fr.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.it.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.ja.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.ko.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.pl.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.pt-BR.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.ru.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.tr.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.zh-Hans.xlf, src/System.ServiceModel.NetNamedPipe/src/Resources/xlf/strings.zh-Hant.xlf, src/System.ServiceModel.NetNamedPipe/src/System.ServiceModel.NetNamedPipe.csproj, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/Channels/NamedPipeChannelFactory.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/Channels/NamedPipeConnectionPoolSettings.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/Channels/NamedPipeTransportBindingElement.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/Channels/PipeConnectionInitiator.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/NamedPipeTransportSecurity.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/NetNamedPipeBinding.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/NetNamedPipeSecurity.cs, src/System.Web.Services.Description/src/System.Web.Services.Description.csproj
Switch to using SupportedOSPlatform attribute and doing runtime OS checks in constructors and throwing if not on Windows
=> Change NetNamedPipe from net6.0-windows to net6.0

src/System.Private.ServiceModel/tests/Scenarios/Binding/WS/TransportWithMessageCredentialSecurity/WSNetTcpTransportWithMessageCredentialSecurityTests.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Security/SecuritySessionClientSettings.cs
=> Fix TWMC when using single threaded sync context

src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.4.0.0.cs, src/System.ServiceModel.NetTcp/src/System/ServiceModel/Channels/SocketConnection.cs
=> Fix disabling send/receive timers after send/receive operations completed

src/dotnet-svcutil/lib/src/CommandProcessorOptions.cs, src/dotnet-svcutil/lib/src/HelpGenerator.cs, src/dotnet-svcutil/lib/src/ImportModule.cs, src/dotnet-svcutil/lib/src/SR.resx, src/dotnet-svcutil/lib/src/Shared/Options/SvcutilOptions.cs
=> Support option to generate only service contracts

src/System.ServiceModel.Http/src/System/ServiceModel/HttpBindingBase.cs
For #5202.
Cc @mconnew, @HongGit
=> Remove interface IBindingRuntimePreferences from HttpBindingBase

src/System.Private.ServiceModel/tools/CertificateGenerator/CertificateGenerator.csproj, src/System.Private.ServiceModel/tools/SelfHostedWcfService/SelfHostedWCFService.csproj, src/System.Private.ServiceModel/tools/scripts/BuildCertUtil.cmd, src/System.Private.ServiceModel/tools/scripts/BuildWCFSelfHostedService.cmd, src/System.Private.ServiceModel/tools/scripts/CleanUpWCFSelfHostedSvc.cmd, src/System.Private.ServiceModel/tools/scripts/RefreshServerCertificates.cmd, src/System.Private.ServiceModel/tools/scripts/ScheduledRestartWcfSelfHostedService.cmd, src/System.Private.ServiceModel/tools/scripts/SetupWcfIISHostedService.cmd, src/System.Private.ServiceModel/tools/scripts/StartWCFSelfHostedSvcDoWork.cmd
Update below full framework target csproj to use SDK style format:
- CertificateGenerator.csproj 
- SelfHostedWCFService.csproj
=> Convert full framework targeted csproj to use SDK-style

src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs
Fix a naming typo and fixing issue #4658.
=> Fix error when targetframework is defined as variable in Directory.Build.props

src/System.ServiceModel.NetTcp/src/PACKAGE.md
Issue #5238.
Add PACKAGE.md to System.ServiceModel.NetTcp package
=> Add PACKAGE.md to System.ServiceModel.NetTcp package

Directory.Build.props, src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/Connection.cs, src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/ConnectionUtilities.cs, src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/SingletonConnectionReader.cs, src/System.ServiceModel.NetNamedPipe/src/System/ServiceModel/Channels/PipeConnection.cs, src/System.ServiceModel.NetTcp/src/System/ServiceModel/Channels/SocketConnection.cs, src/System.ServiceModel.Primitives/ref/System.ServiceModel.Primitives.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/DetectEofStream.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/ProducerConsumerStream.cs
=> Fix NetTcp with certificates on .net 8

src/System.ServiceModel.Http/src/Resources/xlf/Strings.cs.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.de.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.es.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.fr.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.it.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.ja.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.ko.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.pl.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.pt-BR.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.ru.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.tr.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.zh-Hans.xlf, src/System.ServiceModel.Http/src/Resources/xlf/Strings.zh-Hant.xlf
=> Cherry-pick loc change to prepare for release/6.1

src/System.ServiceModel.NetFramingBase/src/System/ServiceModel/Channels/ConnectionPool.cs
=> Catch unhandled exception when closing connection.

src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/Binding.UDS.IntegrationTests.csproj, src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/UDSBindingTests.cs
The GA version fixes some api issues around security mode, so made the changes needed for that too.
=> Updating to GA version of CoreWCF UDS which fixes package dependency issues

eng/Versions.props
setup branding for WCF Client 8.0 release
=> Branding for WCF Client 8.0 release

Directory.Build.props, dotnet-svcutil.xmlserializer.sln, src/svcutilcore/dotnet-svcutil.xmlserializer.sln, src/svcutilcore/files/dotnet-svcutil.xmlserializer.targets, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Options.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/Tool.cs, src/svcutilcore/src/Microsoft/Tools/ServiceModel/SvcUtil/ToolConsole.cs, src/svcutilcore/src/Resources/xlf/Strings.cs.xlf, src/svcutilcore/src/Resources/xlf/Strings.de.xlf, src/svcutilcore/src/Resources/xlf/Strings.es.xlf, src/svcutilcore/src/Resources/xlf/Strings.fr.xlf, src/svcutilcore/src/Resources/xlf/Strings.it.xlf, src/svcutilcore/src/Resources/xlf/Strings.ja.xlf, src/svcutilcore/src/Resources/xlf/Strings.ko.xlf, src/svcutilcore/src/Resources/xlf/Strings.pl.xlf, src/svcutilcore/src/Resources/xlf/Strings.pt-BR.xlf, src/svcutilcore/src/Resources/xlf/Strings.ru.xlf, src/svcutilcore/src/Resources/xlf/Strings.tr.xlf, src/svcutilcore/src/Resources/xlf/Strings.zh-Hans.xlf, src/svcutilcore/src/Resources/xlf/Strings.zh-Hant.xlf, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj, src/svcutilcore/tests/dotnet-svcutil.xmlserializer.IntegrationTests.csproj
Cherry-pick 3 dotnet-svcutil.XmlSerializer fix commits from main branch (tool will support .NET6.0 and earlier .NET Core versions).
=> [Release/6.1] Cherry-pick dotnet-svcutil.XmlSerializer PR from main

src/System.Private.ServiceModel/tests/Scenarios/Binding/UDS/UDSBindingTests.cs
cc: @birojnayak , @mconnew,  @HongGit
=> Update UDS WindowsAuth test to run on Windows only.

System.ServiceModel.sln, src/System.ServiceModel.NetNamedPipe/tests/NetNamedPipeBindingTest.cs, src/System.ServiceModel.NetNamedPipe/tests/System.ServiceModel.NetNamedPipe.Tests.csproj
=> Add NetNamedPipe long path test

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj
Upgrade Nuget.* package to high version for dotnet-svcutil project.
=> Fix CG issue with dotnet-svcutil solution

azure-pipelines-arcade-PR.yml, azure-pipelines-arcade.yml
- add azure-pipeline-arcade-PR.yml
- modify azure-pipeline-arcade.yml file
- separate PR and build pipelines
=> Migrate to 1ES template pipelines

src/dotnet-svcutil/lib/src/FrameworkFork/System.Runtime.Serialization/System/Runtime/Serialization/DataContract.cs, src/dotnet-svcutil/lib/src/FrameworkFork/System.Runtime.Serialization/System/Runtime/Serialization/DictionaryGlobals.cs, src/dotnet-svcutil/lib/src/FrameworkFork/System.Runtime.Serialization/System/Runtime/Serialization/PrimitiveDataContract.cs
=> Add missing integer schema types..

src/dotnet-svcutil/lib/src/Shared/FrameworkInfo.cs, src/dotnet-svcutil/lib/src/Shared/MSBuildProj.cs
=> dotnet-svcutil: resolve targetFramework from Directory.Build.props

src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/MessageHeaders.cs
Added ProtocolException as an inner exception of InvalidOperationException towards header validation to solve the issue #5204
=> Added ProtocolException towards header validation

src/dotnet-svcutil/lib/src/dotnet-svcutil-lib.csproj
Cherry-pick CG issue fix from main branch.
=> [release/6.1] Fix CG issue with dotnet-svcutil solution (#5431)

azure-pipelines-arcade-PR.yml, azure-pipelines-arcade.yml
Update to 1ES pipelines for release/6.1 branch
=> [release/6.1] Update to 1ES pipelines for release/6.1 branch

azure-pipelines-arcade.yml
Fix no loc build issue with release/6.1 branch.
=> fix not loc build issue with release/6.1 branch

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Binding/Tcp/NetTcpBindingTests.4.0.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs, src/System.ServiceModel.Primitives/src/System/ServiceModel/Channels/ServiceChannelProxy.cs
=> Fix sync hang issue after async task method call

src/System.Private.ServiceModel/tests/Common/Infrastructure/testproperties.targets
=> Resolve Line-Breaking in Test Properties File for Semicolon Values

eng/SendToHelix.proj
[4.10] - Replace open branch with internal helix agent pool
=> [4.10] - Replace open branch with internal helix agent pool

azure-pipelines-arcade.yml
Remove tracking branch release/3.*
Enable Policheck and tsa for WCF Client pipeline.
=> Enable Policheck and tsa for WCF Client pipeline

src/System.Private.ServiceModel/tools/PackageChecker/Program.cs
Before this change, it would pull the latest System.ServiceModel dependency from the nuget feeds. Now it will use the local WCF packages in the same folder as the package you are validating. It is presuming the other packages are in the same folder. Might need to loosen that restriction later, but for now it seems reasonable.
=> Improved handling of local dependencies, e.g. Http depending on Primitives.

eng/Versions.props
Setup 8.1.2 branding for release.
=> setup WCF Client 8.1.2 branding

src/svcutilcore/files/dotnet-svcutil.xmlserializer.targets, src/svcutilcore/src/dotnet-svcutil.xmlserializer.csproj
=> [dotnet-svcutil.XmlSerializer] Add support of net9.0

src/System.Private.ServiceModel/tests/Common/Scenarios/ServiceInterfaces.cs, src/System.Private.ServiceModel/tests/Scenarios/Contract/XmlSerializer/XmlSerializerFormatTest.4.1.0.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/IWcfService.cs, src/System.Private.ServiceModel/tools/IISHostedWcfService/App_code/WcfService.cs, src/dotnet-svcutil/lib/tests/Baselines/FederationServiceTest/Saml2IssuedToken_mex/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicHttpsTransSecMessCredsUserName/BasicHttpsTransSecMessCredsUserName/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttp/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeBasicSvcs/BasicHttps/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttp/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttpWebSockets/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttps/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNetHttpSvcs/NetHttpsWebSockets/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WcfRuntimeNettcpTransSecMessCredsUserName/TcpTransSecMessCredsUserName/Reference.cs, src/dotnet-svcutil/lib/tests/Baselines/WsHttpBindingAndws2007HttpBindingTransSecMessCredsUserName/HttpsTransSecMessCredsUserName/Reference.cs
Redo PR #5329 which is old with merging conflicts.
=> Fix EchoMessageResquestWithMessageHeader typo in test

src/dotnet-svcutil/lib/tests/src/dotnet-svcutil-lib.Tests.csproj
This fixes the pipeline failure in PR https://github.com/dotnet/wcf/pull/5806 (Update dependencies from dotnet/arcade)
=> [dotnet-svcutil] Update target framework version for test project

es-metadata.yml
Change requested by bot on internal mirror that needs to be applied to the public repo and mirrored instead of being applied to the internal mirror.
=> Inventory bootstrapping

eng/Versions.props, src/System.ServiceModel.Http/src/CompatibilitySuppressions.xml, src/System.ServiceModel.Primitives/src/CompatibilitySuppressions.xml
=> Rev WCF versioning for -rc build
